var searchData=
[
  ['efficiency_0',['Why This Proves RVV Efficiency',['../md_docs_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['eigen_20decompositions_1',['B. Eliminating $50,000$ Matrix Eigen-Decompositions',['../md_docs_2projection.html#b-eliminating-50000-matrix-eigen-decompositions',1,'']]],
  ['eigen_5fdecomposition_5frvv_2',['eigen_decomposition_rvv',['../namespacervv__pcl.html#ab6bf0c81cf1a0a4c26d0cd950f5e5789',1,'rvv_pcl']]],
  ['elapsed_3',['elapsed',['../structInstructionTimer.html#a8e55a25e37b78cd07ccbcde14e482d12',1,'InstructionTimer']]],
  ['elapsedms_4',['elapsedMs',['../classTimer.html#aff1a7e5d5dbcca1b9a7f679afc2f371a',1,'Timer']]],
  ['elevation_20grid_20export_20pipeline_3a_5',['2. Run Fast 2.5D Elevation Grid Export Pipeline:',['../md_docs_2projection.html#autotoc_md2-run-fast-25d-elevation-grid-export-pipeline',1,'']]],
  ['eliminating_20_2450_20000_24_20matrix_20eigen_20decompositions_6',['B. Eliminating $50,000$ Matrix Eigen-Decompositions',['../md_docs_2projection.html#b-eliminating-50000-matrix-eigen-decompositions',1,'']]],
  ['eliminating_2050_20million_20ransac_20cross_20dot_20products_7',['C. Eliminating 50 Million RANSAC Cross/Dot-Products',['../md_docs_2projection.html#c-eliminating-50-million-ransac-crossdot-products',1,'']]],
  ['emulation_20strong_8',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['emulator_9',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['enabled_10',['New Features Enabled',['../index.html#new-features-enabled',1,'']]],
  ['encode_5fmultipart_5fformdata_11',['encode_multipart_formdata',['../namespaceserve__mcap.html#a66faf58e121c0c523a968f9b1c05151c',1,'serve_mcap']]],
  ['encodemorton3d_12',['encodeMorton3D',['../test__all__3d__branching__approaches_8cpp.html#a65a76cc832f673b942cc1a82bc2f9ed7',1,'test_all_3d_branching_approaches.cpp']]],
  ['encoding_13',['encoding',['../namespaceexport__mcap.html#aa4506cab69a0ac4236ef905eeae21488',1,'export_mcap']]],
  ['end_5fheaders_14',['end_headers',['../classserve__mcap_1_1FoxgloveCORSHandler.html#aa442a5c9fb9bbfa4abfa5b52748ccecb',1,'serve_mcap::FoxgloveCORSHandler']]],
  ['enter_20the_20container_20activate_20the_20environment_15',['4. Enter the container / activate the environment',['../md_docs_2setup.html#autotoc_md4-enter-the-container--activate-the-environment',1,'']]],
  ['entry_16',['Entry',['../structCompactSparse3DGridBench_1_1Entry.html',1,'CompactSparse3DGridBench']]],
  ['environment_17',['4. Enter the container / activate the environment',['../md_docs_2setup.html#autotoc_md4-enter-the-container--activate-the-environment',1,'']]],
  ['environment_20setup_18',['RVPoint Docker Environment Setup',['../md_docs_2setup.html',1,'']]],
  ['eps_5fscale_5f_19',['eps_scale_',['../classrvv__pcl_1_1SpatialHash.html#a4d5764b064b2b5beef84d4e653444e68',1,'rvv_pcl::SpatialHash']]],
  ['error_201_3a_20illegal_20instruction_20',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['error_202_3a_20cannot_20execute_20binary_20file_21',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['error_203_3a_20qemu_20riscv64_3a_20command_20not_20found_22',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['errors_23',['errors',['../namespaceexport__mcap.html#a358aa775b64e512ace33b170ba48b678',1,'export_mcap']]],
  ['errors_20solutions_24',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['estimation_20strong_25',['&lt;strong&gt;Normal Estimation&lt;/strong&gt;',['../instruction_manual.html#normal-estimation',1,'']]],
  ['euclidean_20clustering_20sub_20actions_20stage_209_26',['C. Euclidean Clustering Sub-Actions (Stage 9)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#c-euclidean-clustering-sub-actions-stage-9',1,'']]],
  ['euclidean_5fclustering_2ecpp_27',['euclidean_clustering.cpp',['../euclidean__clustering_8cpp.html',1,'']]],
  ['euclidean_5fclustering_2eh_28',['euclidean_clustering.h',['../euclidean__clustering_8h.html',1,'']]],
  ['euclideanclustering_29',['euclideanclustering',['../classrvv__pcl_1_1EuclideanClustering.html',1,'rvv_pcl::EuclideanClustering'],['../classrvv__pcl_1_1EuclideanClustering.html#a0b91cffb0bb8347d1bee859a1b0af176',1,'rvv_pcl::EuclideanClustering::EuclideanClustering()']]],
  ['evolution_30',['1. Executive Summary &amp; Benchmark Evolution',['../md_docs_2projection.html#autotoc_md1-executive-summary--benchmark-evolution',1,'']]],
  ['example_3a_20what_20happens_20when_20you_20run_20the_20command_31',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['exec_20nochain_20tt_32',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['execute_33',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['execute_20binary_20file_34',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['execution_35',['Scalar Execution',['../instruction_manual.html#scalar-execution',1,'']]],
  ['execution_20⚡_36',['RVV Vector Execution ⚡',['../instruction_manual.html#rvv-vector-execution-',1,'']]],
  ['execution_20command_20breakdown_37',['QEMU Execution Command Breakdown',['../instruction_manual.html#qemu-execution-command-breakdown',1,'']]],
  ['execution_20commands_38',['Execution Commands',['../instruction_manual.html#execution-commands',1,'']]],
  ['execution_20flow_39',['Execution Flow',['../instruction_manual.html#execution-flow',1,'']]],
  ['execution_20loop_20strong_40',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['execution_3a_20voxel_20grid_20test_41',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['executive_20summary_42',['1. Executive Summary',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md1-executive-summary',1,'']]],
  ['executive_20summary_20benchmark_20evolution_43',['1. Executive Summary &amp; Benchmark Evolution',['../md_docs_2projection.html#autotoc_md1-executive-summary--benchmark-evolution',1,'']]],
  ['executive_20summary_20problem_20statement_44',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['expected_20performance_20impact_45',['3. Key Synergy &amp; Expected Performance Impact',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md3-key-synergy--expected-performance-impact',1,'']]],
  ['experiment_20report_46',['RVPoint Pipeline Profiling &amp; Implementation Ablation Experiment Report',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html',1,'']]],
  ['experiment_20work_20log_20future_20finalization_20checklist_47',['6. Ongoing Experiment Work Log &amp; Future Finalization Checklist',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md6-ongoing-experiment-work-log--future-finalization-checklist',1,'']]],
  ['export_48',['export',['../namespaceexport__mcap.html#a8f56f9c86857c5f9496170943bd49cbc',1,'export_mcap']]],
  ['export_20pipeline_3a_49',['2. Run Fast 2.5D Elevation Grid Export Pipeline:',['../md_docs_2projection.html#autotoc_md2-run-fast-25d-elevation-grid-export-pipeline',1,'']]],
  ['export_5fmcap_50',['export_mcap',['../namespaceexport__mcap.html',1,'']]],
  ['export_5fmcap_2epy_51',['export_mcap.py',['../export__mcap_8py.html',1,'']]],
  ['extend_20the_20code_52',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['extensions_20to_20tt_20pointeroctree_20tt_53',['4. API Extensions to &lt;tt&gt;PointerOctree&lt;/tt&gt;',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md4-api-extensions-to-pointeroctree',1,'']]],
  ['extract_54',['extract',['../classrvv__pcl_1_1EuclideanClustering.html#add96d5baeda98924592779e4632cece4',1,'rvv_pcl::EuclideanClustering']]],
  ['extract_5fplane_5finliers_5foutliers_5frvv_55',['extract_plane_inliers_outliers_rvv',['../namespacervv__pcl.html#a88c2472ce35c12d47d44a38d94042bf3',1,'rvv_pcl']]],
  ['extract_5fplane_5finliers_5frvv_56',['extract_plane_inliers_rvv',['../namespacervv__pcl.html#a7037e3ddad1e97e2ad4da67d709fa533',1,'rvv_pcl']]],
  ['extract_5fplane_5foutliers_5frvv_57',['extract_plane_outliers_rvv',['../namespacervv__pcl.html#a270e4b7dfd954cec2f063cedc0e73bd5',1,'rvv_pcl']]],
  ['extractobstaclessoa_58',['extractObstaclesSoA',['../classFusedRVV25DEngine.html#a1df5c35e70822ca6f181c9084d8f31a0',1,'FusedRVV25DEngine']]]
];
