var searchData=
[
  ['o_20test_5fvoxel_5frvv_20tt_20output_20filename_0',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['object_1',['gem5 v24 requires &lt;tt&gt;SEWorkload&lt;/tt&gt; set on the system object',['../md_guides_2session__2026-04-07.html#gem5-v24-requires-seworkload-set-on-the-system-object',1,'']]],
  ['octree_2',['octree',['../md_guides_2AGENT.html#normal-estimation-requires-octree',1,'Normal Estimation Requires Octree'],['../classrvv__pcl_1_1Octree.html#a790970c110caef92f22a11b224aca47b',1,'rvv_pcl::Octree::Octree()'],['../classrvv__pcl_1_1Octree.html',1,'rvv_pcl::Octree']]],
  ['octree_20tt_20strong_3',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['octree_2ecpp_4',['octree.cpp',['../octree_8cpp.html',1,'']]],
  ['octree_5fbuild_5',['octree_build',['../structSpatialIndexResult.html#a90e8e08bfef166c23e54fa24aad11e97',1,'SpatialIndexResult']]],
  ['octree_5fnormals_6',['octree_normals',['../structSpatialIndexResult.html#aacc33b46e56734a3f3e9dc99f8eae6fe',1,'SpatialIndexResult']]],
  ['octreenode_7',['OctreeNode',['../structrvv__pcl_1_1OctreeNode.html',1,'rvv_pcl']]],
  ['of_202026_2004_2007_8',['What&apos;s Done (as of 2026-04-07)',['../md_guides_2AGENT.html#whats-done-as-of-2026-04-07',1,'']]],
  ['of_20arrays_20soa_20vector_20code_9',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['of_20contents_10',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['of_20structures_20aos_20scalar_20code_11',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['on_20rvv_12',['&lt;tt&gt;#error&lt;/tt&gt; Guard on RVV',['../md_guides_2AGENT.html#error-guard-on-rvv',1,'']]],
  ['on_20the_20system_20object_13',['gem5 v24 requires &lt;tt&gt;SEWorkload&lt;/tt&gt; set on the system object',['../md_guides_2session__2026-04-07.html#gem5-v24-requires-seworkload-set-on-the-system-object',1,'']]],
  ['on_20ubuntu_2022_2004_14',['&lt;tt&gt;mkswap -q&lt;/tt&gt; flag does not exist on Ubuntu 22.04',['../md_guides_2session__2026-04-07.html#mkswap--q-flag-does-not-exist-on-ubuntu-2204',1,'']]],
  ['one_20insn_20per_20tb_20tt_15',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['only_16',['Helper Kernels (RVV Only)',['../instruction_manual.html#helper-kernels-rvv-only',1,'']]],
  ['only_20script_20you_20need_17',['The Only Script You Need',['../md_guides_2AGENT.html#the-only-script-you-need',1,'']]],
  ['only_20when_20dockerfile_20changes_18',['Building Docker Image (only when Dockerfile changes)',['../md_guides_2AGENT.html#building-docker-image-only-when-dockerfile-changes',1,'']]],
  ['oom_20killed_20even_20with_20moderate_20parallelism_19',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['oom_20killed_20with_20high_20parallelism_20',['gem5 linker OOM-killed with high parallelism',['../md_guides_2session__2026-04-07.html#gem5-linker-oom-killed-with-high-parallelism',1,'']]],
  ['operator_3c_3c_21',['operator&lt;&lt;',['../structDualStream.html#a6db163d2147bf6cf9580198ac01dd143',1,'DualStream::operator&lt;&lt;(const T &amp;data)'],['../structDualStream.html#aaf7ac796b9841cbf4c81f48b3335f1e7',1,'DualStream::operator&lt;&lt;(std::ostream &amp;(*manip)(std::ostream &amp;))'],['../structDualStream.html#a60f2eb49ac87ed95949b100cf3dd14d2',1,'DualStream::operator&lt;&lt;(const T &amp;v)'],['../structDualStream.html#acab96ee7a8857c2dadb669350b43bce4',1,'DualStream::operator&lt;&lt;(std::ostream &amp;(*m)(std::ostream &amp;))']]],
  ['optimization_3a_20fused_20gather_20filter_22',['Advanced Optimization: Fused Gather-Filter',['../vector_theory.html#advanced-optimization-fused-gather-filter',1,'']]],
  ['optimizations_23',['Key Optimizations',['../pipeline_demo.html#key-optimizations',1,'']]],
  ['optimized_20point_20cloud_20library_24',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['options_20summary_25',['Configuration Options Summary',['../instruction_manual.html#configuration-options-summary',1,'']]],
  ['order_26',['What&apos;s Next (priority order)',['../md_guides_2AGENT.html#whats-next-priority-order',1,'']]],
  ['order_20for_20new_20agents_27',['Recommended Reading Order for New Agents',['../md_guides_2AGENT.html#recommended-reading-order-for-new-agents',1,'']]],
  ['organization_28',['File Organization',['../instruction_manual.html#file-organization',1,'']]],
  ['outlier_20removal_20sor_20strong_29',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['output_30',['output',['../pipeline_demo.html#autotoc_md3-expected-output',1,'3. Expected Output'],['../instruction_manual.html#inspecting-compilation-output',1,'Inspecting Compilation Output']]],
  ['output_20filename_31',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['output_20format_32',['Output format',['../md_guides_2AGENT.html#output-format',1,'']]],
  ['output_5fpng_33',['output_png',['../namespacevisualize__result.html#a16184e23585550b6960543b562a74805',1,'visualize_result']]],
  ['overview_34',['Overview',['../instruction_manual.html#overview',1,'']]]
];
