var searchData=
[
  ['s_20approach_0',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['savepcd_1',['savePCD',['../namespacervv__pcl.html#a8c14b4e55a663b61179a570c0ec7fcef',1,'rvv_pcl']]],
  ['savepcd_20file_5fpath_20points_5fvector_20tt_2',['&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#savepcdfile_path-points_vector',1,'']]],
  ['savepcdrgb_3',['savePCDRGB',['../namespacervv__pcl.html#adb41d632dacd51d705751ef4c2b0b5bc',1,'rvv_pcl']]],
  ['scalar_20code_4',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['scalar_20execution_5',['Scalar Execution',['../instruction_manual.html#scalar-execution',1,'']]],
  ['scalar_5f25d_5fbaseline_2ecpp_6',['scalar_25d_baseline.cpp',['../scalar__25d__baseline_8cpp.html',1,'']]],
  ['scaling_7',['scaling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-d-ransac-plane-fitting-iteration-scaling-1',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-d-ransac-plane-fitting-iteration-scaling',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling']]],
  ['script_20s_20approach_8',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['scripts_20profile_5fpipeline_20py_20tt_9',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]],
  ['search_10',['Ablation B: Spatial Neighbor Search',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-b-spatial-neighbor-search',1,'']]],
  ['search_20methods_20_24n_2018_20542_24_11',['Ablation B: Spatial Neighbor Search Methods ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'']]],
  ['search_20strong_12',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['searcher_5f_13',['searcher_',['../classrvv__pcl_1_1EuclideanClustering.html#a2949073074614c34b5ca9c70979538be',1,'rvv_pcl::EuclideanClustering']]],
  ['searchrecursive_14',['searchRecursive',['../classSIMDOctree8Wide.html#a09e5d46a326a636748a30472b975d858',1,'SIMDOctree8Wide']]],
  ['segment_15',['segment',['../classBenchmarkScalar25D.html#af79d54c0268f074532fb33e9f2e90036',1,'BenchmarkScalar25D']]],
  ['segmentground_16',['segmentGround',['../classSweepTurboGrid.html#ad4edbc2ca77ba63ef65c5d46918745a7',1,'SweepTurboGrid']]],
  ['segmentobstacles_17',['segmentObstacles',['../classBenchmarkFusedRVV.html#a4be6fd2882a0c8947fc871a5e4ecfda3',1,'BenchmarkFusedRVV']]],
  ['selection_3a_20linux_20vs_20bare_20metal_18',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['serialization_20results_19',['3. Serialization &amp; Results',['../instruction_manual.html#autotoc_md3-serialization--results',1,'']]],
  ['serve_5flocal_20',['serve_local',['../namespaceserve__mcap.html#ab765f5181efd048aa005ba3699b6f5f1',1,'serve_mcap']]],
  ['serve_5fmcap_21',['serve_mcap',['../namespaceserve__mcap.html',1,'']]],
  ['serve_5fmcap_2epy_22',['serve_mcap.py',['../serve__mcap_8py.html',1,'']]],
  ['set_20vector_20length_23',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['setbuildepsilon_24',['setbuildepsilon',['../classrvv__pcl_1_1PointerOctree.html#abfac44079cf7734475cf10d3483b2b65',1,'rvv_pcl::PointerOctree::setBuildEpsilon()'],['../classrvv__pcl_1_1Octree.html#a0fb9ac6ecaf5822aa10f4c8e7c89701f',1,'rvv_pcl::Octree::setBuildEpsilon()']]],
  ['setclustertolerance_25',['setClusterTolerance',['../classrvv__pcl_1_1EuclideanClustering.html#a0d9b56e4c283a088ba2c5f1141fe606c',1,'rvv_pcl::EuclideanClustering']]],
  ['sethashprimes_26',['setHashPrimes',['../classrvv__pcl_1_1SpatialHash.html#a03f5b2ec370557f10d31261d69b902ea',1,'rvv_pcl::SpatialHash']]],
  ['setinputcloud_27',['setinputcloud',['../classrvv__pcl_1_1SpatialHash.html#a3bbba309026c48c337cd535e7c9b17b6',1,'rvv_pcl::SpatialHash::setInputCloud()'],['../classrvv__pcl_1_1PointerOctree.html#a29b289790d88cec70ba0b11bf066442b',1,'rvv_pcl::PointerOctree::setInputCloud()'],['../classrvv__pcl_1_1CaravanPointerOctree.html#ae7e3d6da9113ff28c8dc5b07b5551fae',1,'rvv_pcl::CaravanPointerOctree::setInputCloud()'],['../classrvv__pcl_1_1Octree.html#aa607901983d3865078eeca2228260b27',1,'rvv_pcl::Octree::setInputCloud()'],['../classrvv__pcl_1_1EuclideanClustering.html#af86f172d8e4b2ade3d2782233dfd1676',1,'rvv_pcl::EuclideanClustering::setInputCloud()'],['../classrvv__pcl_1_1CaravanRadiusSearch.html#a6a5212079bd396902b14dfba4ff69ffd',1,'rvv_pcl::CaravanRadiusSearch::setInputCloud()']]],
  ['setmaxclustersize_28',['setMaxClusterSize',['../classrvv__pcl_1_1EuclideanClustering.html#adb58b2501233ed2f386828f4761e254d',1,'rvv_pcl::EuclideanClustering']]],
  ['setmaxdepth_29',['setmaxdepth',['../classrvv__pcl_1_1Octree.html#ad88650c2708174d17c74dbafffbdeb45',1,'rvv_pcl::Octree::setMaxDepth()'],['../classrvv__pcl_1_1PointerOctree.html#aaa48b4d845e43a8960ba513fc21ab4bb',1,'rvv_pcl::PointerOctree::setMaxDepth(int d)']]],
  ['setmaxpointsperleaf_30',['setmaxpointsperleaf',['../classrvv__pcl_1_1PointerOctree.html#aebbaf45f296c6ca44de4c0d8e368d10f',1,'rvv_pcl::PointerOctree::setMaxPointsPerLeaf()'],['../classrvv__pcl_1_1Octree.html#af5bba9b1fbe08da029bded7a47b69a1a',1,'rvv_pcl::Octree::setMaxPointsPerLeaf()']]],
  ['setminclustersize_31',['setMinClusterSize',['../classrvv__pcl_1_1EuclideanClustering.html#a504f93403bc9e92bfa4ba606b2ef1eb1',1,'rvv_pcl::EuclideanClustering']]],
  ['setneighborsearch_32',['setneighborsearch',['../classrvv__pcl_1_1EuclideanClustering.html#af0a3894a2cae1d406b994c4a67a1ca2b',1,'rvv_pcl::EuclideanClustering::setNeighborSearch(const PointerOctree *search)'],['../classrvv__pcl_1_1EuclideanClustering.html#a8ef65c7a148ea107591e9af367143c49',1,'rvv_pcl::EuclideanClustering::setNeighborSearch(const Octree *search)']]],
  ['setup_33',['setup',['../index.html#️-installation--setup',1,'🛠️ Installation &amp; Setup'],['../md_docs_2setup.html',1,'RVPoint Docker Environment Setup']]],
  ['setup_20and_20verification_34',['6. gem5 setup and verification',['../md_docs_2setup.html#autotoc_md6-gem5-setup-and-verification',1,'']]],
  ['setup_20ubuntu_2024_2004_35',['WSL2 Setup (Ubuntu 24.04)',['../index.html#wsl2-setup-ubuntu-2404',1,'']]],
  ['setup_2emd_36',['setup.md',['../setup_8md.html',1,'']]],
  ['shared_20tile_20aabb_37',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['simdoctree8wide_38',['simdoctree8wide',['../classSIMDOctree8Wide.html#a8933bc3bfd3f5bd3c8b0cfe3ef26f576',1,'SIMDOctree8Wide::SIMDOctree8Wide()'],['../classSIMDOctree8Wide.html',1,'SIMDOctree8Wide']]],
  ['simdoctreenode8wide_39',['SIMDOctreeNode8Wide',['../structSIMDOctreeNode8Wide.html',1,'']]],
  ['simple_5feigen3x3_5fsmallest_40',['simple_eigen3x3_smallest',['../namespacervv__pcl.html#ac196c9ab0cbb077b7b7cc78ac9a07d67',1,'rvv_pcl']]],
  ['simple_5fpcd_5floader_2eh_41',['simple_pcd_loader.h',['../simple__pcd__loader_8h.html',1,'']]],
  ['sizes_42',['sizes',['../structrvv__pcl_1_1detail_1_1PCDHeader.html#a92476cba379721fc551f708cbd3c9491',1,'rvv_pcl::detail::PCDHeader']]],
  ['soa_20structure_43',['Create SoA Structure',['../instruction_manual.html#create-soa-structure',1,'']]],
  ['soa_20vector_20code_44',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['soabuffer_45',['SoABuffer',['../structSoABuffer.html',1,'']]],
  ['solution_3a_20trace_20based_20counting_46',['The Solution: Trace-Based Counting',['../md_docs_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['solution_3a_20tt_20vluxei32_20tt_20indexed_20load_47',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['solutions_48',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['sor_49',['sor',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-c-statistical-outlier-removal-sor',1,'Ablation C: Statistical Outlier Removal (SOR)'],['../vector_theory.html#integration-in-sor',1,'Integration in SOR']]],
  ['sor_20implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_50',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['sor_20strong_51',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['sor_5fgrid_5fcaravan_52',['sor_grid_caravan',['../namespacervv__pcl.html#ae83e3649ed3dec8e31b21dda36a1b61f',1,'rvv_pcl']]],
  ['sor_5foctree_53',['sor_octree',['../namespacervv__pcl.html#a51b5cb32a6bad0fb8eb39a5ea8df05e2',1,'rvv_pcl']]],
  ['sor_5fpointer_5foctree_54',['sor_pointer_octree',['../namespacervv__pcl.html#a5bde591375b5dad1052e67e3f8ebfc50',1,'rvv_pcl']]],
  ['sor_5frvv_55',['sor_rvv',['../namespacervv__pcl.html#a10fef2e1c9e7aec2b93d045a7ac1fbad',1,'rvv_pcl']]],
  ['sor_5fsc_56',['sor_sc',['../namespacervv__pcl.html#a311c448d07adeb6a74fcea87f25c1f3c',1,'rvv_pcl']]],
  ['sor_5fspatial_5fhash_57',['sor_spatial_hash',['../namespacervv__pcl.html#acaaf6338c8d633849a34e1244fcbc0b8',1,'rvv_pcl']]],
  ['sorfilter_58',['sorFilter',['../classrvv__pcl_1_1CaravanPointerOctree.html#a2f824eabd809883d53bfd1a4cf3c74d0',1,'rvv_pcl::CaravanPointerOctree']]],
  ['source_20files_20input_59',['5. Source Files - Input',['../instruction_manual.html#autotoc_md5-source-files---input',1,'']]],
  ['spatial_20indexing_60',['Spatial Indexing',['../instruction_manual.html#spatial-indexing',1,'']]],
  ['spatial_20neighbor_20search_61',['Ablation B: Spatial Neighbor Search',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-b-spatial-neighbor-search',1,'']]],
  ['spatial_20neighbor_20search_20methods_20_24n_2018_20542_24_62',['Ablation B: Spatial Neighbor Search Methods ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'']]],
  ['spatial_20tree_20construction_20tt_20octree_3a_3abuild_20tt_63',['A. Spatial Tree Construction (&lt;tt&gt;Octree::build&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#a-spatial-tree-construction-octreebuild',1,'']]],
  ['spatial_5fhashing_2ecpp_64',['spatial_hashing.cpp',['../spatial__hashing_8cpp.html',1,'']]],
  ['spatialhash_65',['spatialhash',['../classrvv__pcl_1_1SpatialHash.html',1,'rvv_pcl::SpatialHash'],['../classrvv__pcl_1_1SpatialHash.html#a5c29a96155ecf8bdd83a8b2a1febe975',1,'rvv_pcl::SpatialHash::SpatialHash()']]],
  ['spatialhash_20tt_20strong_66',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['specification_67',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['speedup_68',['2. Why &lt;tt&gt;pipeline_export&lt;/tt&gt; Capped at ~1.6× Speedup',['../md_docs_2projection.html#autotoc_md2-why-pipeline_export-capped-at-16-speedup',1,'']]],
  ['splitby3_69',['splitBy3',['../test__all__3d__branching__approaches_8cpp.html#a599ba77a8e32c7dfa9859238cb5752f2',1,'test_all_3d_branching_approaches.cpp']]],
  ['src_20include_20profiler_20h_20tt_70',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['src_20include_20tt_20include_20directory_71',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['stage_201_3a_20preprocessing_72',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]],
  ['stage_202_3a_20compilation_73',['Stage 2: Compilation',['../instruction_manual.html#stage-2-compilation',1,'']]],
  ['stage_203_3a_20assembly_74',['Stage 3: Assembly',['../instruction_manual.html#stage-3-assembly',1,'']]],
  ['stage_204_3a_20linking_75',['Stage 4: Linking',['../instruction_manual.html#stage-4-linking',1,'']]],
  ['stage_208_76',['B. RANSAC Sub-Actions (Stage 8)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#b-ransac-sub-actions-stage-8',1,'']]],
  ['stage_209_77',['C. Euclidean Clustering Sub-Actions (Stage 9)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#c-euclidean-clustering-sub-actions-stage-9',1,'']]],
  ['stage_20breakdown_20across_20configurations_78',['Stage Breakdown Across Configurations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#stage-breakdown-across-configurations',1,'']]],
  ['stage_20sub_20stage_20micro_20timing_20breakdown_79',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['stage_20timing_20matrix_80',['High-Level Stage Timing Matrix',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#high-level-stage-timing-matrix',1,'']]],
  ['stages_81',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['standardized_20development_20workflow_82',['1. Standardized Development Workflow',['../instruction_manual.html#autotoc_md1-standardized-development-workflow',1,'']]],
  ['start_83',['start',['../instruction_manual.html#program-start',1,'Program Start'],['../classTimer.html#a3a8b5272198d029779dc9302a54305a8',1,'Timer::start()'],['../structInstructionTimer.html#a7168bb762d280110c7b13e5f9b159f48',1,'InstructionTimer::start']]],
  ['start_20recommended_84',['Quick Start (Recommended)',['../index.html#quick-start-recommended',1,'']]],
  ['statement_85',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['statistical_20outlier_20removal_20sor_86',['Ablation C: Statistical Outlier Removal (SOR)',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-c-statistical-outlier-removal-sor',1,'']]],
  ['statistical_20outlier_20removal_20sor_20implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_87',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['statistical_20outlier_20removal_20sor_20strong_88',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['statistical_5foutlier_5fremoval_2ecpp_89',['statistical_outlier_removal.cpp',['../statistical__outlier__removal_8cpp.html',1,'']]],
  ['step_20by_20step_20execution_3a_20voxel_20grid_20test_90',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['steps_20for_20finalization_3a_91',['Next Steps for Finalization:',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#next-steps-for-finalization',1,'']]],
  ['steps_20for_20implementation_92',['5. Next Steps for Implementation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md5-next-steps-for-implementation',1,'']]],
  ['steps_20manual_93',['Detailed Verification Steps (Manual)',['../index.html#detailed-verification-steps-manual',1,'']]],
  ['strategies_20_24n_2018_20542_24_94',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['strip_20mining_20pattern_95',['1. Strip Mining Pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'']]],
  ['strong_20a_20clean_20build_20targeting_20gcc_2014_20strong_96',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['strong_20adding_20a_20new_20algorithm_20strong_97',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['strong_20b_20running_20with_20system_20libraries_20strong_98',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['strong_20class_20tt_20octree_20tt_20strong_99',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['strong_20class_20tt_20spatialhash_20tt_20strong_100',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['strong_20normal_20estimation_20strong_101',['&lt;strong&gt;Normal Estimation&lt;/strong&gt;',['../instruction_manual.html#normal-estimation',1,'']]],
  ['strong_20phase_201_3a_20initialization_20strong_102',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['strong_20phase_202_3a_20instruction_20execution_20loop_20strong_103',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['strong_20phase_203_3a_20system_20call_20translation_20strong_104',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['strong_20phase_204_3a_20vector_20instruction_20emulation_20strong_105',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['strong_20radius_20search_20strong_106',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['strong_20ransac_20plane_20fitting_20strong_107',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['strong_20statistical_20outlier_20removal_20sor_20strong_108',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['strong_20voxel_20grid_20downsampling_20strong_109',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['struct_20pointcloudsoa_20tt_110',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['struct_20pointxyz_20tt_111',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['structure_112',['structure',['../index.html#autotoc_md-project-structure',1,'📂 Project Structure'],['../instruction_manual.html#component-structure',1,'Component Structure'],['../instruction_manual.html#create-soa-structure',1,'Create SoA Structure']]],
  ['structure_20of_20arrays_20soa_20vector_20code_113',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['structures_114',['structures',['../instruction_manual.html#data-structures-1',1,'Data Structures'],['../instruction_manual.html#data-structures',1,'Data Structures']]],
  ['structures_20aos_20scalar_20code_115',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['sub_20action_20micro_20timing_20analysis_116',['Sub-Action Micro-Timing Analysis',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#sub-action-micro-timing-analysis',1,'']]],
  ['sub_20actions_20stage_208_117',['B. RANSAC Sub-Actions (Stage 8)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#b-ransac-sub-actions-stage-8',1,'']]],
  ['sub_20actions_20stage_209_118',['C. Euclidean Clustering Sub-Actions (Stage 9)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#c-euclidean-clustering-sub-actions-stage-9',1,'']]],
  ['sub_20stage_20micro_20timing_20breakdown_119',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['subtraction_120',['3. Baseline Subtraction',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md3-baseline-subtraction',1,'']]],
  ['summary_121',['summary',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md1-executive-summary',1,'1. Executive Summary'],['../instruction_manual.html#configuration-options-summary',1,'Configuration Options Summary']]],
  ['summary_20benchmark_20evolution_122',['1. Executive Summary &amp; Benchmark Evolution',['../md_docs_2projection.html#autotoc_md1-executive-summary--benchmark-evolution',1,'']]],
  ['summary_20problem_20statement_123',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['summary_20table_124',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['summary_3a_20qemu_20command_20breakdown_125',['Summary: QEMU Command Breakdown',['../instruction_manual.html#summary-qemu-command-breakdown',1,'']]],
  ['sweepturbogrid_126',['sweepturbogrid',['../classSweepTurboGrid.html#a0f486dfde5a2ced0af30a5b6169501f2',1,'SweepTurboGrid::SweepTurboGrid()'],['../classSweepTurboGrid.html',1,'SweepTurboGrid']]],
  ['synergy_20expected_20performance_20impact_127',['3. Key Synergy &amp; Expected Performance Impact',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md3-key-synergy--expected-performance-impact',1,'']]],
  ['system_20call_20translation_20strong_128',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['system_20libraries_20strong_129',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]]
];
