var searchData=
[
  ['o_20test_5fvoxel_5frvv_20tt_20output_20filename_0',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['objectives_1',['1. Overview &amp; Objectives',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md1-overview--objectives',1,'']]],
  ['octree_2',['octree',['../classrvpoint_1_1Octree.html#a86cb94214b6e6188830048d0c9aa69cd',1,'rvpoint::Octree::Octree()'],['../classrvpoint_1_1Octree.html',1,'rvpoint::Octree']]],
  ['octree_20pipeline_3a_3',['3. Run Original Hierarchical Octree Pipeline:',['../md_docs_2projection.html#autotoc_md3-run-original-hierarchical-octree-pipeline',1,'']]],
  ['octree_20traversal_20with_20shared_20tile_20aabb_4',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['octree_20tt_20strong_5',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['octree_2ecpp_6',['octree.cpp',['../octree_8cpp.html',1,'']]],
  ['octree_2eh_7',['octree.h',['../octree_8h.html',1,'']]],
  ['octree_3a_3abuild_20tt_8',['A. Spatial Tree Construction (&lt;tt&gt;Octree::build&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#a-spatial-tree-construction-octreebuild',1,'']]],
  ['octree_5fcompute_5fms_9',['octree_compute_ms',['../structBenchmarkRow.html#a623d1b15ae1a380b5cc816c249fcdb37',1,'BenchmarkRow']]],
  ['octreenode_10',['OctreeNode',['../structrvpoint_1_1OctreeNode.html',1,'rvpoint']]],
  ['of_20arrays_20soa_20vector_20code_11',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['of_20contents_12',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['of_20structures_20aos_20scalar_20code_13',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['one_20insn_20per_20tb_20tt_14',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['ongoing_20experiment_20work_20log_20future_20finalization_20checklist_15',['6. Ongoing Experiment Work Log &amp; Future Finalization Checklist',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md6-ongoing-experiment-work-log--future-finalization-checklist',1,'']]],
  ['only_16',['Helper Kernels (RVV Only)',['../instruction_manual.html#helper-kernels-rvv-only',1,'']]],
  ['operator_28_29_17',['operator()',['../structVoxelHashFunc.html#a819103c22c27eca84ddaa3479cd4697a',1,'VoxelHashFunc']]],
  ['operator_3c_18',['operator&lt;',['../structLinearMortonOctree_1_1PointKey.html#a1b66524c5593986cdec7957afaa0ebfd',1,'LinearMortonOctree::PointKey']]],
  ['operator_3d_3d_19',['operator==',['../structVoxelHash3D.html#a7b9f1c3e2e6a0d77876569c9674cb12e',1,'VoxelHash3D']]],
  ['opt_20gem5_20tt_20binary_20—_20known_20limitation_20',['6b. The bind-mounted &lt;tt&gt;/opt/gem5&lt;/tt&gt; binary — known limitation',['../md_docs_2setup.html#autotoc_md6b-the-bind-mounted-optgem5-binary--known-limitation',1,'']]],
  ['optimization_20recommendations_21',['4. Targeted Architectural Optimization Recommendations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md4-targeted-architectural-optimization-recommendations',1,'']]],
  ['optimization_3a_20fused_20gather_20filter_22',['Advanced Optimization: Fused Gather-Filter',['../vector_theory.html#advanced-optimization-fused-gather-filter',1,'']]],
  ['optimized_20point_20cloud_20library_23',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['options_20summary_24',['Configuration Options Summary',['../instruction_manual.html#configuration-options-summary',1,'']]],
  ['organization_25',['File Organization',['../instruction_manual.html#file-organization',1,'']]],
  ['original_20hierarchical_20octree_20pipeline_3a_26',['3. Run Original Hierarchical Octree Pipeline:',['../md_docs_2projection.html#autotoc_md3-run-original-hierarchical-octree-pipeline',1,'']]],
  ['orthogonal_20projection_20_24_20mathbb_20r_203_20rightarrow_20mathbb_20r_202_24_27',['A. Orthogonal Projection ($\mathbb{R}^3 \rightarrow \mathbb{R}^2$)',['../md_docs_2projection.html#a-orthogonal-projection-mathbbr3-rightarrow-mathbbr2',1,'']]],
  ['outlier_20removal_20sor_28',['Ablation C: Statistical Outlier Removal (SOR)',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-c-statistical-outlier-removal-sor',1,'']]],
  ['outlier_20removal_20sor_20implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_29',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['outlier_20removal_20sor_20strong_30',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['output_31',['Inspecting Compilation Output',['../instruction_manual.html#inspecting-compilation-output',1,'']]],
  ['output_20filename_32',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['overhead_20compile_20time_20toggle_20tt_20src_20include_20profiler_20h_20tt_33',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['overview_34',['Overview',['../instruction_manual.html#overview',1,'']]],
  ['overview_20objectives_35',['1. Overview &amp; Objectives',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md1-overview--objectives',1,'']]]
];
