var searchData=
[
  ['a_0',['a',['../structPlane3D.html#afc228f1f51f077b673029eca0552b567',1,'Plane3D']]],
  ['a_20clean_20build_20targeting_20gcc_2014_20strong_1',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['a_20new_20algorithm_20strong_2',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['a_20orthogonal_20projection_20_24_20mathbb_20r_203_20rightarrow_20mathbb_20r_202_24_3',['A. Orthogonal Projection ($\mathbb{R}^3 \rightarrow \mathbb{R}^2$)',['../md_docs_2projection.html#a-orthogonal-projection-mathbbr3-rightarrow-mathbbr2',1,'']]],
  ['a_20query_20tiling_20tile_20aabb_20computation_4',['A. Query Tiling &amp; Tile AABB Computation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#a-query-tiling--tile-aabb-computation',1,'']]],
  ['a_20spatial_20tree_20construction_20tt_20octree_3a_3abuild_20tt_5',['A. Spatial Tree Construction (&lt;tt&gt;Octree::build&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#a-spatial-tree-construction-octreebuild',1,'']]],
  ['a_20vectorized_202d_20coordinate_20quantization_20tt_20insertcloudrvv_20tt_6',['A. Vectorized 2D Coordinate Quantization (&lt;tt&gt;insertCloudRVV&lt;/tt&gt;)',['../md_docs_2projection.html#a-vectorized-2d-coordinate-quantization-insertcloudrvv',1,'']]],
  ['a_3a_20voxel_20grid_20downsampling_7',['Ablation A: Voxel Grid Downsampling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-a-voxel-grid-downsampling',1,'']]],
  ['a_3a_20voxel_20grid_20downsampling_20_24n_20114_20278_20to_2018_20542_24_8',['Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'']]],
  ['aabb_9',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['aabb_20computation_10',['A. Query Tiling &amp; Tile AABB Computation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#a-query-tiling--tile-aabb-computation',1,'']]],
  ['ablation_20a_3a_20voxel_20grid_20downsampling_11',['Ablation A: Voxel Grid Downsampling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-a-voxel-grid-downsampling',1,'']]],
  ['ablation_20a_3a_20voxel_20grid_20downsampling_20_24n_20114_20278_20to_2018_20542_24_12',['Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'']]],
  ['ablation_20b_3a_20spatial_20neighbor_20search_13',['Ablation B: Spatial Neighbor Search',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-b-spatial-neighbor-search',1,'']]],
  ['ablation_20b_3a_20spatial_20neighbor_20search_20methods_20_24n_2018_20542_24_14',['Ablation B: Spatial Neighbor Search Methods ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'']]],
  ['ablation_20c_3a_20statistical_20outlier_20removal_20sor_15',['Ablation C: Statistical Outlier Removal (SOR)',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-c-statistical-outlier-removal-sor',1,'']]],
  ['ablation_20c_3a_20statistical_20outlier_20removal_20sor_20implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_16',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['ablation_20d_3a_20ransac_20plane_20fitting_20iteration_20scaling_17',['ablation d: ransac plane fitting iteration scaling',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-d-ransac-plane-fitting-iteration-scaling',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling'],['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-d-ransac-plane-fitting-iteration-scaling-1',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling']]],
  ['ablation_20experiment_20report_18',['RVPoint Pipeline Profiling &amp; Implementation Ablation Experiment Report',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html',1,'']]],
  ['ablation_5fbench_2ecpp_19',['ablation_bench.cpp',['../ablation__bench_8cpp.html',1,'']]],
  ['ablations_20',['ablations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md3-phase-2-component-level-implementation-ablations',1,'3. Phase 2 Component-Level Implementation Ablations'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md4-phase-2-comparative-implementation-ablations',1,'4. Phase 2: Comparative Implementation Ablations']]],
  ['accelerated_20rvv_20ultra_20fast_20pipeline_3a_21',['1. Run Hardware-Accelerated RVV Ultra-Fast Pipeline:',['../md_docs_2projection.html#autotoc_md1-run-hardware-accelerated-rvv-ultra-fast-pipeline',1,'']]],
  ['across_20configurations_22',['Stage Breakdown Across Configurations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#stage-breakdown-across-configurations',1,'']]],
  ['action_20micro_20timing_20analysis_23',['Sub-Action Micro-Timing Analysis',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#sub-action-micro-timing-analysis',1,'']]],
  ['actions_20stage_208_24',['B. RANSAC Sub-Actions (Stage 8)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#b-ransac-sub-actions-stage-8',1,'']]],
  ['actions_20stage_209_25',['C. Euclidean Clustering Sub-Actions (Stage 9)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#c-euclidean-clustering-sub-actions-stage-9',1,'']]],
  ['activate_20the_20environment_26',['4. Enter the container / activate the environment',['../md_docs_2setup.html#autotoc_md4-enter-the-container--activate-the-environment',1,'']]],
  ['adding_20a_20new_20algorithm_20strong_27',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['advanced_20optimization_3a_20fused_20gather_20filter_28',['Advanced Optimization: Fused Gather-Filter',['../vector_theory.html#advanced-optimization-fused-gather-filter',1,'']]],
  ['advanced_20topics_29',['Advanced Topics',['../instruction_manual.html#advanced-topics',1,'']]],
  ['algebra_20redesign_30',['3. Mathematical &amp; Linear Algebra Redesign',['../md_docs_2projection.html#autotoc_md3-mathematical--linear-algebra-redesign',1,'']]],
  ['algorithm_20strong_31',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['algorithms_32',['algorithms',['../instruction_manual.html#core-algorithms',1,'Core Algorithms'],['../instruction_manual.html#the-5-core-algorithms',1,'The 5 Core Algorithms']]],
  ['analysis_33',['Sub-Action Micro-Timing Analysis',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#sub-action-micro-timing-analysis',1,'']]],
  ['analysis_20report_34',['Pipeline Performance Profiling &amp; Bottleneck Analysis Report',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html',1,'']]],
  ['and_20running_20the_20project_35',['7. Building and running the project',['../md_docs_2setup.html#autotoc_md7-building-and-running-the-project',1,'']]],
  ['and_20verification_36',['6. gem5 setup and verification',['../md_docs_2setup.html#autotoc_md6-gem5-setup-and-verification',1,'']]],
  ['aos_20scalar_20code_37',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['api_20extensions_20to_20tt_20pointeroctree_20tt_38',['4. API Extensions to &lt;tt&gt;PointerOctree&lt;/tt&gt;',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md4-api-extensions-to-pointeroctree',1,'']]],
  ['api_20reference_39',['API Reference',['../instruction_manual.html#api-reference',1,'']]],
  ['application_20binary_20interface_40',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['approach_41',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['architectural_20comparison_3a_20tt_20pipeline_5ffast_5fexport_20tt_20vs_20tt_20pipeline_5frvv_5fultra_5ffast_20tt_42',['5. Architectural Comparison: &lt;tt&gt;pipeline_fast_export&lt;/tt&gt; vs &lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;',['../md_docs_2projection.html#autotoc_md5-architectural-comparison-pipeline_fast_export-vs-pipeline_rvv_ultra_fast',1,'']]],
  ['architectural_20design_20vector_20mechanics_43',['2. Architectural Design &amp; Vector Mechanics',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md2-architectural-design--vector-mechanics',1,'']]],
  ['architectural_20optimization_20recommendations_44',['4. Targeted Architectural Optimization Recommendations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md4-targeted-architectural-optimization-recommendations',1,'']]],
  ['architectural_20recommendations_45',['5. Architectural Recommendations',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md5-architectural-recommendations',1,'']]],
  ['architecture_46',['architecture',['../instruction_manual.html#codebase-architecture',1,'Codebase Architecture'],['../md_docs_2projection.html',1,'Real-Time RVV Point Cloud Perception Architecture']]],
  ['architecture_20specification_47',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['architecture_20technical_20design_20document_48',['Caravan-PointerOctree Hybrid: Architecture &amp; Technical Design Document',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html',1,'']]],
  ['are_5fpoints_5fclose_49',['are_points_close',['../test__voxel__grid_8cpp.html#ad26dac34e77a9711c640f3f7790c95fb',1,'are_points_close(const PointXYZ &amp;a, const PointXYZ &amp;b, float eps=1e-4):&#160;test_voxel_grid.cpp'],['../test__sor_8cpp.html#ad26dac34e77a9711c640f3f7790c95fb',1,'are_points_close(const PointXYZ &amp;a, const PointXYZ &amp;b, float eps=1e-4):&#160;test_sor.cpp']]],
  ['array_20of_20structures_20aos_20scalar_20code_50',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['arrays_20soa_20vector_20code_51',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['artifact_20locations_52',['7. Artifact Locations',['../md_docs_2projection.html#autotoc_md7-artifact-locations',1,'']]],
  ['assembly_53',['Stage 3: Assembly',['../instruction_manual.html#stage-3-assembly',1,'']]],
  ['at_201_206×_20speedup_54',['2. Why &lt;tt&gt;pipeline_export&lt;/tt&gt; Capped at ~1.6× Speedup',['../md_docs_2projection.html#autotoc_md2-why-pipeline_export-capped-at-16-speedup',1,'']]],
  ['automated_20two_20phase_20workflow_20tt_20scripts_20profile_5fpipeline_20py_20tt_55',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]]
];
