var searchData=
[
  ['radius_20search_20strong_0',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['radius_5fsearch_2ecpp_1',['radius_search.cpp',['../radius__search_8cpp.html',1,'']]],
  ['radius_5fsearch_5frvv_2',['radius_search_rvv',['../namespacervv__pcl.html#a25414ba9a167a367adf1eab651d0f57c',1,'rvv_pcl']]],
  ['radius_5fsearch_5fsc_3',['radius_search_sc',['../namespacervv__pcl.html#a4fa0c868d09e8d4892c66405cb80d027',1,'rvv_pcl']]],
  ['radiussearch_4',['radiussearch',['../classrvv__pcl_1_1Octree.html#a9633283f15cfb3a44e3d0e7b0a071ec2',1,'rvv_pcl::Octree::radiusSearch()'],['../classrvv__pcl_1_1SpatialHash.html#a541087deca1e78387f692077f42f4ce4',1,'rvv_pcl::SpatialHash::radiusSearch()']]],
  ['ransac_20plane_20fitting_20strong_5',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['ransac_5fplane_2ecpp_6',['ransac_plane.cpp',['../ransac__plane_8cpp.html',1,'']]],
  ['ransac_5fplane_5frvv_7',['ransac_plane_rvv',['../namespacervv__pcl.html#aa2192abcea5e3f0fe02a0c20b6c7a1d6',1,'rvv_pcl']]],
  ['ransac_5fplane_5fsc_8',['ransac_plane_sc',['../namespacervv__pcl.html#a876b57104ffd09196f3547cd415bf2ff',1,'rvv_pcl']]],
  ['reading_9',['Further Reading',['../instruction_manual.html#further-reading',1,'']]],
  ['readme_2emd_10',['README.md',['../README_8md.html',1,'']]],
  ['readme_5frvv_5fdemo_11',['README_RVV_DEMO',['../readme_rvv_demo.html',1,'']]],
  ['readme_5frvv_5fdemo_2emd_12',['README_RVV_DEMO.md',['../README__RVV__DEMO_8md.html',1,'']]],
  ['real_20hardware_13',['QEMU vs Real Hardware',['../instruction_manual.html#qemu-vs-real-hardware',1,'']]],
  ['recommended_14',['Quick Start (Recommended)',['../index.html#quick-start-recommended',1,'']]],
  ['recursivesearch_15',['recursiveSearch',['../classrvv__pcl_1_1Octree.html#a1129dfe61f40e154f0ed2cc72982d48c',1,'rvv_pcl::Octree']]],
  ['reference_16',['reference',['../instruction_manual.html#api-reference',1,'API Reference'],['../instruction_manual.html#quick-reference',1,'Quick Reference']]],
  ['reference_20guide_17',['RVPoint Instruction Manual &amp; Reference Guide',['../instruction_manual.html#rvpoint-instruction-manual--reference-guide',1,'']]],
  ['register_20grouping_18',['2. LMUL (Register Grouping)',['../vector_theory.html#autotoc_md2-lmul-register-grouping',1,'']]],
  ['removal_20sor_20strong_19',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['reserve_5ffactor_5f_20',['reserve_factor_',['../classrvv__pcl_1_1SpatialHash.html#a78c3475b8ede584848f0c4e8f468bdb9',1,'rvv_pcl::SpatialHash']]],
  ['reset_21',['reset',['../structTimer.html#a9020542d73357a4eef512eefaf57524b',1,'Timer']]],
  ['resources_22',['Documentation &amp; Resources',['../index.html#documentation--resources',1,'']]],
  ['results_23',['results',['../instruction_manual.html#autotoc_md3-serialization--results',1,'3. Serialization &amp; Results'],['../index.html#expected-results',1,'Expected Results'],['../md_results_2benchmark__summary__report.html#results',1,'Results']]],
  ['risc_20v_20vector_20optimized_20point_20cloud_20library_24',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['risc_20v_20vector_20rvv_20implementation_20guide_25',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['riscv64_20linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_26',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['riscv64_20tt_20the_20emulator_27',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['riscv64_3a_20command_20not_20found_28',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['root_5f_29',['root_',['../classrvv__pcl_1_1Octree.html#a457b60f76b8b8d07a172b32866cecc71',1,'rvv_pcl::Octree']]],
  ['run_20full_20verification_30',['Run Full Verification',['../index.html#run-full-verification',1,'']]],
  ['run_20pipeline_31',['2. Run Pipeline',['../pipeline_demo.html#autotoc_md2-run-pipeline',1,'']]],
  ['run_20the_20command_32',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['running_20individual_20tests_33',['Running Individual Tests',['../index.html#running-individual-tests',1,'']]],
  ['running_20tests_34',['Running Tests',['../instruction_manual.html#running-tests',1,'']]],
  ['running_20the_20benchmark_35',['Running the Benchmark',['../index.html#running-the-benchmark',1,'']]],
  ['running_20with_20docker_20manual_36',['Running with Docker (Manual)',['../index.html#running-with-docker-manual',1,'']]],
  ['running_20with_20system_20libraries_20strong_37',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_38',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['rv64gcv_20tt_20architecture_20specification_39',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['rvpoint_20instruction_20manual_20reference_20guide_40',['RVPoint Instruction Manual &amp; Reference Guide',['../instruction_manual.html#rvpoint-instruction-manual--reference-guide',1,'']]],
  ['rvpoint_3a_20risc_20v_20vector_20optimized_20point_20cloud_20library_41',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['rvv_201_200_20features_42',['RVV 1.0 Features',['../instruction_manual.html#rvv-10-features',1,'']]],
  ['rvv_20concepts_43',['Key RVV Concepts',['../vector_theory.html#key-rvv-concepts',1,'']]],
  ['rvv_20efficiency_44',['Why This Proves RVV Efficiency',['../md_tests_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['rvv_20features_45',['Key RVV Features',['../instruction_manual.html#key-rvv-features',1,'']]],
  ['rvv_20implementation_20guide_46',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['rvv_20only_47',['Helper Kernels (RVV Only)',['../instruction_manual.html#helper-kernels-rvv-only',1,'']]],
  ['rvv_20patterns_48',['Common RVV Patterns',['../instruction_manual.html#common-rvv-patterns',1,'']]],
  ['rvv_20point_20cloud_20pipeline_20demo_20branch_3a_20arian_5fexps_49',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['rvv_20programming_20concepts_50',['RVV Programming Concepts',['../instruction_manual.html#rvv-programming-concepts',1,'']]],
  ['rvv_20vector_20execution_20⚡_51',['RVV Vector Execution ⚡',['../instruction_manual.html#rvv-vector-execution-',1,'']]],
  ['rvv_5fcommon_2ecpp_52',['rvv_common.cpp',['../rvv__common_8cpp.html',1,'']]],
  ['rvv_5finst_53',['rvv_inst',['../structBenchmarkData.html#a5d6405af190857520bba171063afc3a9',1,'BenchmarkData']]],
  ['rvv_5fpcl_54',['rvv_pcl',['../namespacervv__pcl.html',1,'']]],
  ['rvv_5fpcl_2eh_55',['rvv_pcl.h',['../rvv__pcl_8h.html',1,'']]],
  ['rvv_5ftest_2ec_56',['rvv_test.c',['../rvv__test_8c.html',1,'']]]
];
