var searchData=
[
  ['f3_0',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['features_1',['features',['../index.html#key-features',1,'Key Features'],['../instruction_manual.html#key-rvv-features',1,'Key RVV Features'],['../instruction_manual.html#rvv-10-features',1,'RVV 1.0 Features']]],
  ['file_2',['file',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'Error 2: &quot;cannot execute binary file&quot;'],['../structDualStream.html#aef90605bb1490b803e9823618f176bc9',1,'DualStream::file']]],
  ['file_20organization_3',['File Organization',['../instruction_manual.html#file-organization',1,'']]],
  ['file_20structure_4',['File Structure',['../md_guides_2AGENT.html#file-structure',1,'']]],
  ['file_5fpath_20points_5fvector_20tt_5',['file_path points_vector tt',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;'],['../instruction_manual.html#savepcdfile_path-points_vector',1,'&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;']]],
  ['filename_6',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['files_7',['Key Files',['../pipeline_demo.html#key-files',1,'']]],
  ['files_20input_8',['5. Source Files - Input',['../instruction_manual.html#autotoc_md5-source-files---input',1,'']]],
  ['filter_9',['Advanced Optimization: Fused Gather-Filter',['../vector_theory.html#advanced-optimization-fused-gather-filter',1,'']]],
  ['first_20steps_20when_20starting_20work_10',['First Steps When Starting Work',['../md_guides_2AGENT.html#first-steps-when-starting-work',1,'']]],
  ['fitting_20strong_11',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['flag_20does_20not_20exist_20on_20ubuntu_2022_2004_12',['&lt;tt&gt;mkswap -q&lt;/tt&gt; flag does not exist on Ubuntu 22.04',['../md_guides_2session__2026-04-07.html#mkswap--q-flag-does-not-exist-on-ubuntu-2204',1,'']]],
  ['flip_5fnormal_5frvv_13',['flip_normal_rvv',['../namespacervv__pcl.html#a0d9f845cd4a86248dfb6acd95f599e5b',1,'rvv_pcl']]],
  ['flipnormaltowardsviewpoint_14',['flipNormalTowardsViewpoint',['../namespacervv__pcl.html#a662b759c3a2968ff7cf0d205dc9c72d9',1,'rvv_pcl']]],
  ['flow_15',['flow',['../instruction_manual.html#execution-flow',1,'Execution Flow'],['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'What QEMU Does Internally (Complete Flow)']]],
  ['for_20agents_16',['for agents',['../md_guides_2AGENT.html#common-tasks-for-agents',1,'Common Tasks for Agents'],['../md_guides_2AGENT.html#critical-gotchas-for-agents',1,'Critical Gotchas for Agents'],['../md_guides_2AGENT.html#quick-start-for-agents',1,'Quick Start for Agents']]],
  ['for_20linux_20uses_20a_20qemu_20vm_20—_20limits_20container_20ram_20to_205_206_20gb_17',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['for_20new_20agents_18',['Recommended Reading Order for New Agents',['../md_guides_2AGENT.html#recommended-reading-order-for-new-agents',1,'']]],
  ['for_20this_20benchmark_19',['Key design rules for this benchmark',['../md_guides_2AGENT.html#key-design-rules-for-this-benchmark',1,'']]],
  ['format_20',['Output format',['../md_guides_2AGENT.html#output-format',1,'']]],
  ['found_21',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['full_20test_20suite_22',['Task 1: Running the Full Test Suite',['../md_guides_2AGENT.html#task-1-running-the-full-test-suite',1,'']]],
  ['full_20verification_23',['Full Verification',['../index.html#full-verification',1,'']]],
  ['function_20extend_20the_20code_24',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['further_20reading_25',['Further Reading',['../instruction_manual.html#further-reading',1,'']]],
  ['fused_20gather_20filter_26',['Advanced Optimization: Fused Gather-Filter',['../vector_theory.html#advanced-optimization-fused-gather-filter',1,'']]]
];
