var searchData=
[
  ['calculation_0',['Distance Calculation',['../instruction_manual.html#distance-calculation',1,'']]],
  ['call_20translation_20strong_1',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['cannot_20execute_20binary_20file_2',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['cap_20—_20container_20sees_20less_20ram_20than_20host_3',['Stale container memory cap — container sees less RAM than host',['../md_guides_2session__2026-04-07.html#stale-container-memory-cap--container-sees-less-ram-than-host',1,'']]],
  ['cc_20tt_20compilation_20oom_20killed_20even_20with_20moderate_20parallelism_4',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['cd_5',['CI/CD',['../index.html#cicd',1,'']]],
  ['cell_5fsize_5f_6',['cell_size_',['../classrvv__pcl_1_1SpatialHash.html#ae04eeccbfb840ae62458138d8f2db005',1,'rvv_pcl::SpatialHash']]],
  ['changes_7',['Building Docker Image (only when Dockerfile changes)',['../md_guides_2AGENT.html#building-docker-image-only-when-dockerfile-changes',1,'']]],
  ['check_5frvv_5ffeatures_8',['check_rvv_features',['../test__rvv__features_8c.html#a699ce3eaaa120d787df2775c49c55826',1,'test_rvv_features.c']]],
  ['checking_20benchmark_20results_9',['Task 4: Checking Benchmark Results',['../md_guides_2AGENT.html#task-4-checking-benchmark-results',1,'']]],
  ['checks_10',['Safety Checks',['../md_guides_2AGENT.html#safety-checks',1,'']]],
  ['children_11',['children',['../structrvv__pcl_1_1OctreeNode.html#a68e0907cabe2b57aa877bfe61ce8899b',1,'rvv_pcl::OctreeNode']]],
  ['choices_12',['choices',['../namespacegem5__se.html#aeab4210936df846bdd7eb1d74b0dbcfb',1,'gem5_se']]],
  ['ci_20cd_13',['CI/CD',['../index.html#cicd',1,'']]],
  ['class_20tt_20octree_20tt_20strong_14',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['class_20tt_20spatialhash_20tt_20strong_15',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['clean_20build_20targeting_20gcc_2014_20strong_16',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['clk_5fdomain_17',['clk_domain',['../namespacegem5__se.html#a8d3bb3c7a0ab285a48e36e66b4f7f42f',1,'gem5_se']]],
  ['clock_18',['clock',['../namespacegem5__se.html#a7e5e5a2c903df04ca77eadb7e39fcc50',1,'gem5_se']]],
  ['clock_20time_19',['Why Not Wall-Clock Time?',['../md_guides_2AGENT.html#why-not-wall-clock-time',1,'']]],
  ['cloud_20library_20',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['cloud_20pipeline_20demo_20branch_3a_20arian_5fexps_21',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['cloud_5f_22',['cloud_',['../classrvv__pcl_1_1Octree.html#a350aeea9e39f10699be47f496faa537f',1,'rvv_pcl::Octree::cloud_'],['../classrvv__pcl_1_1SpatialHash.html#aa0014a79604f78c69f5c02fba42c006d',1,'rvv_pcl::SpatialHash::cloud_']]],
  ['clouddata_23',['CloudData',['../structCloudData.html',1,'']]],
  ['cmake_20build_20inside_20container_24',['CMake Build (inside container)',['../md_guides_2AGENT.html#cmake-build-inside-container',1,'']]],
  ['cmakelists_20txt_20addition_25',['CMakeLists.txt addition',['../md_guides_2AGENT.html#cmakeliststxt-addition',1,'']]],
  ['cmd_26',['cmd',['../namespacegem5__se.html#ad5b156ffddc50242fba73e69c408b8c7',1,'gem5_se']]],
  ['code_27',['code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'2. How to Function &amp; Extend the Code'],['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'Array of Structures (AoS) - Scalar Code'],['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'Structure of Arrays (SoA) - Vector Code']]],
  ['code_20breakdown_28',['The Code Breakdown',['../vector_theory.html#the-code-breakdown',1,'']]],
  ['codebase_20architecture_29',['Codebase Architecture',['../instruction_manual.html#codebase-architecture',1,'']]],
  ['command_30',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['command_20breakdown_31',['command breakdown',['../instruction_manual.html#command-breakdown',1,'Command Breakdown'],['../instruction_manual.html#qemu-execution-command-breakdown',1,'QEMU Execution Command Breakdown'],['../instruction_manual.html#summary-qemu-command-breakdown',1,'Summary: QEMU Command Breakdown']]],
  ['command_20linux_20target_32',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['command_20not_20found_33',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['command_20patterns_34',['Command Patterns',['../md_guides_2AGENT.html#command-patterns',1,'']]],
  ['commands_35',['commands',['../md_guides_2AGENT.html#before-running-destructive-commands',1,'Before Running Destructive Commands'],['../instruction_manual.html#compilation-commands',1,'Compilation Commands'],['../instruction_manual.html#execution-commands',1,'Execution Commands']]],
  ['commands_20inside_20container_20directly_36',['Running Commands Inside Container Directly',['../md_guides_2AGENT.html#running-commands-inside-container-directly',1,'']]],
  ['common_20intrinsics_37',['Common Intrinsics',['../instruction_manual.html#common-intrinsics',1,'']]],
  ['common_20qemu_20errors_20solutions_38',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['common_20rvv_20patterns_39',['Common RVV Patterns',['../instruction_manual.html#common-rvv-patterns',1,'']]],
  ['common_20tasks_20for_20agents_40',['Common Tasks for Agents',['../md_guides_2AGENT.html#common-tasks-for-agents',1,'']]],
  ['compilation_41',['Stage 2: Compilation',['../instruction_manual.html#stage-2-compilation',1,'']]],
  ['compilation_20command_20linux_20target_42',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['compilation_20commands_43',['Compilation Commands',['../instruction_manual.html#compilation-commands',1,'']]],
  ['compilation_20deep_20dive_44',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['compilation_20oom_20killed_20even_20with_20moderate_20parallelism_45',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['compilation_20output_46',['Inspecting Compilation Output',['../instruction_manual.html#inspecting-compilation-output',1,'']]],
  ['compilation_20stages_47',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['compiler_48',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['compiler_20selection_3a_20linux_20vs_20bare_20metal_49',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['complete_20example_3a_20what_20happens_20when_20you_20run_20the_20command_50',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['complete_20flow_51',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['component_20structure_52',['Component Structure',['../instruction_manual.html#component-structure',1,'']]],
  ['compute_5fcovariance_5frvv_53',['compute_covariance_rvv',['../namespacervv__pcl.html#a7579c4594b9c3142399c0ebc4818d8b0',1,'rvv_pcl']]],
  ['concepts_54',['concepts',['../vector_theory.html#key-rvv-concepts',1,'Key RVV Concepts'],['../instruction_manual.html#rvv-programming-concepts',1,'RVV Programming Concepts']]],
  ['configuration_55',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['configuration_20options_20summary_56',['Configuration Options Summary',['../instruction_manual.html#configuration-options-summary',1,'']]],
  ['constrs_20cc_20tt_20compilation_20oom_20killed_20even_20with_20moderate_20parallelism_57',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['container_58',['CMake Build (inside container)',['../md_guides_2AGENT.html#cmake-build-inside-container',1,'']]],
  ['container_20directly_59',['Running Commands Inside Container Directly',['../md_guides_2AGENT.html#running-commands-inside-container-directly',1,'']]],
  ['container_20memory_20cap_20—_20container_20sees_20less_20ram_20than_20host_60',['Stale container memory cap — container sees less RAM than host',['../md_guides_2session__2026-04-07.html#stale-container-memory-cap--container-sees-less-ram-than-host',1,'']]],
  ['container_20ram_20to_205_206_20gb_61',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['container_20recommended_62',['Dev Container (Recommended)',['../index.html#dev-container-recommended',1,'']]],
  ['containers_63',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['contents_64',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['convention_65',['3. Intrinsics Naming Convention',['../vector_theory.html#autotoc_md3-intrinsics-naming-convention',1,'']]],
  ['core_20algorithms_66',['core algorithms',['../instruction_manual.html#core-algorithms',1,'Core Algorithms'],['../instruction_manual.html#the-5-core-algorithms',1,'The 5 Core Algorithms']]],
  ['core_20headers_67',['Before Editing Core Headers',['../md_guides_2AGENT.html#before-editing-core-headers',1,'']]],
  ['core_20logic_3a_20tt_20get_5fdist_5fsq_5frvv_20tt_68',['Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;',['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'']]],
  ['cost_69',['Ground Truth Generation Is Not Pipeline Cost',['../md_guides_2AGENT.html#ground-truth-generation-is-not-pipeline-cost',1,'']]],
  ['counting_70',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['counting_20methodology_71',['Instruction Counting Methodology',['../md_tests_2INSTRUCTION__COUNTING.html',1,'']]],
  ['counting_20rdinstret_72',['Instruction Counting (rdinstret)',['../md_guides_2AGENT.html#instruction-counting-rdinstret',1,'']]],
  ['cpp_20tt_73',['Key RVV Kernels (in &lt;tt&gt;rvv_common.cpp&lt;/tt&gt;)',['../md_guides_2AGENT.html#key-rvv-kernels-in-rvv_commoncpp',1,'']]],
  ['cpu_74',['cpu',['../namespacegem5__se.html#aa3bdd4ab99676855567984731b972beb',1,'gem5_se']]],
  ['cpu_20configuration_75',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['cpu_20rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_76',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['create_20soa_20structure_77',['Create SoA Structure',['../instruction_manual.html#create-soa-structure',1,'']]],
  ['critical_20design_20decision_78',['Data Layout (Critical Design Decision)',['../md_guides_2AGENT.html#data-layout-critical-design-decision',1,'']]],
  ['critical_20gotchas_20for_20agents_79',['Critical Gotchas for Agents',['../md_guides_2AGENT.html#critical-gotchas-for-agents',1,'']]],
  ['cross_20compiler_80',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['current_20status_81',['Current Status',['../md_guides_2AGENT.html#current-status',1,'']]],
  ['custom_20toolchain_20path_82',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]]
];
