var searchData=
[
  ['l2_0',['L2',['../namespacervpoint_1_1bench.html#a416d76d9e386cb87b9a30426806f50b8a7e6aa2d53f6ee2b1a34b017fa403cb76',1,'rvpoint::bench']]],
  ['latency_20wall_3a_1',['The Memory Latency Wall:',['../md_docs_2projection.html#the-memory-latency-wall',1,'']]],
  ['leaf_20vector_20kernel_2',['C. Caravan Leaf Vector Kernel',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#c-caravan-leaf-vector-kernel',1,'']]],
  ['leaf_5fsize_5f_3',['leaf_size_',['../classFusedHashLeafOctree.html#a39b1931e80f2d82aeb4e514e6d7faf85',1,'FusedHashLeafOctree']]],
  ['leaf_5fx_4',['leaf_x',['../structrvpoint_1_1PointerOctreeNode.html#a2b450621f2f26bd8bcdd35ccf2f2134c',1,'rvpoint::PointerOctreeNode']]],
  ['leaf_5fy_5',['leaf_y',['../structrvpoint_1_1PointerOctreeNode.html#abeeed3ce2c057af6f853e8a7e670199e',1,'rvpoint::PointerOctreeNode']]],
  ['leaf_5fz_6',['leaf_z',['../structrvpoint_1_1PointerOctreeNode.html#a6033e5974181a7dadceee980a3ebf707',1,'rvpoint::PointerOctreeNode']]],
  ['leaves_5f_7',['leaves_',['../classFusedHashLeafOctree.html#a96ccca9534e7572338a10f1aa6c768af',1,'FusedHashLeafOctree']]],
  ['length_8',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['length_20multiplier_9',['2. LMUL (Length Multiplier)',['../instruction_manual.html#autotoc_md2-lmul-length-multiplier',1,'']]],
  ['level_20implementation_20ablations_10',['3. Phase 2 Component-Level Implementation Ablations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md3-phase-2-component-level-implementation-ablations',1,'']]],
  ['level_20stage_20timing_20matrix_11',['High-Level Stage Timing Matrix',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#high-level-stage-timing-matrix',1,'']]],
  ['libraries_20strong_12',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['library_13',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['license_14',['📄 License',['../index.html#autotoc_md-license',1,'']]],
  ['limitation_15',['6b. The bind-mounted &lt;tt&gt;/opt/gem5&lt;/tt&gt; binary — known limitation',['../md_docs_2setup.html#autotoc_md6b-the-bind-mounted-optgem5-binary--known-limitation',1,'']]],
  ['linear_20algebra_20redesign_16',['3. Mathematical &amp; Linear Algebra Redesign',['../md_docs_2projection.html#autotoc_md3-mathematical--linear-algebra-redesign',1,'']]],
  ['linearmortonoctree_17',['linearmortonoctree',['../classLinearMortonOctree.html',1,'LinearMortonOctree'],['../classLinearMortonOctree.html#a88f5dd6858e1c13ca8db35890eeabe76',1,'LinearMortonOctree::LinearMortonOctree()']]],
  ['linking_18',['Stage 4: Linking',['../instruction_manual.html#stage-4-linking',1,'']]],
  ['linux_19',['Building for Linux',['../index.html#building-for-linux',1,'']]],
  ['linux_20cross_20compiler_20',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_21',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['linux_20target_22',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['linux_20toolchain_23',['⚡ GCC 14 Upgrade &amp; Linux Toolchain',['../index.html#autotoc_md-gcc-14-upgrade--linux-toolchain',1,'']]],
  ['linux_20vs_20bare_20metal_24',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['lmul_20length_20multiplier_25',['2. LMUL (Length Multiplier)',['../instruction_manual.html#autotoc_md2-lmul-length-multiplier',1,'']]],
  ['lmul_20register_20grouping_26',['2. LMUL (Register Grouping)',['../vector_theory.html#autotoc_md2-lmul-register-grouping',1,'']]],
  ['load_27',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['load_5fpcd_5fdata_28',['load_pcd_data',['../namespaceexport__mcap.html#aac6b27da6fbaf96e76066ca41995f629',1,'export_mcap']]],
  ['loadpcd_29',['loadPCD',['../namespacervpoint.html#a63c57900a13a76af267b191e2a533662',1,'rvpoint']]],
  ['loadpcd_20file_5fpath_20points_5fvector_20tt_30',['&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'']]],
  ['locations_31',['7. Artifact Locations',['../md_docs_2projection.html#autotoc_md7-artifact-locations',1,'']]],
  ['log_20future_20finalization_20checklist_32',['6. Ongoing Experiment Work Log &amp; Future Finalization Checklist',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md6-ongoing-experiment-work-log--future-finalization-checklist',1,'']]],
  ['log_5fmessage_33',['log_message',['../classserve__mcap_1_1FoxgloveCORSHandler.html#a005529394980e42a289f94bd5cad0070',1,'serve_mcap::FoxgloveCORSHandler']]],
  ['logging_20tt_20d_20exec_20nochain_20tt_34',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['logic_3a_20tt_20get_5fdist_5fsq_5frvv_20tt_35',['Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;',['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'']]],
  ['loop_20strong_36',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['lp64d_20tt_20application_20binary_20interface_37',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]]
];
