var searchData=
[
  ['i_20src_20include_20tt_20include_20directory_0',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['identity_5fpose_1',['identity_pose',['../namespaceexport__mcap.html#a9506181f086c3715714462ae2d7a68ba',1,'export_mcap']]],
  ['idx_2',['idx',['../structLinearMortonOctree_1_1PointKey.html#a1b0e34dc1af785fa9374da4c5e0132d5',1,'LinearMortonOctree::PointKey']]],
  ['illegal_20instruction_3',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['image_4',['1. Build the image',['../md_docs_2setup.html#autotoc_md1-build-the-image',1,'']]],
  ['image_20the_20wrapper_20script_20s_20approach_5',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['impact_6',['3. Key Synergy &amp; Expected Performance Impact',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md3-key-synergy--expected-performance-impact',1,'']]],
  ['implementation_7',['5. Next Steps for Implementation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md5-next-steps-for-implementation',1,'']]],
  ['implementation_20ablation_20experiment_20report_8',['RVPoint Pipeline Profiling &amp; Implementation Ablation Experiment Report',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html',1,'']]],
  ['implementation_20ablations_9',['implementation ablations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md3-phase-2-component-level-implementation-ablations',1,'3. Phase 2 Component-Level Implementation Ablations'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md4-phase-2-comparative-implementation-ablations',1,'4. Phase 2: Comparative Implementation Ablations']]],
  ['implementation_20guide_10',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_11',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['in_20sor_12',['Integration in SOR',['../vector_theory.html#integration-in-sor',1,'']]],
  ['include_20directory_13',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['include_20profiler_20h_20tt_14',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['include_20tt_20include_20directory_15',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['indexed_20gather_20tt_20_5f_5friscv_5fvluxei32_5fv_5ff32m8_20tt_16',['B. Vector Indexed Gather (&lt;tt&gt;__riscv_vluxei32_v_f32m8&lt;/tt&gt;)',['../md_docs_2projection.html#b-vector-indexed-gather-__riscv_vluxei32_v_f32m8',1,'']]],
  ['indexed_20load_17',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['indexing_18',['Spatial Indexing',['../instruction_manual.html#spatial-indexing',1,'']]],
  ['indices_19',['indices',['../structFusedVectorLeaf.html#a8fb8f24e6c3def4887f47f4d4b289107',1,'FusedVectorLeaf::indices'],['../structrvpoint_1_1ClusterIndices.html#a63d57d5cd73400462652dee44c25c6b4',1,'rvpoint::ClusterIndices::indices'],['../structrvpoint_1_1PointerOctreeNode.html#a929c31fc77d717fa643b470cdd3b1bb0',1,'rvpoint::PointerOctreeNode::indices'],['../structrvpoint_1_1OctreeNode.html#adb153886c1727cd7e168789e8cb89f69',1,'rvpoint::OctreeNode::indices']]],
  ['individual_20tests_20',['Running Individual Tests',['../index.html#running-individual-tests',1,'']]],
  ['infrastructure_20diagnostic_20design_21',['2. Infrastructure &amp; Diagnostic Design',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md2-infrastructure--diagnostic-design',1,'']]],
  ['ingestrawstream_22',['ingestRawStream',['../classFusedRVV25DEngine.html#aa2dc59ce6216204e799ee5db6311e35d',1,'FusedRVV25DEngine']]],
  ['ingeststream_23',['ingestStream',['../classBenchmarkFusedRVV.html#a7d42c4229d7b16296e90f2c65bc0f33b',1,'BenchmarkFusedRVV']]],
  ['initialization_20strong_24',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['inlier_5fcount_25',['inlier_count',['../structPlane3D.html#a420894521e9d122a593b7f97b1600460',1,'Plane3D']]],
  ['input_26',['5. Source Files - Input',['../instruction_manual.html#autotoc_md5-source-files---input',1,'']]],
  ['insert_27',['insert',['../classBenchmarkScalar25D.html#a22e3d85a8a4a1beafd6fd59faf0fcf07',1,'BenchmarkScalar25D']]],
  ['insertcloud_28',['insertCloud',['../classSweepTurboGrid.html#a1846a2836587e983180f1fd8f22b1517',1,'SweepTurboGrid']]],
  ['insertcloudrvv_20tt_29',['A. Vectorized 2D Coordinate Quantization (&lt;tt&gt;insertCloudRVV&lt;/tt&gt;)',['../md_docs_2projection.html#a-vectorized-2d-coordinate-quantization-insertcloudrvv',1,'']]],
  ['insertrecursive_30',['insertRecursive',['../classSIMDOctree8Wide.html#adb3f6d796aaf56636d25814f5157e24a',1,'SIMDOctree8Wide']]],
  ['inside_20the_20container_31',['3. Install the Docker CLI inside the container',['../md_docs_2setup.html#autotoc_md3-install-the-docker-cli-inside-the-container',1,'']]],
  ['insn_20per_20tb_20tt_32',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['inspecting_20compilation_20output_33',['Inspecting Compilation Output',['../instruction_manual.html#inspecting-compilation-output',1,'']]],
  ['install_20the_20docker_20cli_20inside_20the_20container_34',['3. Install the Docker CLI inside the container',['../md_docs_2setup.html#autotoc_md3-install-the-docker-cli-inside-the-container',1,'']]],
  ['installation_20setup_35',['🛠️ Installation &amp; Setup',['../index.html#️-installation--setup',1,'']]],
  ['instruction_36',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['instruction_20counting_20methodology_37',['Instruction Counting Methodology',['../md_docs_2INSTRUCTION__COUNTING.html',1,'']]],
  ['instruction_20emulation_20strong_38',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['instruction_20execution_20loop_20strong_39',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['instruction_20manual_20reference_20guide_40',['RVPoint Instruction Manual &amp; Reference Guide',['../instruction_manual.html#rvpoint-instruction-manual--reference-guide',1,'']]],
  ['instruction_5fcounting_2emd_41',['INSTRUCTION_COUNTING.md',['../INSTRUCTION__COUNTING_8md.html',1,'']]],
  ['instruction_5fmanual_42',['INSTRUCTION_MANUAL',['../instruction_manual.html',1,'']]],
  ['instruction_5fmanual_2emd_43',['INSTRUCTION_MANUAL.md',['../INSTRUCTION__MANUAL_8md.html',1,'']]],
  ['instructiontimer_44',['InstructionTimer',['../structInstructionTimer.html',1,'']]],
  ['integration_20in_20sor_45',['Integration in SOR',['../vector_theory.html#integration-in-sor',1,'']]],
  ['integration_20usage_20guide_46',['Team Integration &amp; Usage Guide',['../instruction_manual.html#team-integration--usage-guide',1,'']]],
  ['interface_47',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['internally_20complete_20flow_48',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['intrinsics_49',['Common Intrinsics',['../instruction_manual.html#common-intrinsics',1,'']]],
  ['intrinsics_20naming_20convention_50',['3. Intrinsics Naming Convention',['../vector_theory.html#autotoc_md3-intrinsics-naming-convention',1,'']]],
  ['intrinsics_20naming_20guide_51',['3. Vector Intrinsics Naming Guide',['../instruction_manual.html#autotoc_md3-vector-intrinsics-naming-guide',1,'']]],
  ['inv_5fcell_5f_52',['inv_cell_',['../classFast3DSpatialGrid.html#ada73f7f15e25b7dbd45803f801b03907',1,'Fast3DSpatialGrid::inv_cell_'],['../classCompactSparse3DGridBench.html#a39823de6d94544f1760f1f8bc5aa7951',1,'CompactSparse3DGridBench::inv_cell_']]],
  ['inv_5fcell_5fsize_5f_53',['inv_cell_size_',['../classFusedRVV25DEngine.html#a2fce2fba161ae6176f77e278585c4805',1,'FusedRVV25DEngine::inv_cell_size_'],['../classBenchmarkScalar25D.html#abf5ef67e1375535e27e7e73b80e7cd1b',1,'BenchmarkScalar25D::inv_cell_size_'],['../classBenchmarkFusedRVV.html#a7ee02f854f50f1c1b9b26dced036ce9d',1,'BenchmarkFusedRVV::inv_cell_size_'],['../classSweepTurboGrid.html#a4fea0957c6af0fe9036f4fb385c4342d',1,'SweepTurboGrid::inv_cell_size_']]],
  ['inv_5fleaf_5f_54',['inv_leaf_',['../classFusedHashLeafOctree.html#acae6f8c3760d1e1b7d93d82bc6dc8e52',1,'FusedHashLeafOctree']]],
  ['inv_5fscale_5f_55',['inv_scale_',['../classLinearMortonOctree.html#acdf09c79d3b6daa33dc058bed13e3c39',1,'LinearMortonOctree']]],
  ['is_20better_56',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['is_5fleaf_57',['is_leaf',['../structrvpoint_1_1OctreeNode.html#abd4f2e1706302b474888adc41fade435',1,'rvpoint::OctreeNode::is_leaf'],['../structrvpoint_1_1PointerOctreeNode.html#a52767b92a01ec6e0f3d93c6696314fdf',1,'rvpoint::PointerOctreeNode::is_leaf'],['../structSIMDOctreeNode8Wide.html#afa6f4bd244818a8fefe999551bb4a9bd',1,'SIMDOctreeNode8Wide::is_leaf']]],
  ['is_5foccupied_58',['is_occupied',['../structFusedVectorLeaf.html#a7bb8ab0497f3a86323a2e6a2c5a9d296',1,'FusedVectorLeaf']]],
  ['iteration_20scaling_59',['iteration scaling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-d-ransac-plane-fitting-iteration-scaling-1',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-d-ransac-plane-fitting-iteration-scaling',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling']]]
];
