var searchData=
[
  ['p1_5f_0',['p1_',['../classrvv__pcl_1_1SpatialHash.html#a3c5615bb17999c2fa30b887190867534',1,'rvv_pcl::SpatialHash']]],
  ['p2_5f_1',['p2_',['../classrvv__pcl_1_1SpatialHash.html#a372dc70b3bcbfb9913cd8dde3a5190b8',1,'rvv_pcl::SpatialHash']]],
  ['parallelism_2',['parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism'],['../md_guides_2session__2026-04-07.html#gem5-linker-oom-killed-with-high-parallelism',1,'gem5 linker OOM-killed with high parallelism']]],
  ['parameters_3',['Parameters',['../md_guides_2AGENT.html#parameters',1,'']]],
  ['parser_4',['parser',['../namespacegem5__se.html#a5d24d9d97521f4a7a74a2a27b43dae5b',1,'gem5_se']]],
  ['path_5',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['pattern_6',['pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'1. Strip Mining Pattern'],['../instruction_manual.html#test-pattern',1,'Test Pattern']]],
  ['patterns_7',['patterns',['../md_guides_2AGENT.html#command-patterns',1,'Command Patterns'],['../instruction_manual.html#common-rvv-patterns',1,'Common RVV Patterns']]],
  ['per_20tb_20tt_8',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['performance_20summary_20table_9',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['performance_20tuning_10',['Performance Tuning',['../instruction_manual.html#performance-tuning',1,'']]],
  ['phase_201_3a_20initialization_20strong_11',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['phase_202_3a_20instruction_20execution_20loop_20strong_12',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['phase_203_3a_20system_20call_20translation_20strong_13',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['phase_204_3a_20vector_20instruction_20emulation_20strong_14',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['pi_20bpi_20f3_15',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['pipeline_16',['2. Run Pipeline',['../pipeline_demo.html#autotoc_md2-run-pipeline',1,'']]],
  ['pipeline_20benchmark_17',['The Priority Task: E2E Pipeline Benchmark',['../md_guides_2AGENT.html#the-priority-task-e2e-pipeline-benchmark',1,'']]],
  ['pipeline_20cost_18',['Ground Truth Generation Is Not Pipeline Cost',['../md_guides_2AGENT.html#ground-truth-generation-is-not-pipeline-cost',1,'']]],
  ['pipeline_20demo_19',['Pipeline Demo */',['../pipeline_demo.html',1,'']]],
  ['pipeline_20demo_20branch_3a_20arian_5fexps_20',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['pipeline_20walkthrough_20with_20real_20data_21',['Task 5: Pipeline Walkthrough with Real Data',['../md_guides_2AGENT.html#task-5-pipeline-walkthrough-with-real-data',1,'']]],
  ['pipelineresult_22',['PipelineResult',['../structPipelineResult.html',1,'']]],
  ['plane_20fitting_20strong_23',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['point_20cloud_20library_24',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['point_20cloud_20pipeline_20demo_20branch_3a_20arian_5fexps_25',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['pointcloudsoa_26',['PointCloudSoA',['../structrvv__pcl_1_1PointCloudSoA.html',1,'rvv_pcl']]],
  ['pointcloudsoa_20tt_27',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['points_5fvector_20tt_28',['points_vector tt',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;'],['../instruction_manual.html#savepcdfile_path-points_vector',1,'&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;']]],
  ['pointxyz_29',['PointXYZ',['../structrvv__pcl_1_1PointXYZ.html',1,'rvv_pcl']]],
  ['pointxyz_20tt_30',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['policy_31',['Git Policy',['../md_guides_2AGENT.html#git-policy',1,'']]],
  ['port_32',['port',['../namespacegem5__se.html#a2299720e40fe8f204ce7a037ae93a2d9',1,'gem5_se']]],
  ['practices_33',['Agent Best Practices',['../md_guides_2AGENT.html#agent-best-practices',1,'']]],
  ['preprocessing_34',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]],
  ['prerequisites_35',['prerequisites',['../index.html#prerequisites-1',1,'Prerequisites'],['../pipeline_demo.html#prerequisites',1,'Prerequisites']]],
  ['priority_20order_36',['What&apos;s Next (priority order)',['../md_guides_2AGENT.html#whats-next-priority-order',1,'']]],
  ['priority_20task_3a_20e2e_20pipeline_20benchmark_37',['The Priority Task: E2E Pipeline Benchmark',['../md_guides_2AGENT.html#the-priority-task-e2e-pipeline-benchmark',1,'']]],
  ['problem_38',['problem',['../vector_theory.html#the-problem',1,'The Problem'],['../md_tests_2INSTRUCTION__COUNTING.html#the-problem-1',1,'The Problem']]],
  ['process_39',['process',['../namespacegem5__se.html#ad11c5ee50bdcabde4ed0f4e38474d641',1,'gem5_se']]],
  ['program_20start_40',['Program Start',['../instruction_manual.html#program-start',1,'']]],
  ['programming_20concepts_41',['RVV Programming Concepts',['../instruction_manual.html#rvv-programming-concepts',1,'']]],
  ['project_20architecture_42',['Project Architecture',['../md_guides_2AGENT.html#project-architecture',1,'']]],
  ['project_20navigation_43',['project navigation',['../vector_theory.html#️-project-navigation-1',1,'🗺️ Project Navigation'],['../md_tests_2INSTRUCTION__COUNTING.html#️-project-navigation-2',1,'🗺️ Project Navigation'],['../instruction_manual.html#️-project-navigation',1,'🗺️ Project Navigation']]],
  ['project_20structure_44',['project structure',['../index.html#project-structure-1',1,'Project Structure'],['../pipeline_demo.html#project-structure',1,'Project Structure']]],
  ['proves_20rvv_20efficiency_45',['Why This Proves RVV Efficiency',['../md_tests_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]]
];
