var searchData=
[
  ['t_5fstart_0',['t_start',['../structTimer.html#a6bf6a80cee17e6de7f2d22ede224c7d7',1,'Timer']]],
  ['table_1',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['table_20of_20contents_2',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['target_3',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['target_20hardware_3a_20banana_20pi_20bpi_20f3_4',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['targeting_20gcc_2014_20strong_5',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['tb_20tt_6',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['team_20integration_20usage_20guide_7',['Team Integration &amp; Usage Guide',['../instruction_manual.html#team-integration--usage-guide',1,'']]],
  ['test_8',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['test_20pattern_9',['Test Pattern',['../instruction_manual.html#test-pattern',1,'']]],
  ['test_5fautovec_2ec_10',['test_autovec.c',['../test__autovec_8c.html',1,'']]],
  ['test_5floader_2ecpp_11',['test_loader.cpp',['../test__loader_8cpp.html',1,'']]],
  ['test_5floader_5ffixed_2ecpp_12',['test_loader_fixed.cpp',['../test__loader__fixed_8cpp.html',1,'']]],
  ['test_5floader_5flinux_2ecpp_13',['test_loader_linux.cpp',['../test__loader__linux_8cpp.html',1,'']]],
  ['test_5floader_5fno_5fpcl_2ecpp_14',['test_loader_no_pcl.cpp',['../test__loader__no__pcl_8cpp.html',1,'']]],
  ['test_5floader_5fsimple_2ecpp_15',['test_loader_simple.cpp',['../test__loader__simple_8cpp.html',1,'']]],
  ['test_5fnormal_2ecpp_16',['test_normal.cpp',['../test__normal_8cpp.html',1,'']]],
  ['test_5foctree_2ecpp_17',['test_octree.cpp',['../test__octree_8cpp.html',1,'']]],
  ['test_5fopen_2ec_18',['test_open.c',['../test__open_8c.html',1,'']]],
  ['test_5fpipeline_5fwalkthrough_2ecpp_19',['test_pipeline_walkthrough.cpp',['../test__pipeline__walkthrough_8cpp.html',1,'']]],
  ['test_5fradius_2ecpp_20',['test_radius.cpp',['../test__radius_8cpp.html',1,'']]],
  ['test_5fransac_2ecpp_21',['test_ransac.cpp',['../test__ransac_8cpp.html',1,'']]],
  ['test_5frvv_5ffeatures_2ec_22',['test_rvv_features.c',['../test__rvv__features_8c.html',1,'']]],
  ['test_5fscalar_2ec_23',['test_scalar.c',['../test__scalar_8c.html',1,'']]],
  ['test_5fsor_2ecpp_24',['test_sor.cpp',['../test__sor_8cpp.html',1,'']]],
  ['test_5fspatial_5fhash_5fcomparison_2ecpp_25',['test_spatial_hash_comparison.cpp',['../test__spatial__hash__comparison_8cpp.html',1,'']]],
  ['test_5fspike_2ec_26',['test_spike.c',['../test__spike_8c.html',1,'']]],
  ['test_5ftuples_27',['test_tuples',['../test__tuples_8c.html#a731553bd209edadb53a76cafaaaaa5af',1,'test_tuples.c']]],
  ['test_5ftuples_2ec_28',['test_tuples.c',['../test__tuples_8c.html',1,'']]],
  ['test_5fvector_2ec_29',['test_vector.c',['../test__vector_8c.html',1,'']]],
  ['test_5fvoxel_5fgrid_2ecpp_30',['test_voxel_grid.cpp',['../test__voxel__grid_8cpp.html',1,'']]],
  ['test_5fvoxel_5flinux_2ecpp_31',['test_voxel_linux.cpp',['../test__voxel__linux_8cpp.html',1,'']]],
  ['test_5fvoxel_5frvv_20tt_20output_20filename_32',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['test_5fvoxel_5frvv_20tt_20the_20binary_20to_20execute_33',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['test_5fvoxel_5fscaling_2ecpp_34',['test_voxel_scaling.cpp',['../test__voxel__scaling_8cpp.html',1,'']]],
  ['testing_35',['🏗️ Building &amp; Testing',['../index.html#️-building--testing',1,'']]],
  ['testing_20verification_36',['Testing &amp; Verification',['../instruction_manual.html#testing--verification',1,'']]],
  ['tests_37',['tests',['../index.html#running-individual-tests',1,'Running Individual Tests'],['../instruction_manual.html#running-tests',1,'Running Tests']]],
  ['the_204_20compilation_20stages_38',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['the_205_20core_20algorithms_39',['The 5 Core Algorithms',['../instruction_manual.html#the-5-core-algorithms',1,'']]],
  ['the_20benchmark_40',['Running the Benchmark',['../index.html#running-the-benchmark',1,'']]],
  ['the_20binary_20to_20execute_41',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['the_20code_42',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['the_20code_20breakdown_43',['The Code Breakdown',['../vector_theory.html#the-code-breakdown',1,'']]],
  ['the_20command_44',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['the_20emulator_45',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['the_20linux_20cross_20compiler_46',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['the_20problem_47',['the problem',['../md_tests_2INSTRUCTION__COUNTING.html#the-problem-1',1,'The Problem'],['../vector_theory.html#the-problem',1,'The Problem']]],
  ['the_20solution_3a_20trace_20based_20counting_48',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['the_20solution_3a_20tt_20vluxei32_20tt_20indexed_20load_49',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['theory_50',['Vector Theory */',['../vector_theory.html',1,'']]],
  ['this_20board_51',['Why this board?',['../instruction_manual.html#why-this-board',1,'']]],
  ['this_20is_20better_52',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['this_20proves_20rvv_20efficiency_53',['Why This Proves RVV Efficiency',['../md_tests_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['timer_54',['Timer',['../structTimer.html',1,'']]],
  ['tips_55',['Debugging Tips',['../instruction_manual.html#debugging-tips',1,'']]],
  ['to_20execute_56',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['to_20function_20extend_20the_20code_57',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['to_20use_58',['How to use',['../index.html#how-to-use',1,'']]],
  ['toolchain_59',['⚡ GCC 14 Upgrade &amp; Linux Toolchain',['../index.html#autotoc_md-gcc-14-upgrade--linux-toolchain',1,'']]],
  ['toolchain_20path_60',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['topics_61',['Advanced Topics',['../instruction_manual.html#advanced-topics',1,'']]],
  ['trace_20based_20counting_62',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['trace_20logging_20tt_20d_20exec_20nochain_20tt_63',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['translation_20strong_64',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['true_20vlen_20128_20tt_20cpu_20configuration_65',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['tt_20cpu_20rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_66',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['tt_20d_20exec_20nochain_20tt_67',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['tt_20get_5fdist_5fsq_5frvv_20tt_68',['tt get_dist_sq_rvv tt',['../instruction_manual.html#get_dist_sq_rvv',1,'&lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;'],['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;']]],
  ['tt_20get_5finds_5fin_5fradius_5frvv_20tt_69',['&lt;tt&gt;get_inds_in_radius_rvv&lt;/tt&gt;',['../instruction_manual.html#get_inds_in_radius_rvv',1,'']]],
  ['tt_20i_20src_20include_20tt_20include_20directory_70',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['tt_20loadpcd_20file_5fpath_20points_5fvector_20tt_71',['&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'']]],
  ['tt_20mabi_20lp64d_20tt_20application_20binary_20interface_72',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['tt_20march_20rv64gcv_20tt_20architecture_20specification_73',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['tt_20o_20test_5fvoxel_5frvv_20tt_20output_20filename_74',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['tt_20octree_20tt_20strong_75',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['tt_20one_20insn_20per_20tb_20tt_76',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['tt_20qemu_20riscv64_20tt_20the_20emulator_77',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['tt_20riscv64_20linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_78',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['tt_20savepcd_20file_5fpath_20points_5fvector_20tt_79',['&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#savepcdfile_path-points_vector',1,'']]],
  ['tt_20spatialhash_20tt_20strong_80',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['tt_20struct_20pointcloudsoa_20tt_81',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['tt_20struct_20pointxyz_20tt_82',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['tt_20test_5fvoxel_5frvv_20tt_20the_20binary_20to_20execute_83',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['tt_20vluxei32_20tt_20indexed_20load_84',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['tt_20vsetvl_20tt_20vector_20set_20vector_20length_85',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['tuning_86',['Performance Tuning',['../instruction_manual.html#performance-tuning',1,'']]]
];
