var searchData=
[
  ['savepcd_0',['savePCD',['../namespacervv__pcl.html#a0e10691007799037e6779e1a82615a51',1,'rvv_pcl']]],
  ['savepcd_20file_5fpath_20points_5fvector_20tt_1',['&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#savepcdfile_path-points_vector',1,'']]],
  ['sc_5finst_2',['sc_inst',['../structBenchmarkData.html#a68c66eb5b6084e50bb53ec70bb8ecd36',1,'BenchmarkData']]],
  ['scalar_20code_3',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['scalar_20execution_4',['Scalar Execution',['../instruction_manual.html#scalar-execution',1,'']]],
  ['scale_5',['🚀 Advanced Benchmarks (Large-Scale)',['../md_results_2benchmark__summary__report.html#autotoc_md-advanced-benchmarks-large-scale',1,'']]],
  ['search_20strong_6',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['selection_3a_20linux_20vs_20bare_20metal_7',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['serialization_20results_8',['3. Serialization &amp; Results',['../instruction_manual.html#autotoc_md3-serialization--results',1,'']]],
  ['set_20vector_20length_9',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['setbuildepsilon_10',['setBuildEpsilon',['../classrvv__pcl_1_1Octree.html#a0fb9ac6ecaf5822aa10f4c8e7c89701f',1,'rvv_pcl::Octree']]],
  ['sethashprimes_11',['setHashPrimes',['../classrvv__pcl_1_1SpatialHash.html#a03f5b2ec370557f10d31261d69b902ea',1,'rvv_pcl::SpatialHash']]],
  ['setinputcloud_12',['setinputcloud',['../classrvv__pcl_1_1Octree.html#aa607901983d3865078eeca2228260b27',1,'rvv_pcl::Octree::setInputCloud()'],['../classrvv__pcl_1_1SpatialHash.html#a3bbba309026c48c337cd535e7c9b17b6',1,'rvv_pcl::SpatialHash::setInputCloud()']]],
  ['setmaxdepth_13',['setMaxDepth',['../classrvv__pcl_1_1Octree.html#ad88650c2708174d17c74dbafffbdeb45',1,'rvv_pcl::Octree']]],
  ['setmaxpointsperleaf_14',['setMaxPointsPerLeaf',['../classrvv__pcl_1_1Octree.html#af5bba9b1fbe08da029bded7a47b69a1a',1,'rvv_pcl::Octree']]],
  ['setup_15',['🛠️ Installation &amp; Setup',['../index.html#️-installation--setup',1,'']]],
  ['simple_5feigen3x3_5fsmallest_16',['simple_eigen3x3_smallest',['../namespacervv__pcl.html#ac196c9ab0cbb077b7b7cc78ac9a07d67',1,'rvv_pcl']]],
  ['simple_5fpcd_5floader_2eh_17',['simple_pcd_loader.h',['../simple__pcd__loader_8h.html',1,'']]],
  ['soa_20structure_18',['Create SoA Structure',['../instruction_manual.html#create-soa-structure',1,'']]],
  ['soa_20vector_20code_19',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['solution_3a_20trace_20based_20counting_20',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['solution_3a_20tt_20vluxei32_20tt_20indexed_20load_21',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['solutions_22',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['sor_23',['Integration in SOR',['../vector_theory.html#integration-in-sor',1,'']]],
  ['sor_20strong_24',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['sor_5frvv_25',['sor_rvv',['../namespacervv__pcl.html#a10fef2e1c9e7aec2b93d045a7ac1fbad',1,'rvv_pcl']]],
  ['sor_5fsc_26',['sor_sc',['../namespacervv__pcl.html#a311c448d07adeb6a74fcea87f25c1f3c',1,'rvv_pcl']]],
  ['source_20files_20input_27',['5. Source Files - Input',['../instruction_manual.html#autotoc_md5-source-files---input',1,'']]],
  ['spatial_20indexing_28',['Spatial Indexing',['../instruction_manual.html#spatial-indexing',1,'']]],
  ['spatial_5fhashing_2ecpp_29',['spatial_hashing.cpp',['../spatial__hashing_8cpp.html',1,'']]],
  ['spatialhash_30',['spatialhash',['../classrvv__pcl_1_1SpatialHash.html',1,'rvv_pcl::SpatialHash'],['../classrvv__pcl_1_1SpatialHash.html#a5c29a96155ecf8bdd83a8b2a1febe975',1,'rvv_pcl::SpatialHash::SpatialHash()']]],
  ['spatialhash_20tt_20strong_31',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['specification_32',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['src_20include_20tt_20include_20directory_33',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['stage_201_3a_20preprocessing_34',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]],
  ['stage_202_3a_20compilation_35',['Stage 2: Compilation',['../instruction_manual.html#stage-2-compilation',1,'']]],
  ['stage_203_3a_20assembly_36',['Stage 3: Assembly',['../instruction_manual.html#stage-3-assembly',1,'']]],
  ['stage_204_3a_20linking_37',['Stage 4: Linking',['../instruction_manual.html#stage-4-linking',1,'']]],
  ['stages_38',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['standardized_20development_20workflow_39',['1. Standardized Development Workflow',['../instruction_manual.html#autotoc_md1-standardized-development-workflow',1,'']]],
  ['start_40',['start',['../instruction_manual.html#program-start',1,'Program Start'],['../pipeline_demo.html#quick-start',1,'Quick Start'],['../structTimer.html#a3a8b5272198d029779dc9302a54305a8',1,'Timer::start()'],['../structTimer.html#aa1b7c788f57b562fefb54cadc7e308b4',1,'Timer::start']]],
  ['start_20recommended_41',['Quick Start (Recommended)',['../index.html#quick-start-recommended',1,'']]],
  ['statistical_20outlier_20removal_20sor_20strong_42',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['statistical_5foutlier_5fremoval_2ecpp_43',['statistical_outlier_removal.cpp',['../statistical__outlier__removal_8cpp.html',1,'']]],
  ['step_20by_20step_20execution_3a_20voxel_20grid_20test_44',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['steps_20manual_45',['Detailed Verification Steps (Manual)',['../index.html#detailed-verification-steps-manual',1,'']]],
  ['strip_20mining_20pattern_46',['1. Strip Mining Pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'']]],
  ['strong_20a_20clean_20build_20targeting_20gcc_2014_20strong_47',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['strong_20adding_20a_20new_20algorithm_20strong_48',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['strong_20b_20running_20with_20system_20libraries_20strong_49',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['strong_20class_20tt_20octree_20tt_20strong_50',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['strong_20class_20tt_20spatialhash_20tt_20strong_51',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['strong_20normal_20estimation_20strong_52',['&lt;strong&gt;Normal Estimation&lt;/strong&gt;',['../instruction_manual.html#normal-estimation',1,'']]],
  ['strong_20phase_201_3a_20initialization_20strong_53',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['strong_20phase_202_3a_20instruction_20execution_20loop_20strong_54',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['strong_20phase_203_3a_20system_20call_20translation_20strong_55',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['strong_20phase_204_3a_20vector_20instruction_20emulation_20strong_56',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['strong_20radius_20search_20strong_57',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['strong_20ransac_20plane_20fitting_20strong_58',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['strong_20statistical_20outlier_20removal_20sor_20strong_59',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['strong_20voxel_20grid_20downsampling_20strong_60',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['struct_20pointcloudsoa_20tt_61',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['struct_20pointxyz_20tt_62',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['structure_63',['structure',['../index.html#autotoc_md-project-structure',1,'📂 Project Structure'],['../instruction_manual.html#component-structure',1,'Component Structure'],['../instruction_manual.html#create-soa-structure',1,'Create SoA Structure'],['../pipeline_demo.html#project-structure',1,'Project Structure']]],
  ['structure_20of_20arrays_20soa_20vector_20code_64',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['structures_65',['structures',['../instruction_manual.html#data-structures',1,'Data Structures'],['../instruction_manual.html#data-structures-1',1,'Data Structures']]],
  ['structures_20aos_20scalar_20code_66',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['subtraction_67',['3. Baseline Subtraction',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md3-baseline-subtraction',1,'']]],
  ['summary_68',['Configuration Options Summary',['../instruction_manual.html#configuration-options-summary',1,'']]],
  ['summary_20table_69',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['summary_3a_20qemu_20command_20breakdown_70',['Summary: QEMU Command Breakdown',['../instruction_manual.html#summary-qemu-command-breakdown',1,'']]],
  ['system_20call_20translation_20strong_71',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['system_20libraries_20strong_72',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]]
];
