var searchData=
[
  ['calculation_0',['Distance Calculation',['../instruction_manual.html#distance-calculation',1,'']]],
  ['call_20translation_20strong_1',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['cannot_20execute_20binary_20file_2',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['cap_20—_20container_20sees_20less_20ram_20than_20host_3',['Stale container memory cap — container sees less RAM than host',['../md_guides_2session__2026-04-07.html#stale-container-memory-cap--container-sees-less-ram-than-host',1,'']]],
  ['cc_20tt_20compilation_20oom_20killed_20even_20with_20moderate_20parallelism_4',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['cd_5',['CI/CD',['../index.html#cicd',1,'']]],
  ['cell_5fsize_5f_6',['cell_size_',['../classrvv__pcl_1_1SpatialHash.html#ae04eeccbfb840ae62458138d8f2db005',1,'rvv_pcl::SpatialHash']]],
  ['changes_7',['Building Docker Image (only when Dockerfile changes)',['../md_guides_2AGENT.html#building-docker-image-only-when-dockerfile-changes',1,'']]],
  ['check_5frvv_5ffeatures_8',['check_rvv_features',['../test__rvv__features_8c.html#a699ce3eaaa120d787df2775c49c55826',1,'test_rvv_features.c']]],
  ['checking_20benchmark_20results_9',['Task 4: Checking Benchmark Results',['../md_guides_2AGENT.html#task-4-checking-benchmark-results',1,'']]],
  ['checks_10',['Safety Checks',['../md_guides_2AGENT.html#safety-checks',1,'']]],
  ['child_5fmax_5fx_11',['child_max_x',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#a309788f952a08fd5a713eb3d0ebdcc9d',1,'rvv_pcl::VectorizedTraversalOctreeNode']]],
  ['child_5fmax_5fy_12',['child_max_y',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#ab6f5c3d2404090e65c0bf0f79c2a6b1b',1,'rvv_pcl::VectorizedTraversalOctreeNode']]],
  ['child_5fmax_5fz_13',['child_max_z',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#a039fb816289dd29be6a5d62f7a5b5068',1,'rvv_pcl::VectorizedTraversalOctreeNode']]],
  ['child_5fmin_5fx_14',['child_min_x',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#ab4998aaa7895d11b22de350259951962',1,'rvv_pcl::VectorizedTraversalOctreeNode']]],
  ['child_5fmin_5fy_15',['child_min_y',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#ac40679198d06aaa810c29f080c7cbbe1',1,'rvv_pcl::VectorizedTraversalOctreeNode']]],
  ['child_5fmin_5fz_16',['child_min_z',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#ab36cc97eec3765b7f03c612dcea24fb5',1,'rvv_pcl::VectorizedTraversalOctreeNode']]],
  ['children_17',['children',['../structrvv__pcl_1_1PacketPointerOctreeNode.html#aca3c241d2f93381f7a729b9f0a1df6a5',1,'rvv_pcl::PacketPointerOctreeNode::children'],['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#a9f3db04ac28ebcd1aedf197cd403f3f5',1,'rvv_pcl::VectorizedTraversalOctreeNode::children'],['../structrvv__pcl_1_1PointerOctreeNode.html#ad074ed80893f7e8e7f5726bdf63b216a',1,'rvv_pcl::PointerOctreeNode::children'],['../structrvv__pcl_1_1MortonPointerOctreeNode.html#aa768ae216529d3c862f340551166c83b',1,'rvv_pcl::MortonPointerOctreeNode::children'],['../structrvv__pcl_1_1OctreeNode.html#a68e0907cabe2b57aa877bfe61ce8899b',1,'rvv_pcl::OctreeNode::children'],['../structrvv__pcl_1_1CustomPointerOctreeNode.html#ac370543de1e86e26be1a1b6ae554235e',1,'rvv_pcl::CustomPointerOctreeNode::children']]],
  ['choices_18',['choices',['../namespacegem5__se.html#aeab4210936df846bdd7eb1d74b0dbcfb',1,'gem5_se']]],
  ['ci_20cd_19',['CI/CD',['../index.html#cicd',1,'']]],
  ['class_20tt_20octree_20tt_20strong_20',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['class_20tt_20spatialhash_20tt_20strong_21',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['clean_20build_20targeting_20gcc_2014_20strong_22',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['clk_5fdomain_23',['clk_domain',['../namespacegem5__se.html#a8d3bb3c7a0ab285a48e36e66b4f7f42f',1,'gem5_se']]],
  ['clock_24',['clock',['../namespacegem5__se.html#a7e5e5a2c903df04ca77eadb7e39fcc50',1,'gem5_se']]],
  ['clock_20time_25',['Why Not Wall-Clock Time?',['../md_guides_2AGENT.html#why-not-wall-clock-time',1,'']]],
  ['cloud_20library_26',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['cloud_20pipeline_20demo_20branch_3a_20arian_5fexps_27',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['cloud_5f_28',['cloud_',['../classrvv__pcl_1_1CustomPointerOctree.html#a1c59a53c22dee299638e34e34517f151',1,'rvv_pcl::CustomPointerOctree::cloud_'],['../classrvv__pcl_1_1Octree.html#a350aeea9e39f10699be47f496faa537f',1,'rvv_pcl::Octree::cloud_'],['../classrvv__pcl_1_1SpatialHash.html#aa0014a79604f78c69f5c02fba42c006d',1,'rvv_pcl::SpatialHash::cloud_'],['../classrvv__pcl_1_1KdTree.html#ab99eccd3bec7670a743790a7327a5848',1,'rvv_pcl::KdTree::cloud_'],['../classrvv__pcl_1_1MortonPointerOctree.html#a729e0ba84a7a18ebe1ea4d06f7e66018',1,'rvv_pcl::MortonPointerOctree::cloud_'],['../classrvv__pcl_1_1PacketPointerOctree.html#acf81078a9a447729bb32b94c73f524c7',1,'rvv_pcl::PacketPointerOctree::cloud_'],['../classrvv__pcl_1_1PointerOctree.html#a301840ee2eb48928c952573d547f16d6',1,'rvv_pcl::PointerOctree::cloud_'],['../classrvv__pcl_1_1VectorizedTraversalOctree.html#a3f2ff42600705505888dcb512a468528',1,'rvv_pcl::VectorizedTraversalOctree::cloud_']]],
  ['cloud_5falloc_29',['cloud_alloc',['../build_8cpp.html#a1b9e945e1c2a18101bc3614c2304de1a',1,'cloud_alloc(struct Cloud *cloud, int N, float voxel_size):&#160;build.cpp'],['../benchmark__octree_8cpp.html#a1b9e945e1c2a18101bc3614c2304de1a',1,'cloud_alloc(struct Cloud *cloud, int N, float voxel_size):&#160;build.cpp'],['../verify_8cpp.html#a1b9e945e1c2a18101bc3614c2304de1a',1,'cloud_alloc(struct Cloud *cloud, int N, float voxel_size):&#160;build.cpp']]],
  ['cloud_5ffree_30',['cloud_free',['../benchmark__octree_8cpp.html#a287d676ffe6767766080f8db9a174c5a',1,'cloud_free(struct Cloud *cloud):&#160;build.cpp'],['../verify_8cpp.html#a287d676ffe6767766080f8db9a174c5a',1,'cloud_free(struct Cloud *cloud):&#160;build.cpp'],['../build_8cpp.html#a287d676ffe6767766080f8db9a174c5a',1,'cloud_free(struct Cloud *cloud):&#160;build.cpp']]],
  ['clouddata_31',['CloudData',['../structCloudData.html',1,'']]],
  ['cmake_20build_20inside_20container_32',['CMake Build (inside container)',['../md_guides_2AGENT.html#cmake-build-inside-container',1,'']]],
  ['cmakelists_20txt_20addition_33',['CMakeLists.txt addition',['../md_guides_2AGENT.html#cmakeliststxt-addition',1,'']]],
  ['cmd_34',['cmd',['../namespacegem5__se.html#ad5b156ffddc50242fba73e69c408b8c7',1,'gem5_se']]],
  ['code_35',['code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'2. How to Function &amp; Extend the Code'],['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'Array of Structures (AoS) - Scalar Code'],['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'Structure of Arrays (SoA) - Vector Code']]],
  ['code_20breakdown_36',['The Code Breakdown',['../vector_theory.html#the-code-breakdown',1,'']]],
  ['codebase_20architecture_37',['Codebase Architecture',['../instruction_manual.html#codebase-architecture',1,'']]],
  ['command_38',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['command_20breakdown_39',['command breakdown',['../instruction_manual.html#command-breakdown',1,'Command Breakdown'],['../instruction_manual.html#qemu-execution-command-breakdown',1,'QEMU Execution Command Breakdown'],['../instruction_manual.html#summary-qemu-command-breakdown',1,'Summary: QEMU Command Breakdown']]],
  ['command_20linux_20target_40',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['command_20not_20found_41',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['command_20patterns_42',['Command Patterns',['../md_guides_2AGENT.html#command-patterns',1,'']]],
  ['commands_43',['commands',['../md_guides_2AGENT.html#before-running-destructive-commands',1,'Before Running Destructive Commands'],['../instruction_manual.html#compilation-commands',1,'Compilation Commands'],['../instruction_manual.html#execution-commands',1,'Execution Commands']]],
  ['commands_20inside_20container_20directly_44',['Running Commands Inside Container Directly',['../md_guides_2AGENT.html#running-commands-inside-container-directly',1,'']]],
  ['common_20intrinsics_45',['Common Intrinsics',['../instruction_manual.html#common-intrinsics',1,'']]],
  ['common_20qemu_20errors_20solutions_46',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['common_20rvv_20patterns_47',['Common RVV Patterns',['../instruction_manual.html#common-rvv-patterns',1,'']]],
  ['common_20tasks_20for_20agents_48',['Common Tasks for Agents',['../md_guides_2AGENT.html#common-tasks-for-agents',1,'']]],
  ['compilation_49',['Stage 2: Compilation',['../instruction_manual.html#stage-2-compilation',1,'']]],
  ['compilation_20command_20linux_20target_50',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['compilation_20commands_51',['Compilation Commands',['../instruction_manual.html#compilation-commands',1,'']]],
  ['compilation_20deep_20dive_52',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['compilation_20oom_20killed_20even_20with_20moderate_20parallelism_53',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['compilation_20output_54',['Inspecting Compilation Output',['../instruction_manual.html#inspecting-compilation-output',1,'']]],
  ['compilation_20stages_55',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['compiler_56',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['compiler_20integration_57',['4. Software Usage &amp; Compiler Integration',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md4-software-usage--compiler-integration',1,'']]],
  ['compiler_20selection_3a_20linux_20vs_20bare_20metal_58',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['complete_20example_3a_20what_20happens_20when_20you_20run_20the_20command_59',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['complete_20flow_60',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['component_20structure_61',['Component Structure',['../instruction_manual.html#component-structure',1,'']]],
  ['compress_20store_62',['B. &lt;tt&gt;vstore_compressed.v&lt;/tt&gt; (Fused Compress-Store)',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#b-vstore_compressedv-fused-compress-store',1,'']]],
  ['compute_5fcovariance_5frvv_63',['compute_covariance_rvv',['../namespacervv__pcl.html#a7579c4594b9c3142399c0ebc4818d8b0',1,'rvv_pcl']]],
  ['concepts_64',['concepts',['../vector_theory.html#key-rvv-concepts',1,'Key RVV Concepts'],['../instruction_manual.html#rvv-programming-concepts',1,'RVV Programming Concepts']]],
  ['configuration_65',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['configuration_20options_20summary_66',['Configuration Options Summary',['../instruction_manual.html#configuration-options-summary',1,'']]],
  ['constrs_20cc_20tt_20compilation_20oom_20killed_20even_20with_20moderate_20parallelism_67',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['container_68',['CMake Build (inside container)',['../md_guides_2AGENT.html#cmake-build-inside-container',1,'']]],
  ['container_20directly_69',['Running Commands Inside Container Directly',['../md_guides_2AGENT.html#running-commands-inside-container-directly',1,'']]],
  ['container_20memory_20cap_20—_20container_20sees_20less_20ram_20than_20host_70',['Stale container memory cap — container sees less RAM than host',['../md_guides_2session__2026-04-07.html#stale-container-memory-cap--container-sees-less-ram-than-host',1,'']]],
  ['container_20ram_20to_205_206_20gb_71',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['container_20recommended_72',['Dev Container (Recommended)',['../index.html#dev-container-recommended',1,'']]],
  ['containers_73',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['contents_74',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['convention_75',['3. Intrinsics Naming Convention',['../vector_theory.html#autotoc_md3-intrinsics-naming-convention',1,'']]],
  ['core_20algorithms_76',['core algorithms',['../instruction_manual.html#core-algorithms',1,'Core Algorithms'],['../instruction_manual.html#the-5-core-algorithms',1,'The 5 Core Algorithms']]],
  ['core_20architecture_77',['1. The Core Architecture',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md1-the-core-architecture',1,'']]],
  ['core_20headers_78',['Before Editing Core Headers',['../md_guides_2AGENT.html#before-editing-core-headers',1,'']]],
  ['core_20logic_3a_20tt_20get_5fdist_5fsq_5frvv_20tt_79',['Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;',['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'']]],
  ['cost_80',['Ground Truth Generation Is Not Pipeline Cost',['../md_guides_2AGENT.html#ground-truth-generation-is-not-pipeline-cost',1,'']]],
  ['counting_81',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['counting_20methodology_82',['Instruction Counting Methodology',['../md_tests_2INSTRUCTION__COUNTING.html',1,'']]],
  ['counting_20rdinstret_83',['Instruction Counting (rdinstret)',['../md_guides_2AGENT.html#instruction-counting-rdinstret',1,'']]],
  ['counts_84',['counts',['../structrvv__pcl_1_1detail_1_1PCDHeader.html#a4c64decdc26563a6eecec9e88ff9f7c3',1,'rvv_pcl::detail::PCDHeader']]],
  ['cpp_20tt_85',['Key RVV Kernels (in &lt;tt&gt;rvv_common.cpp&lt;/tt&gt;)',['../md_guides_2AGENT.html#key-rvv-kernels-in-rvv_commoncpp',1,'']]],
  ['cpu_86',['cpu',['../namespacegem5__se.html#aa3bdd4ab99676855567984731b972beb',1,'gem5_se']]],
  ['cpu_20configuration_87',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['cpu_20rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_88',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['create_20soa_20structure_89',['Create SoA Structure',['../instruction_manual.html#create-soa-structure',1,'']]],
  ['critical_20design_20decision_90',['Data Layout (Critical Design Decision)',['../md_guides_2AGENT.html#data-layout-critical-design-decision',1,'']]],
  ['critical_20gotchas_20for_20agents_91',['Critical Gotchas for Agents',['../md_guides_2AGENT.html#critical-gotchas-for-agents',1,'']]],
  ['cross_20compiler_92',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['current_20status_93',['Current Status',['../md_guides_2AGENT.html#current-status',1,'']]],
  ['custom_20instructions_20specification_94',['2. Custom Instructions Specification',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md2-custom-instructions-specification',1,'']]],
  ['custom_20toolchain_20path_95',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['custom_5fpointer_5foctree_2ecpp_96',['custom_pointer_octree.cpp',['../custom__pointer__octree_8cpp.html',1,'']]],
  ['custom_5fpointer_5foctree_2eh_97',['custom_pointer_octree.h',['../custom__pointer__octree_8h.html',1,'']]],
  ['custom_5frvv_5fintrinsics_2eh_98',['custom_rvv_intrinsics.h',['../custom__rvv__intrinsics_8h.html',1,'']]],
  ['custompointeroctree_99',['custompointeroctree',['../classrvv__pcl_1_1CustomPointerOctree.html#acb179b9309f2a921422a0896b17a1c5d',1,'rvv_pcl::CustomPointerOctree::CustomPointerOctree()'],['../classrvv__pcl_1_1CustomPointerOctree.html',1,'rvv_pcl::CustomPointerOctree']]],
  ['custompointeroctreenode_100',['custompointeroctreenode',['../structrvv__pcl_1_1CustomPointerOctreeNode.html#adf9c46b29791abf7a5e15c711221efcd',1,'rvv_pcl::CustomPointerOctreeNode::CustomPointerOctreeNode()'],['../structrvv__pcl_1_1CustomPointerOctreeNode.html',1,'rvv_pcl::CustomPointerOctreeNode']]]
];
