var searchData=
[
  ['v_20true_20vlen_20128_20tt_20cpu_20configuration_0',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['v_20vector_20optimized_20point_20cloud_20library_1',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['v_20vector_20rvv_20implementation_20guide_2',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['v2_3',['Voxel Grid: Always Use v2',['../md_guides_2AGENT.html#voxel-grid-always-use-v2',1,'']]],
  ['v24_20does_20not_20support_20all_20rvv_20instructions_20—_20tt_20normal_5frvv_20tt_20hits_20tt_20illegalinstfault_20tt_4',['gem5 v24 does not support all RVV instructions — &lt;tt&gt;normal_rvv&lt;/tt&gt; hits &lt;tt&gt;IllegalInstFault&lt;/tt&gt;',['../md_guides_2session__2026-04-07.html#gem5-v24-does-not-support-all-rvv-instructions--normal_rvv-hits-illegalinstfault',1,'']]],
  ['v24_20requires_20tt_20seworkload_20tt_20set_20on_20the_20system_20object_5',['gem5 v24 requires &lt;tt&gt;SEWorkload&lt;/tt&gt; set on the system object',['../md_guides_2session__2026-04-07.html#gem5-v24-requires-seworkload-set-on-the-system-object',1,'']]],
  ['vector_20code_6',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['vector_20execution_20⚡_7',['RVV Vector Execution ⚡',['../instruction_manual.html#rvv-vector-execution-',1,'']]],
  ['vector_20instruction_20emulation_20strong_8',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['vector_20intrinsics_20naming_20guide_9',['3. Vector Intrinsics Naming Guide',['../instruction_manual.html#autotoc_md3-vector-intrinsics-naming-guide',1,'']]],
  ['vector_20masks_20boolean_20vectors_10',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['vector_20optimized_20point_20cloud_20library_11',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['vector_20rvv_20implementation_20guide_12',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['vector_20set_20vector_20length_13',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['vector_20theory_14',['Vector Theory */',['../vector_theory.html',1,'']]],
  ['vector_5fadd_15',['vector_add',['../test__autovec_8c.html#aaee0dc237f945ad81e6e5fc2410d0035',1,'test_autovec.c']]],
  ['vector_5foperations_5fexplained_16',['vector_operations_explained',['../vector_operations_explained.html',1,'']]],
  ['vector_5foperations_5fexplained_2emd_17',['vector_operations_explained.md',['../vector__operations__explained_8md.html',1,'']]],
  ['vectors_18',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['verification_19',['verification',['../index.html#full-verification',1,'Full Verification'],['../instruction_manual.html#testing--verification',1,'Testing &amp; Verification']]],
  ['version_20must_20be_209_202_20',['QEMU Version Must Be 9.2+',['../md_guides_2AGENT.html#qemu-version-must-be-92',1,'']]],
  ['via_20tt_20run_20sh_20tt_21',['rdinstret Benchmark (via &lt;tt&gt;run.sh&lt;/tt&gt;)',['../index.html#rdinstret-benchmark-via-runsh',1,'']]],
  ['visualize_22',['visualize',['../namespacevisualize__result.html#a4f38314714fef01bfcacc7b2770dd038',1,'visualize_result']]],
  ['visualize_5fresult_23',['visualize_result',['../namespacevisualize__result.html',1,'']]],
  ['visualize_5fresult_2epy_24',['visualize_result.py',['../visualize__result_8py.html',1,'']]],
  ['vlen_20128_20tt_20cpu_20configuration_25',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['vluxei32_20tt_20indexed_20load_26',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['vm_20—_20limits_20container_20ram_20to_205_206_20gb_27',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['voltage_5fdomain_28',['voltage_domain',['../namespacegem5__se.html#afa457bea929f91617f46dc6931495c74',1,'gem5_se']]],
  ['voxel_20grid_20downsampling_20strong_29',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['voxel_20grid_20test_30',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['voxel_20grid_3a_20always_20use_20v2_31',['Voxel Grid: Always Use v2',['../md_guides_2AGENT.html#voxel-grid-always-use-v2',1,'']]],
  ['voxel_5fgrid_5fdownsamp_2ecpp_32',['voxel_grid_downsamp.cpp',['../voxel__grid__downsamp_8cpp.html',1,'']]],
  ['voxel_5fgrid_5fdownsamp_5frvv_33',['voxel_grid_downsamp_rvv',['../namespacervv__pcl.html#aeb6d0889fa7a2d26d799e33858c4997a',1,'rvv_pcl']]],
  ['voxel_5fgrid_5fdownsamp_5frvv_5fv2_34',['voxel_grid_downsamp_rvv_v2',['../namespacervv__pcl.html#a4704468dd499c2107740037f835751cc',1,'rvv_pcl']]],
  ['voxel_5fgrid_5fdownsamp_5fsc_35',['voxel_grid_downsamp_sc',['../namespacervv__pcl.html#a4ba723f597780e83a18f39b9bd31e8ac',1,'rvv_pcl']]],
  ['vs_20bare_20metal_36',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['vs_20real_20hardware_37',['QEMU vs Real Hardware',['../instruction_manual.html#qemu-vs-real-hardware',1,'']]],
  ['vsetvl_20tt_20vector_20set_20vector_20length_38',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]]
];
