var searchData=
[
  ['t_20❌_0',['DON&apos;T ❌',['../md_guides_2AGENT.html#dont-',1,'']]],
  ['t_5fstart_1',['t_start',['../structTimer.html#a6bf6a80cee17e6de7f2d22ede224c7d7',1,'Timer']]],
  ['table_2',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['table_20of_20contents_3',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['tag_5flatency_4',['tag_latency',['../namespacegem5__se.html#ade1b510d5fcb29d3a87368f9608dc074',1,'gem5_se']]],
  ['target_5',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['target_20hardware_3a_20banana_20pi_20bpi_20f3_6',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['targeting_20gcc_2014_20strong_7',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['task_201_3a_20running_20the_20full_20test_20suite_8',['Task 1: Running the Full Test Suite',['../md_guides_2AGENT.html#task-1-running-the-full-test-suite',1,'']]],
  ['task_202_3a_20running_20a_20specific_20algorithm_20test_9',['Task 2: Running a Specific Algorithm Test',['../md_guides_2AGENT.html#task-2-running-a-specific-algorithm-test',1,'']]],
  ['task_203_3a_20adding_20a_20new_20algorithm_10',['Task 3: Adding a New Algorithm',['../md_guides_2AGENT.html#task-3-adding-a-new-algorithm',1,'']]],
  ['task_204_3a_20checking_20benchmark_20results_11',['Task 4: Checking Benchmark Results',['../md_guides_2AGENT.html#task-4-checking-benchmark-results',1,'']]],
  ['task_205_3a_20pipeline_20walkthrough_20with_20real_20data_12',['Task 5: Pipeline Walkthrough with Real Data',['../md_guides_2AGENT.html#task-5-pipeline-walkthrough-with-real-data',1,'']]],
  ['task_3a_20e2e_20pipeline_20benchmark_13',['The Priority Task: E2E Pipeline Benchmark',['../md_guides_2AGENT.html#the-priority-task-e2e-pipeline-benchmark',1,'']]],
  ['tasks_20for_20agents_14',['Common Tasks for Agents',['../md_guides_2AGENT.html#common-tasks-for-agents',1,'']]],
  ['tb_20tt_15',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['team_20integration_20usage_20guide_16',['Team Integration &amp; Usage Guide',['../instruction_manual.html#team-integration--usage-guide',1,'']]],
  ['test_17',['test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'Step-by-Step Execution: Voxel Grid Test'],['../md_guides_2AGENT.html#task-2-running-a-specific-algorithm-test',1,'Task 2: Running a Specific Algorithm Test']]],
  ['test_20pattern_18',['Test Pattern',['../instruction_manual.html#test-pattern',1,'']]],
  ['test_20suite_19',['Task 1: Running the Full Test Suite',['../md_guides_2AGENT.html#task-1-running-the-full-test-suite',1,'']]],
  ['test_5fautovec_2ec_20',['test_autovec.c',['../test__autovec_8c.html',1,'']]],
  ['test_5floader_2ecpp_21',['test_loader.cpp',['../test__loader_8cpp.html',1,'']]],
  ['test_5floader_5ffixed_2ecpp_22',['test_loader_fixed.cpp',['../test__loader__fixed_8cpp.html',1,'']]],
  ['test_5floader_5flinux_2ecpp_23',['test_loader_linux.cpp',['../test__loader__linux_8cpp.html',1,'']]],
  ['test_5floader_5fno_5fpcl_2ecpp_24',['test_loader_no_pcl.cpp',['../test__loader__no__pcl_8cpp.html',1,'']]],
  ['test_5floader_5fsimple_2ecpp_25',['test_loader_simple.cpp',['../test__loader__simple_8cpp.html',1,'']]],
  ['test_5fnormal_2ecpp_26',['test_normal.cpp',['../test__normal_8cpp.html',1,'']]],
  ['test_5foctree_2ecpp_27',['test_octree.cpp',['../test__octree_8cpp.html',1,'']]],
  ['test_5fopen_2ec_28',['test_open.c',['../test__open_8c.html',1,'']]],
  ['test_5fpipeline_5fwalkthrough_2ecpp_29',['test_pipeline_walkthrough.cpp',['../test__pipeline__walkthrough_8cpp.html',1,'']]],
  ['test_5fradius_2ecpp_30',['test_radius.cpp',['../test__radius_8cpp.html',1,'']]],
  ['test_5fransac_2ecpp_31',['test_ransac.cpp',['../test__ransac_8cpp.html',1,'']]],
  ['test_5frvv_5ffeatures_2ec_32',['test_rvv_features.c',['../test__rvv__features_8c.html',1,'']]],
  ['test_5fscalar_2ec_33',['test_scalar.c',['../test__scalar_8c.html',1,'']]],
  ['test_5fsor_2ecpp_34',['test_sor.cpp',['../test__sor_8cpp.html',1,'']]],
  ['test_5fspatial_5fhash_5fcomparison_2ecpp_35',['test_spatial_hash_comparison.cpp',['../test__spatial__hash__comparison_8cpp.html',1,'']]],
  ['test_5fspike_2ec_36',['test_spike.c',['../test__spike_8c.html',1,'']]],
  ['test_5ftuples_37',['test_tuples',['../test__tuples_8c.html#a731553bd209edadb53a76cafaaaaa5af',1,'test_tuples.c']]],
  ['test_5ftuples_2ec_38',['test_tuples.c',['../test__tuples_8c.html',1,'']]],
  ['test_5fvector_2ec_39',['test_vector.c',['../test__vector_8c.html',1,'']]],
  ['test_5fvoxel_5fgrid_2ecpp_40',['test_voxel_grid.cpp',['../test__voxel__grid_8cpp.html',1,'']]],
  ['test_5fvoxel_5flinux_2ecpp_41',['test_voxel_linux.cpp',['../test__voxel__linux_8cpp.html',1,'']]],
  ['test_5fvoxel_5frvv_20tt_20output_20filename_42',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['test_5fvoxel_5frvv_20tt_20the_20binary_20to_20execute_43',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['test_5fvoxel_5fscaling_2ecpp_44',['test_voxel_scaling.cpp',['../test__voxel__scaling_8cpp.html',1,'']]],
  ['testing_20verification_45',['Testing &amp; Verification',['../instruction_manual.html#testing--verification',1,'']]],
  ['tests_46',['tests',['../index.html#available-tests',1,'Available tests'],['../index.html#running-tests-1',1,'Running Tests'],['../instruction_manual.html#running-tests',1,'Running Tests']]],
  ['tgts_5fper_5fmshr_47',['tgts_per_mshr',['../namespacegem5__se.html#ad45aca10760133598abd7a967c43943d',1,'gem5_se']]],
  ['than_20host_48',['Stale container memory cap — container sees less RAM than host',['../md_guides_2session__2026-04-07.html#stale-container-memory-cap--container-sees-less-ram-than-host',1,'']]],
  ['the_204_20compilation_20stages_49',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['the_205_20core_20algorithms_50',['The 5 Core Algorithms',['../instruction_manual.html#the-5-core-algorithms',1,'']]],
  ['the_20benchmarks_20measure_51',['What the Benchmarks Measure',['../md_guides_2AGENT.html#what-the-benchmarks-measure',1,'']]],
  ['the_20binary_20to_20execute_52',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['the_20code_53',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['the_20code_20breakdown_54',['The Code Breakdown',['../vector_theory.html#the-code-breakdown',1,'']]],
  ['the_20command_55',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['the_20emulator_56',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['the_20full_20test_20suite_57',['Task 1: Running the Full Test Suite',['../md_guides_2AGENT.html#task-1-running-the-full-test-suite',1,'']]],
  ['the_20linux_20cross_20compiler_58',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['the_20only_20script_20you_20need_59',['The Only Script You Need',['../md_guides_2AGENT.html#the-only-script-you-need',1,'']]],
  ['the_20priority_20task_3a_20e2e_20pipeline_20benchmark_60',['The Priority Task: E2E Pipeline Benchmark',['../md_guides_2AGENT.html#the-priority-task-e2e-pipeline-benchmark',1,'']]],
  ['the_20problem_61',['the problem',['../md_tests_2INSTRUCTION__COUNTING.html#the-problem-1',1,'The Problem'],['../vector_theory.html#the-problem',1,'The Problem']]],
  ['the_20solution_3a_20trace_20based_20counting_62',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['the_20solution_3a_20tt_20vluxei32_20tt_20indexed_20load_63',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['the_20system_20object_64',['gem5 v24 requires &lt;tt&gt;SEWorkload&lt;/tt&gt; set on the system object',['../md_guides_2session__2026-04-07.html#gem5-v24-requires-seworkload-set-on-the-system-object',1,'']]],
  ['theory_65',['Vector Theory */',['../vector_theory.html',1,'']]],
  ['this_20benchmark_66',['Key design rules for this benchmark',['../md_guides_2AGENT.html#key-design-rules-for-this-benchmark',1,'']]],
  ['this_20board_67',['Why this board?',['../instruction_manual.html#why-this-board',1,'']]],
  ['this_20is_20better_68',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['this_20proves_20rvv_20efficiency_69',['Why This Proves RVV Efficiency',['../md_tests_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['this_20session_70',['Work Done This Session',['../md_guides_2session__2026-04-07.html#work-done-this-session',1,'']]],
  ['time_71',['Why Not Wall-Clock Time?',['../md_guides_2AGENT.html#why-not-wall-clock-time',1,'']]],
  ['timer_72',['Timer',['../structTimer.html',1,'']]],
  ['tips_73',['Debugging Tips',['../instruction_manual.html#debugging-tips',1,'']]],
  ['to_205_206_20gb_74',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['to_20execute_75',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['to_20function_20extend_20the_20code_76',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['toolchain_77',['Toolchain',['../index.html#toolchain',1,'']]],
  ['toolchain_20needs_20sysroot_78',['Linux Toolchain Needs Sysroot',['../md_guides_2AGENT.html#linux-toolchain-needs-sysroot',1,'']]],
  ['toolchain_20path_79',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['topics_80',['Advanced Topics',['../instruction_manual.html#advanced-topics',1,'']]],
  ['trace_20based_20counting_81',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['trace_20benchmark_82',['QEMU Trace Benchmark',['../index.html#qemu-trace-benchmark',1,'']]],
  ['trace_20logging_20tt_20d_20exec_20nochain_20tt_83',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['translation_20strong_84',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['true_85',['True',['../namespacegem5__se.html#a3c0c080a09c7ca0e244481bb81a1339d',1,'gem5_se']]],
  ['true_20vlen_20128_20tt_20cpu_20configuration_86',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['truth_20generation_20is_20not_20pipeline_20cost_87',['Ground Truth Generation Is Not Pipeline Cost',['../md_guides_2AGENT.html#ground-truth-generation-is-not-pipeline-cost',1,'']]],
  ['tt_20cpu_20rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_88',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['tt_20d_20exec_20nochain_20tt_89',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['tt_20error_20tt_20guard_20on_20rvv_90',['&lt;tt&gt;#error&lt;/tt&gt; Guard on RVV',['../md_guides_2AGENT.html#error-guard-on-rvv',1,'']]],
  ['tt_20get_5fdist_5fsq_5frvv_20tt_91',['tt get_dist_sq_rvv tt',['../instruction_manual.html#get_dist_sq_rvv',1,'&lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;'],['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;']]],
  ['tt_20get_5finds_5fin_5fradius_5frvv_20tt_92',['&lt;tt&gt;get_inds_in_radius_rvv&lt;/tt&gt;',['../instruction_manual.html#get_inds_in_radius_rvv',1,'']]],
  ['tt_20i_20src_20include_20tt_20include_20directory_93',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['tt_20inst_20constrs_20cc_20tt_20compilation_20oom_20killed_20even_20with_20moderate_20parallelism_94',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['tt_20loadpcd_20file_5fpath_20points_5fvector_20tt_95',['&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'']]],
  ['tt_20mabi_20lp64d_20tt_20application_20binary_20interface_96',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['tt_20march_20rv64gcv_20tt_20architecture_20specification_97',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['tt_20mkswap_20q_20tt_20flag_20does_20not_20exist_20on_20ubuntu_2022_2004_98',['&lt;tt&gt;mkswap -q&lt;/tt&gt; flag does not exist on Ubuntu 22.04',['../md_guides_2session__2026-04-07.html#mkswap--q-flag-does-not-exist-on-ubuntu-2204',1,'']]],
  ['tt_20normal_5frvv_20tt_20hits_20tt_20illegalinstfault_20tt_99',['gem5 v24 does not support all RVV instructions — &lt;tt&gt;normal_rvv&lt;/tt&gt; hits &lt;tt&gt;IllegalInstFault&lt;/tt&gt;',['../md_guides_2session__2026-04-07.html#gem5-v24-does-not-support-all-rvv-instructions--normal_rvv-hits-illegalinstfault',1,'']]],
  ['tt_20o_20test_5fvoxel_5frvv_20tt_20output_20filename_100',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['tt_20octree_20tt_20strong_101',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['tt_20one_20insn_20per_20tb_20tt_102',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['tt_20qemu_20riscv64_20tt_20the_20emulator_103',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['tt_20riscv64_20linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_104',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['tt_20run_20sh_20tt_105',['rdinstret Benchmark (via &lt;tt&gt;run.sh&lt;/tt&gt;)',['../index.html#rdinstret-benchmark-via-runsh',1,'']]],
  ['tt_20rvv_5fcommon_20cpp_20tt_106',['Key RVV Kernels (in &lt;tt&gt;rvv_common.cpp&lt;/tt&gt;)',['../md_guides_2AGENT.html#key-rvv-kernels-in-rvv_commoncpp',1,'']]],
  ['tt_20savepcd_20file_5fpath_20points_5fvector_20tt_107',['&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#savepcdfile_path-points_vector',1,'']]],
  ['tt_20seworkload_20tt_20set_20on_20the_20system_20object_108',['gem5 v24 requires &lt;tt&gt;SEWorkload&lt;/tt&gt; set on the system object',['../md_guides_2session__2026-04-07.html#gem5-v24-requires-seworkload-set-on-the-system-object',1,'']]],
  ['tt_20spatialhash_20tt_20strong_109',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['tt_20struct_20pointcloudsoa_20tt_110',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['tt_20struct_20pointxyz_20tt_111',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['tt_20swapon_20tt_20is_20impossible_20inside_20docker_20containers_112',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['tt_20test_5fvoxel_5frvv_20tt_20the_20binary_20to_20execute_113',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['tt_20vluxei32_20tt_20indexed_20load_114',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['tt_20vsetvl_20tt_20vector_20set_20vector_20length_115',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['tuning_116',['Performance Tuning',['../instruction_manual.html#performance-tuning',1,'']]],
  ['txt_20addition_117',['CMakeLists.txt addition',['../md_guides_2AGENT.html#cmakeliststxt-addition',1,'']]],
  ['types_118',['types',['../structrvv__pcl_1_1detail_1_1PCDHeader.html#a98f31d73e0e4684d7fc5b3827fde3f2c',1,'rvv_pcl::detail::PCDHeader']]]
];
