var searchData=
[
  ['p1_5f_0',['p1_',['../classrvpoint_1_1SpatialHash.html#ad5969d2a8dc6940dc091916ee01660ab',1,'rvpoint::SpatialHash']]],
  ['p2_5f_1',['p2_',['../classrvpoint_1_1SpatialHash.html#afc3c19c05f7e69496cbb73459e031b7a',1,'rvpoint::SpatialHash']]],
  ['pack_5fxyz_2',['pack_xyz',['../namespaceexport__mcap.html#a058f3ae2cf5fa1017f32efa389beb0ba',1,'export_mcap']]],
  ['pack_5fxyzrgb_3',['pack_xyzrgb',['../namespaceexport__mcap.html#a129930b5bd3588844d768947dc01e5c0',1,'export_mcap']]],
  ['parent_4',['parent',['../structDisjointSet3D.html#a57bbd729d54e252c8b932717d514ff3a',1,'DisjointSet3D']]],
  ['parsekernel_5',['parseKernel',['../namespacervpoint_1_1bench.html#af27130d07ba1579e5239edc27d370fbd',1,'rvpoint::bench']]],
  ['parsepcdheader_6',['parsePCDHeader',['../namespacervpoint_1_1detail.html#a596e148af0d2d0ff6ae9538732170bed',1,'rvpoint::detail']]],
  ['path_7',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['pattern_8',['pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'1. Strip Mining Pattern'],['../instruction_manual.html#test-pattern',1,'Test Pattern']]],
  ['patterns_9',['Common RVV Patterns',['../instruction_manual.html#common-rvv-patterns',1,'']]],
  ['pcdheader_10',['PCDHeader',['../structrvpoint_1_1detail_1_1PCDHeader.html',1,'rvpoint::detail']]],
  ['pcl_5fpipeline_5fbenchmark_2ecpp_11',['pcl_pipeline_benchmark.cpp',['../pcl__pipeline__benchmark_8cpp.html',1,'']]],
  ['pcl_5fstandalone_5fpipeline_2ecpp_12',['pcl_standalone_pipeline.cpp',['../pcl__standalone__pipeline_8cpp.html',1,'']]],
  ['per_20tb_20tt_13',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['perception_20architecture_14',['Real-Time RVV Point Cloud Perception Architecture',['../md_docs_2projection.html',1,'']]],
  ['performance_20impact_15',['3. Key Synergy &amp; Expected Performance Impact',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md3-key-synergy--expected-performance-impact',1,'']]],
  ['performance_20profiling_20bottleneck_20analysis_20report_16',['Pipeline Performance Profiling &amp; Bottleneck Analysis Report',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html',1,'']]],
  ['performance_20summary_20table_17',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['performance_20tuning_18',['Performance Tuning',['../instruction_manual.html#performance-tuning',1,'']]],
  ['phase_201_20pipeline_20profiling_20matrix_19',['2. Phase 1 Pipeline Profiling Matrix',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md2-phase-1-pipeline-profiling-matrix',1,'']]],
  ['phase_201_3a_20initialization_20strong_20',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['phase_201_3a_20pipeline_20stage_20sub_20stage_20micro_20timing_20breakdown_21',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['phase_202_20component_20level_20implementation_20ablations_22',['3. Phase 2 Component-Level Implementation Ablations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md3-phase-2-component-level-implementation-ablations',1,'']]],
  ['phase_202_3a_20comparative_20implementation_20ablations_23',['4. Phase 2: Comparative Implementation Ablations',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md4-phase-2-comparative-implementation-ablations',1,'']]],
  ['phase_202_3a_20instruction_20execution_20loop_20strong_24',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['phase_203_3a_20system_20call_20translation_20strong_25',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['phase_204_3a_20vector_20instruction_20emulation_20strong_26',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['phase_20workflow_20tt_20scripts_20profile_5fpipeline_20py_20tt_27',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]],
  ['pi_20bpi_20f3_28',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['pipeline_29',['🤖 CI/CD Pipeline',['../index.html#autotoc_md-cicd-pipeline',1,'']]],
  ['pipeline_20performance_20profiling_20bottleneck_20analysis_20report_30',['Pipeline Performance Profiling &amp; Bottleneck Analysis Report',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html',1,'']]],
  ['pipeline_20profiling_20implementation_20ablation_20experiment_20report_31',['RVPoint Pipeline Profiling &amp; Implementation Ablation Experiment Report',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html',1,'']]],
  ['pipeline_20profiling_20matrix_32',['2. Phase 1 Pipeline Profiling Matrix',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md2-phase-1-pipeline-profiling-matrix',1,'']]],
  ['pipeline_20stage_20sub_20stage_20micro_20timing_20breakdown_33',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['pipeline_3a_34',['pipeline:',['../md_docs_2projection.html#autotoc_md1-run-hardware-accelerated-rvv-ultra-fast-pipeline',1,'1. Run Hardware-Accelerated RVV Ultra-Fast Pipeline:'],['../md_docs_2projection.html#autotoc_md2-run-fast-25d-elevation-grid-export-pipeline',1,'2. Run Fast 2.5D Elevation Grid Export Pipeline:'],['../md_docs_2projection.html#autotoc_md3-run-original-hierarchical-octree-pipeline',1,'3. Run Original Hierarchical Octree Pipeline:']]],
  ['pipeline_5f3d_5fturbo_2ecpp_35',['pipeline_3d_turbo.cpp',['../pipeline__3d__turbo_8cpp.html',1,'']]],
  ['pipeline_5fcompare_5fbench_2ecpp_36',['pipeline_compare_bench.cpp',['../pipeline__compare__bench_8cpp.html',1,'']]],
  ['pipeline_5fexport_20tt_20capped_20at_201_206×_20speedup_37',['2. Why &lt;tt&gt;pipeline_export&lt;/tt&gt; Capped at ~1.6× Speedup',['../md_docs_2projection.html#autotoc_md2-why-pipeline_export-capped-at-16-speedup',1,'']]],
  ['pipeline_5fexport_2ecpp_38',['pipeline_export.cpp',['../pipeline__export_8cpp.html',1,'']]],
  ['pipeline_5ffast_5fexport_20tt_20vs_20tt_20pipeline_5frvv_5fultra_5ffast_20tt_39',['5. Architectural Comparison: &lt;tt&gt;pipeline_fast_export&lt;/tt&gt; vs &lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;',['../md_docs_2projection.html#autotoc_md5-architectural-comparison-pipeline_fast_export-vs-pipeline_rvv_ultra_fast',1,'']]],
  ['pipeline_5ffast_5fexport_2ecpp_40',['pipeline_fast_export.cpp',['../pipeline__fast__export_8cpp.html',1,'']]],
  ['pipeline_5fprofiling_5fand_5fablation_5fexperiment_2emd_41',['PIPELINE_PROFILING_AND_ABLATION_EXPERIMENT.md',['../PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT_8md.html',1,'']]],
  ['pipeline_5frvv_5fturbo_2ecpp_42',['pipeline_rvv_turbo.cpp',['../pipeline__rvv__turbo_8cpp.html',1,'']]],
  ['pipeline_5frvv_5fultra_5ffast_20tt_43',['pipeline_rvv_ultra_fast tt',['../md_docs_2projection.html#autotoc_md4-hardware-rvv-10-vectorization-pipeline_rvv_ultra_fast',1,'4. Hardware RVV 1.0 Vectorization (&lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;)'],['../md_docs_2projection.html#autotoc_md5-architectural-comparison-pipeline_fast_export-vs-pipeline_rvv_ultra_fast',1,'5. Architectural Comparison: &lt;tt&gt;pipeline_fast_export&lt;/tt&gt; vs &lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;']]],
  ['pipeline_5frvv_5fultra_5ffast_2ecpp_44',['pipeline_rvv_ultra_fast.cpp',['../pipeline__rvv__ultra__fast_8cpp.html',1,'']]],
  ['plane_20fitting_20iteration_20scaling_45',['plane fitting iteration scaling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-d-ransac-plane-fitting-iteration-scaling-1',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-d-ransac-plane-fitting-iteration-scaling',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling']]],
  ['plane_20fitting_20strong_46',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['plane3d_47',['Plane3D',['../structPlane3D.html',1,'']]],
  ['point_20cloud_20library_48',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['point_20cloud_20perception_20architecture_49',['Real-Time RVV Point Cloud Perception Architecture',['../md_docs_2projection.html',1,'']]],
  ['point_5findices_50',['point_indices',['../structSIMDOctreeNode8Wide.html#a6e14a97782279ec40437c24c5c43f499',1,'SIMDOctreeNode8Wide']]],
  ['point_5ftypes_2eh_51',['point_types.h',['../point__types_8h.html',1,'']]],
  ['pointcloudsoa_52',['PointCloudSoA',['../structrvpoint_1_1PointCloudSoA.html',1,'rvpoint']]],
  ['pointcloudsoa_20tt_53',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['pointer_5foctree_2ecpp_54',['pointer_octree.cpp',['../pointer__octree_8cpp.html',1,'']]],
  ['pointer_5foctree_2eh_55',['pointer_octree.h',['../pointer__octree_8h.html',1,'']]],
  ['pointeroctree_56',['pointeroctree',['../classrvpoint_1_1PointerOctree.html',1,'rvpoint::PointerOctree'],['../classrvpoint_1_1PointerOctree.html#af0546bf095b9b703e7f77268ad3cf832',1,'rvpoint::PointerOctree::PointerOctree()']]],
  ['pointeroctree_20hybrid_3a_20architecture_20technical_20design_20document_57',['Caravan-PointerOctree Hybrid: Architecture &amp; Technical Design Document',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html',1,'']]],
  ['pointeroctree_20tt_58',['4. API Extensions to &lt;tt&gt;PointerOctree&lt;/tt&gt;',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md4-api-extensions-to-pointeroctree',1,'']]],
  ['pointeroctreenode_59',['pointeroctreenode',['../structrvpoint_1_1PointerOctreeNode.html#a9fe4edbd4864b54fb440381b7acb4f08',1,'rvpoint::PointerOctreeNode::PointerOctreeNode()'],['../structrvpoint_1_1PointerOctreeNode.html',1,'rvpoint::PointerOctreeNode']]],
  ['pointkey_60',['PointKey',['../structLinearMortonOctree_1_1PointKey.html',1,'LinearMortonOctree']]],
  ['points_61',['points',['../structrvpoint_1_1detail_1_1PCDHeader.html#aebb8d814c069931946c2d0c82b46f3d0',1,'rvpoint::detail::PCDHeader']]],
  ['points_5fvector_20tt_62',['points_vector tt',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;'],['../instruction_manual.html#savepcdfile_path-points_vector',1,'&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;']]],
  ['pointxyz_63',['PointXYZ',['../structrvpoint_1_1PointXYZ.html',1,'rvpoint']]],
  ['pointxyz_20tt_64',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['pointxyzrgb_65',['PointXYZRGB',['../structrvpoint_1_1PointXYZRGB.html',1,'rvpoint']]],
  ['prebuild_5fbackends_66',['prebuild_backends',['../namespacegem5batch.html#adb3d22a2c0cc536865ff6d6b03c9559d',1,'gem5batch']]],
  ['preprocessing_67',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]],
  ['prerequisites_68',['prerequisites',['../md_docs_2setup.html#autotoc_md0-prerequisites',1,'0. Prerequisites'],['../index.html#prerequisites',1,'Prerequisites']]],
  ['printusage_69',['printUsage',['../test__pcd__radius_8cpp.html#aead97c99e70c0da7036fbbe230ef68b6',1,'test_pcd_radius.cpp']]],
  ['problem_70',['problem',['../md_docs_2INSTRUCTION__COUNTING.html#the-problem',1,'The Problem'],['../vector_theory.html#the-problem-1',1,'The Problem']]],
  ['problem_20statement_71',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['products_72',['C. Eliminating 50 Million RANSAC Cross/Dot-Products',['../md_docs_2projection.html#c-eliminating-50-million-ransac-crossdot-products',1,'']]],
  ['profile_5fpipeline_73',['profile_pipeline',['../namespaceprofile__pipeline.html',1,'']]],
  ['profile_5fpipeline_20py_20tt_74',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]],
  ['profile_5fpipeline_2epy_75',['profile_pipeline.py',['../profile__pipeline_8py.html',1,'']]],
  ['profiler_20h_20tt_76',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['profiler_2eh_77',['profiler.h',['../profiler_8h.html',1,'']]],
  ['profiling_20bottleneck_20analysis_20report_78',['Pipeline Performance Profiling &amp; Bottleneck Analysis Report',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html',1,'']]],
  ['profiling_20implementation_20ablation_20experiment_20report_79',['RVPoint Pipeline Profiling &amp; Implementation Ablation Experiment Report',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html',1,'']]],
  ['profiling_20matrix_80',['2. Phase 1 Pipeline Profiling Matrix',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md2-phase-1-pipeline-profiling-matrix',1,'']]],
  ['program_20start_81',['Program Start',['../instruction_manual.html#program-start',1,'']]],
  ['programming_20concepts_82',['RVV Programming Concepts',['../instruction_manual.html#rvv-programming-concepts',1,'']]],
  ['project_83',['7. Building and running the project',['../md_docs_2setup.html#autotoc_md7-building-and-running-the-project',1,'']]],
  ['project_20navigation_84',['project navigation',['../vector_theory.html#️-project-navigation-2',1,'🗺️ Project Navigation'],['../instruction_manual.html#️-project-navigation-1',1,'🗺️ Project Navigation'],['../md_docs_2INSTRUCTION__COUNTING.html#️-project-navigation',1,'🗺️ Project Navigation']]],
  ['project_20structure_85',['📂 Project Structure',['../index.html#autotoc_md-project-structure',1,'']]],
  ['project_5froot_86',['PROJECT_ROOT',['../namespacegem5batch.html#a03a89349de8f6de2c1b53775989b9087',1,'gem5batch']]],
  ['projection_20_24_20mathbb_20r_203_20rightarrow_20mathbb_20r_202_24_87',['A. Orthogonal Projection ($\mathbb{R}^3 \rightarrow \mathbb{R}^2$)',['../md_docs_2projection.html#a-orthogonal-projection-mathbbr3-rightarrow-mathbbr2',1,'']]],
  ['projection_2emd_88',['projection.md',['../projection_8md.html',1,'']]],
  ['proves_20rvv_20efficiency_89',['Why This Proves RVV Efficiency',['../md_docs_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['providers_90',['PROVIDERS',['../namespaceserve__mcap.html#a8c84feabaefbbfc80c47d50ac77b111f',1,'serve_mcap']]],
  ['ptr_5foctree_5f_91',['ptr_octree_',['../classrvpoint_1_1CaravanPointerOctree.html#a6bdde656580e60102307aeca7e891b94',1,'rvpoint::CaravanPointerOctree']]],
  ['ptr_5fsearcher_5f_92',['ptr_searcher_',['../classrvpoint_1_1EuclideanClustering.html#aac96190a64242be8c626944bfaf5768f',1,'rvpoint::EuclideanClustering']]],
  ['py_20tt_93',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]]
];
