var searchData=
[
  ['l2bus_0',['l2bus',['../namespacegem5__se.html#a6e1d40e69c4a2a2b2c2532ac21974a39',1,'gem5_se']]],
  ['l2cache_1',['l2cache',['../namespacegem5__se.html#a16195cee872409fd47d90a0306317dbf',1,'gem5_se']]],
  ['layout_20critical_20design_20decision_2',['Data Layout (Critical Design Decision)',['../md_guides_2AGENT.html#data-layout-critical-design-decision',1,'']]],
  ['learned_3',['Session Logs (Hard Limits &amp; Lessons Learned)',['../md_guides_2AGENT.html#session-logs-hard-limits--lessons-learned',1,'']]],
  ['length_4',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['length_20multiplier_5',['2. LMUL (Length Multiplier)',['../instruction_manual.html#autotoc_md2-lmul-length-multiplier',1,'']]],
  ['less_20ram_20than_20host_6',['Stale container memory cap — container sees less RAM than host',['../md_guides_2session__2026-04-07.html#stale-container-memory-cap--container-sees-less-ram-than-host',1,'']]],
  ['lessons_20learned_7',['Session Logs (Hard Limits &amp; Lessons Learned)',['../md_guides_2AGENT.html#session-logs-hard-limits--lessons-learned',1,'']]],
  ['libraries_20strong_8',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['library_9',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['license_10',['License',['../index.html#license',1,'']]],
  ['limits_20container_20ram_20to_205_206_20gb_11',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['limits_20discovered_12',['Hard Limits Discovered',['../md_guides_2session__2026-04-07.html#hard-limits-discovered',1,'']]],
  ['limits_20lessons_20learned_13',['Session Logs (Hard Limits &amp; Lessons Learned)',['../md_guides_2AGENT.html#session-logs-hard-limits--lessons-learned',1,'']]],
  ['linker_20oom_20killed_20with_20high_20parallelism_14',['gem5 linker OOM-killed with high parallelism',['../md_guides_2session__2026-04-07.html#gem5-linker-oom-killed-with-high-parallelism',1,'']]],
  ['linking_15',['Stage 4: Linking',['../instruction_manual.html#stage-4-linking',1,'']]],
  ['linux_20cross_20compiler_16',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_17',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['linux_20target_18',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['linux_20toolchain_20needs_20sysroot_19',['Linux Toolchain Needs Sysroot',['../md_guides_2AGENT.html#linux-toolchain-needs-sysroot',1,'']]],
  ['linux_20uses_20a_20qemu_20vm_20—_20limits_20container_20ram_20to_205_206_20gb_20',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['linux_20vs_20bare_20metal_21',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['list_22',['Deprecated List',['../deprecated.html',1,'']]],
  ['lmul_20length_20multiplier_23',['2. LMUL (Length Multiplier)',['../instruction_manual.html#autotoc_md2-lmul-length-multiplier',1,'']]],
  ['lmul_20register_20grouping_24',['2. LMUL (Register Grouping)',['../vector_theory.html#autotoc_md2-lmul-register-grouping',1,'']]],
  ['load_25',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['load_5fpcd_26',['load_pcd',['../namespacevisualize__result.html#a01ab7ebdc0417d3f4a6544af600cdc46',1,'visualize_result']]],
  ['loadpcd_27',['loadPCD',['../namespacervv__pcl.html#ad513fe0e21cc1b7ae4c1086b415473d0',1,'rvv_pcl']]],
  ['loadpcd_20file_5fpath_20points_5fvector_20tt_28',['&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'']]],
  ['log_3a_202026_2004_2007_29',['Session Log: 2026-04-07',['../md_guides_2session__2026-04-07.html',1,'']]],
  ['logging_20tt_20d_20exec_20nochain_20tt_30',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['logic_3a_20tt_20get_5fdist_5fsq_5frvv_20tt_31',['Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;',['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'']]],
  ['logs_20hard_20limits_20lessons_20learned_32',['Session Logs (Hard Limits &amp; Lessons Learned)',['../md_guides_2AGENT.html#session-logs-hard-limits--lessons-learned',1,'']]],
  ['loop_20strong_33',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['lp64d_20tt_20application_20binary_20interface_34',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]]
];
