var searchData=
[
  ['d_0',['d',['../structPlane3D.html#a1848dacc27ec81e8304025ec3e17a2da',1,'Plane3D']]],
  ['d_20connected_20component_202_205d_20grid_20bfs_1',['D. Connected-Component 2.5D Grid BFS',['../md_docs_2projection.html#d-connected-component-25d-grid-bfs',1,'']]],
  ['d_20exec_20nochain_20tt_2',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['d_3a_20ransac_20plane_20fitting_20iteration_20scaling_3',['d: ransac plane fitting iteration scaling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-d-ransac-plane-fitting-iteration-scaling-1',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-d-ransac-plane-fitting-iteration-scaling',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling']]],
  ['data_20generation_4',['Data Generation',['../instruction_manual.html#data-generation',1,'']]],
  ['data_20structures_5',['data structures',['../instruction_manual.html#data-structures-1',1,'Data Structures'],['../instruction_manual.html#data-structures',1,'Data Structures']]],
  ['data_5ftype_6',['data_type',['../structrvpoint_1_1detail_1_1PCDHeader.html#aaf3225a1d21ac79519ff5b997a28a8d3',1,'rvpoint::detail::PCDHeader']]],
  ['debugging_20tips_7',['Debugging Tips',['../instruction_manual.html#debugging-tips',1,'']]],
  ['decompositions_8',['B. Eliminating $50,000$ Matrix Eigen-Decompositions',['../md_docs_2projection.html#b-eliminating-50000-matrix-eigen-decompositions',1,'']]],
  ['decompresslzf_9',['decompressLZF',['../namespacervpoint_1_1detail.html#aa4c9c75369acde93fe7a6d68a42c117f',1,'rvpoint::detail']]],
  ['deep_20dive_10',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['default_5ftasks_11',['DEFAULT_TASKS',['../namespacegem5batch.html#aa7b4a401e1f4823e4d092ec572174222',1,'gem5batch']]],
  ['design_12',['2. Infrastructure &amp; Diagnostic Design',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md2-infrastructure--diagnostic-design',1,'']]],
  ['design_20document_13',['Caravan-PointerOctree Hybrid: Architecture &amp; Technical Design Document',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html',1,'']]],
  ['design_20vector_20mechanics_14',['2. Architectural Design &amp; Vector Mechanics',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md2-architectural-design--vector-mechanics',1,'']]],
  ['detailed_20verification_20steps_20manual_15',['Detailed Verification Steps (Manual)',['../index.html#detailed-verification-steps-manual',1,'']]],
  ['dev_20container_16',['2. Create the dev container',['../md_docs_2setup.html#autotoc_md2-create-the-dev-container',1,'']]],
  ['development_20workflow_17',['1. Standardized Development Workflow',['../instruction_manual.html#autotoc_md1-standardized-development-workflow',1,'']]],
  ['diagnostic_20design_18',['2. Infrastructure &amp; Diagnostic Design',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md2-infrastructure--diagnostic-design',1,'']]],
  ['directory_19',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['discover_5favailable_5fstages_20',['discover_available_stages',['../namespaceexport__mcap.html#aaa8960863a102ed148332a9079020ab6',1,'export_mcap']]],
  ['discover_5fframes_21',['discover_frames',['../namespaceexport__mcap.html#a621b326a7885ec71fb6d9762b8b00c19',1,'export_mcap']]],
  ['disjointset3d_22',['disjointset3d',['../structDisjointSet3D.html',1,'DisjointSet3D'],['../structDisjointSet3D.html#a51241594d7ded8bc964548768d75951c',1,'DisjointSet3D::DisjointSet3D()']]],
  ['distance_20calculation_23',['Distance Calculation',['../instruction_manual.html#distance-calculation',1,'']]],
  ['dive_24',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['do_5fget_25',['do_GET',['../classserve__mcap_1_1FoxgloveCORSHandler.html#a7ff55db78daf7a5ea775e5c3ae5ec8b9',1,'serve_mcap::FoxgloveCORSHandler']]],
  ['do_5foptions_26',['do_OPTIONS',['../classserve__mcap_1_1FoxgloveCORSHandler.html#a26e078dc5f9c1d40455c46040efbf07a',1,'serve_mcap::FoxgloveCORSHandler']]],
  ['docker_20cli_20inside_20the_20container_27',['3. Install the Docker CLI inside the container',['../md_docs_2setup.html#autotoc_md3-install-the-docker-cli-inside-the-container',1,'']]],
  ['docker_20environment_20setup_28',['RVPoint Docker Environment Setup',['../md_docs_2setup.html',1,'']]],
  ['docker_20image_20the_20wrapper_20script_20s_20approach_29',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['docker_20manual_30',['Running with Docker (Manual)',['../index.html#running-with-docker-manual',1,'']]],
  ['document_31',['Caravan-PointerOctree Hybrid: Architecture &amp; Technical Design Document',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html',1,'']]],
  ['documentation_20resources_32',['Documentation &amp; Resources',['../index.html#documentation--resources',1,'']]],
  ['does_20internally_20complete_20flow_33',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['dot_20products_34',['C. Eliminating 50 Million RANSAC Cross/Dot-Products',['../md_docs_2projection.html#c-eliminating-50-million-ransac-crossdot-products',1,'']]],
  ['down_20rebuilding_20clean_35',['8. Tearing down / rebuilding clean',['../md_docs_2setup.html#autotoc_md8-tearing-down--rebuilding-clean',1,'']]],
  ['downsampling_36',['Ablation A: Voxel Grid Downsampling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-a-voxel-grid-downsampling',1,'']]],
  ['downsampling_20_24n_20114_20278_20to_2018_20542_24_37',['Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'']]],
  ['downsampling_20strong_38',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]]
];
