var searchData=
[
  ['t_5fstart_0',['t_start',['../classTimer.html#a6bf6a80cee17e6de7f2d22ede224c7d7',1,'Timer']]],
  ['table_1',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['table_20of_20contents_2',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['table_5f_3',['table_',['../classCompactSparse3DGridBench.html#af90ca22bfaf2b7ab4d0d570b8afe10a2',1,'CompactSparse3DGridBench']]],
  ['target_4',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['target_20hardware_3a_20banana_20pi_20bpi_20f3_5',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['target_5ffilepath_6',['target_filepath',['../classserve__mcap_1_1FoxgloveCORSHandler.html#add44dc3efd347e6d07fc3f867f1eb76f',1,'serve_mcap.FoxgloveCORSHandler.target_filepath'],['../classserve__mcap_1_1FoxgloveCORSHandler.html#abee775d8935c5bab2cd8d72efc497797',1,'serve_mcap.FoxgloveCORSHandler.target_filepath']]],
  ['targeted_20architectural_20optimization_20recommendations_7',['4. Targeted Architectural Optimization Recommendations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md4-targeted-architectural-optimization-recommendations',1,'']]],
  ['targeting_20gcc_2014_20strong_8',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['tasks_3a_9',['Completed Tasks:',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#completed-tasks',1,'']]],
  ['tb_20tt_10',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['team_20integration_20usage_20guide_11',['Team Integration &amp; Usage Guide',['../instruction_manual.html#team-integration--usage-guide',1,'']]],
  ['tearing_20down_20rebuilding_20clean_12',['8. Tearing down / rebuilding clean',['../md_docs_2setup.html#autotoc_md8-tearing-down--rebuilding-clean',1,'']]],
  ['technical_20design_20document_13',['Caravan-PointerOctree Hybrid: Architecture &amp; Technical Design Document',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html',1,'']]],
  ['test_14',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['test_20pattern_15',['Test Pattern',['../instruction_manual.html#test-pattern',1,'']]],
  ['test_5fall_5f3d_5fbranching_5fapproaches_2ecpp_16',['test_all_3d_branching_approaches.cpp',['../test__all__3d__branching__approaches_8cpp.html',1,'']]],
  ['test_5fcaravan_5fvs_5fpointer_5foctree_2ecpp_17',['test_caravan_vs_pointer_octree.cpp',['../test__caravan__vs__pointer__octree_8cpp.html',1,'']]],
  ['test_5feuclidean_5fclustering_2ecpp_18',['test_euclidean_clustering.cpp',['../test__euclidean__clustering_8cpp.html',1,'']]],
  ['test_5fflat_5fgrid_5fpipeline_2ecpp_19',['test_flat_grid_pipeline.cpp',['../test__flat__grid__pipeline_8cpp.html',1,'']]],
  ['test_5ffused_5fhash_5fleaf_5frvv_2ecpp_20',['test_fused_hash_leaf_rvv.cpp',['../test__fused__hash__leaf__rvv_8cpp.html',1,'']]],
  ['test_5ffused_5fturbo_5fvs_5fscalar_2ecpp_21',['test_fused_turbo_vs_scalar.cpp',['../test__fused__turbo__vs__scalar_8cpp.html',1,'']]],
  ['test_5floader_2ecpp_22',['test_loader.cpp',['../test__loader_8cpp.html',1,'']]],
  ['test_5fmulti_5fframe_5fsweep_2ecpp_23',['test_multi_frame_sweep.cpp',['../test__multi__frame__sweep_8cpp.html',1,'']]],
  ['test_5fnormal_2ecpp_24',['test_normal.cpp',['../test__normal_8cpp.html',1,'']]],
  ['test_5foctree_2ecpp_25',['test_octree.cpp',['../test__octree_8cpp.html',1,'']]],
  ['test_5foctree_5fcache_5fbehavior_2ecpp_26',['test_octree_cache_behavior.cpp',['../test__octree__cache__behavior_8cpp.html',1,'']]],
  ['test_5foctree_5fgather_5fvs_5fcontiguous_2ecpp_27',['test_octree_gather_vs_contiguous.cpp',['../test__octree__gather__vs__contiguous_8cpp.html',1,'']]],
  ['test_5foctree_5fleaf_5fsize_5fsweep_2ecpp_28',['test_octree_leaf_size_sweep.cpp',['../test__octree__leaf__size__sweep_8cpp.html',1,'']]],
  ['test_5fopenmp_5frvv_5fscaling_2ecpp_29',['test_openmp_rvv_scaling.cpp',['../test__openmp__rvv__scaling_8cpp.html',1,'']]],
  ['test_5fpcd_5fradius_2ecpp_30',['test_pcd_radius.cpp',['../test__pcd__radius_8cpp.html',1,'']]],
  ['test_5fpipeline_5fwalkthrough_2ecpp_31',['test_pipeline_walkthrough.cpp',['../test__pipeline__walkthrough_8cpp.html',1,'']]],
  ['test_5fpure_5fcompute_5fbenchmark_2ecpp_32',['test_pure_compute_benchmark.cpp',['../test__pure__compute__benchmark_8cpp.html',1,'']]],
  ['test_5fradius_2ecpp_33',['test_radius.cpp',['../test__radius_8cpp.html',1,'']]],
  ['test_5fransac_2ecpp_34',['test_ransac.cpp',['../test__ransac_8cpp.html',1,'']]],
  ['test_5frvpoint_5f3d_5fturbo_5fbench_2ecpp_35',['test_rvpoint_3d_turbo_bench.cpp',['../test__rvpoint__3d__turbo__bench_8cpp.html',1,'']]],
  ['test_5frvv_5ffeatures_2ec_36',['test_rvv_features.c',['../test__rvv__features_8c.html',1,'']]],
  ['test_5frvv_5fvs_5fscalar_5fkernels_2ecpp_37',['test_rvv_vs_scalar_kernels.cpp',['../test__rvv__vs__scalar__kernels_8cpp.html',1,'']]],
  ['test_5fscalar_2ec_38',['test_scalar.c',['../test__scalar_8c.html',1,'']]],
  ['test_5fsor_2ecpp_39',['test_sor.cpp',['../test__sor_8cpp.html',1,'']]],
  ['test_5fsor_5fbottleneck_2ecpp_40',['test_sor_bottleneck.cpp',['../test__sor__bottleneck_8cpp.html',1,'']]],
  ['test_5fsor_5fradius_5fvalidation_2ecpp_41',['test_sor_radius_validation.cpp',['../test__sor__radius__validation_8cpp.html',1,'']]],
  ['test_5fsor_5fsearch_5fstrategies_2ecpp_42',['test_sor_search_strategies.cpp',['../test__sor__search__strategies_8cpp.html',1,'']]],
  ['test_5fsor_5fsqrt_5felimination_2ecpp_43',['test_sor_sqrt_elimination.cpp',['../test__sor__sqrt__elimination_8cpp.html',1,'']]],
  ['test_5fspatial_5fhash_5fcomparison_2ecpp_44',['test_spatial_hash_comparison.cpp',['../test__spatial__hash__comparison_8cpp.html',1,'']]],
  ['test_5ftuples_45',['test_tuples',['../test__tuples_8c.html#a731553bd209edadb53a76cafaaaaa5af',1,'test_tuples.c']]],
  ['test_5ftuples_2ec_46',['test_tuples.c',['../test__tuples_8c.html',1,'']]],
  ['test_5fvector_2ec_47',['test_vector.c',['../test__vector_8c.html',1,'']]],
  ['test_5fvoxel_5fgrid_2ecpp_48',['test_voxel_grid.cpp',['../test__voxel__grid_8cpp.html',1,'']]],
  ['test_5fvoxel_5frvv_20tt_20output_20filename_49',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['test_5fvoxel_5frvv_20tt_20the_20binary_20to_20execute_50',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['testing_51',['🏗️ Building &amp; Testing',['../index.html#️-building--testing',1,'']]],
  ['testing_20verification_52',['Testing &amp; Verification',['../instruction_manual.html#testing--verification',1,'']]],
  ['tests_53',['tests',['../index.html#running-individual-tests',1,'Running Individual Tests'],['../instruction_manual.html#running-tests',1,'Running Tests']]],
  ['the_204_20compilation_20stages_54',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['the_205_20core_20algorithms_55',['The 5 Core Algorithms',['../instruction_manual.html#the-5-core-algorithms',1,'']]],
  ['the_20benchmark_56',['Running the Benchmark',['../index.html#running-the-benchmark',1,'']]],
  ['the_20binary_20to_20execute_57',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['the_20bind_20mounted_20tt_20opt_20gem5_20tt_20binary_20—_20known_20limitation_58',['6b. The bind-mounted &lt;tt&gt;/opt/gem5&lt;/tt&gt; binary — known limitation',['../md_docs_2setup.html#autotoc_md6b-the-bind-mounted-optgem5-binary--known-limitation',1,'']]],
  ['the_20code_59',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['the_20code_20breakdown_60',['The Code Breakdown',['../vector_theory.html#the-code-breakdown',1,'']]],
  ['the_20command_61',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['the_20container_20activate_20the_20environment_62',['4. Enter the container / activate the environment',['../md_docs_2setup.html#autotoc_md4-enter-the-container--activate-the-environment',1,'']]],
  ['the_20dev_20container_63',['2. Create the dev container',['../md_docs_2setup.html#autotoc_md2-create-the-dev-container',1,'']]],
  ['the_20docker_20cli_20inside_20the_20container_64',['3. Install the Docker CLI inside the container',['../md_docs_2setup.html#autotoc_md3-install-the-docker-cli-inside-the-container',1,'']]],
  ['the_20emulator_65',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['the_20image_66',['1. Build the image',['../md_docs_2setup.html#autotoc_md1-build-the-image',1,'']]],
  ['the_20linux_20cross_20compiler_67',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['the_20memory_20latency_20wall_3a_68',['The Memory Latency Wall:',['../md_docs_2projection.html#the-memory-latency-wall',1,'']]],
  ['the_20problem_69',['the problem',['../md_docs_2INSTRUCTION__COUNTING.html#the-problem',1,'The Problem'],['../vector_theory.html#the-problem-1',1,'The Problem']]],
  ['the_20project_70',['7. Building and running the project',['../md_docs_2setup.html#autotoc_md7-building-and-running-the-project',1,'']]],
  ['the_20risc_20v_20qemu_20toolchain_71',['5. Verify the RISC-V + QEMU toolchain',['../md_docs_2setup.html#autotoc_md5-verify-the-risc-v--qemu-toolchain',1,'']]],
  ['the_20solution_3a_20trace_20based_20counting_72',['The Solution: Trace-Based Counting',['../md_docs_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['the_20solution_3a_20tt_20vluxei32_20tt_20indexed_20load_73',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['the_20tt_20manuel313_20gem5_5fv25_20tt_20docker_20image_20the_20wrapper_20script_20s_20approach_74',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['theory_75',['Vector Theory */',['../vector_theory.html',1,'']]],
  ['this_20board_76',['Why this board?',['../instruction_manual.html#why-this-board',1,'']]],
  ['this_20is_20better_77',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['this_20proves_20rvv_20efficiency_78',['Why This Proves RVV Efficiency',['../md_docs_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['tile_20aabb_79',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['tile_20aabb_20computation_80',['A. Query Tiling &amp; Tile AABB Computation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#a-query-tiling--tile-aabb-computation',1,'']]],
  ['tiling_20tile_20aabb_20computation_81',['A. Query Tiling &amp; Tile AABB Computation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#a-query-tiling--tile-aabb-computation',1,'']]],
  ['time_20rvv_20point_20cloud_20perception_20architecture_82',['Real-Time RVV Point Cloud Perception Architecture',['../md_docs_2projection.html',1,'']]],
  ['time_20toggle_20tt_20src_20include_20profiler_20h_20tt_83',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['timer_84',['Timer',['../classTimer.html',1,'']]],
  ['timing_20analysis_85',['Sub-Action Micro-Timing Analysis',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#sub-action-micro-timing-analysis',1,'']]],
  ['timing_20breakdown_86',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['timing_20matrix_87',['High-Level Stage Timing Matrix',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#high-level-stage-timing-matrix',1,'']]],
  ['tips_88',['Debugging Tips',['../instruction_manual.html#debugging-tips',1,'']]],
  ['to_2018_20542_24_89',['Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'']]],
  ['to_20execute_90',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['to_20function_20extend_20the_20code_91',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]],
  ['to_20run_92',['6. How to Run',['../md_docs_2projection.html#autotoc_md6-how-to-run',1,'']]],
  ['to_20tt_20pointeroctree_20tt_93',['4. API Extensions to &lt;tt&gt;PointerOctree&lt;/tt&gt;',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md4-api-extensions-to-pointeroctree',1,'']]],
  ['to_20use_94',['How to use',['../index.html#how-to-use',1,'']]],
  ['toggle_20tt_20src_20include_20profiler_20h_20tt_95',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['toolchain_96',['toolchain',['../index.html#autotoc_md-gcc-14-upgrade--linux-toolchain',1,'⚡ GCC 14 Upgrade &amp; Linux Toolchain'],['../md_docs_2setup.html#autotoc_md5-verify-the-risc-v--qemu-toolchain',1,'5. Verify the RISC-V + QEMU toolchain']]],
  ['toolchain_20path_97',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['topics_98',['Advanced Topics',['../instruction_manual.html#advanced-topics',1,'']]],
  ['trace_20based_20counting_99',['The Solution: Trace-Based Counting',['../md_docs_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['trace_20logging_20tt_20d_20exec_20nochain_20tt_100',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['translation_20strong_101',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['traversal_20with_20shared_20tile_20aabb_102',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['tree_20construction_20tt_20octree_3a_3abuild_20tt_103',['A. Spatial Tree Construction (&lt;tt&gt;Octree::build&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#a-spatial-tree-construction-octreebuild',1,'']]],
  ['true_20vlen_20128_20tt_20cpu_20configuration_104',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['tt_20_5f_5friscv_5fvcompress_5fvm_5ff32m8_20tt_105',['C. Hardware Vector Mask Compression (&lt;tt&gt;__riscv_vcompress_vm_f32m8&lt;/tt&gt;)',['../md_docs_2projection.html#c-hardware-vector-mask-compression-__riscv_vcompress_vm_f32m8',1,'']]],
  ['tt_20_5f_5friscv_5fvluxei32_5fv_5ff32m8_20tt_106',['B. Vector Indexed Gather (&lt;tt&gt;__riscv_vluxei32_v_f32m8&lt;/tt&gt;)',['../md_docs_2projection.html#b-vector-indexed-gather-__riscv_vluxei32_v_f32m8',1,'']]],
  ['tt_20cpu_20rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_107',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['tt_20d_20exec_20nochain_20tt_108',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['tt_20get_5fdist_5fsq_5frvv_20tt_109',['tt get_dist_sq_rvv tt',['../instruction_manual.html#get_dist_sq_rvv',1,'&lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;'],['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;']]],
  ['tt_20get_5finds_5fin_5fradius_5frvv_20tt_110',['&lt;tt&gt;get_inds_in_radius_rvv&lt;/tt&gt;',['../instruction_manual.html#get_inds_in_radius_rvv',1,'']]],
  ['tt_20i_20src_20include_20tt_20include_20directory_111',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['tt_20insertcloudrvv_20tt_112',['A. Vectorized 2D Coordinate Quantization (&lt;tt&gt;insertCloudRVV&lt;/tt&gt;)',['../md_docs_2projection.html#a-vectorized-2d-coordinate-quantization-insertcloudrvv',1,'']]],
  ['tt_20loadpcd_20file_5fpath_20points_5fvector_20tt_113',['&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'']]],
  ['tt_20mabi_20lp64d_20tt_20application_20binary_20interface_114',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['tt_20manuel313_20gem5_5fv25_20tt_20docker_20image_20the_20wrapper_20script_20s_20approach_115',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['tt_20march_20rv64gcv_20tt_20architecture_20specification_116',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['tt_20o_20test_5fvoxel_5frvv_20tt_20output_20filename_117',['6. &lt;tt&gt;-o test_voxel_rvv&lt;/tt&gt; - Output Filename',['../instruction_manual.html#autotoc_md6--o-test_voxel_rvv---output-filename',1,'']]],
  ['tt_20octree_20tt_20strong_118',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['tt_20octree_3a_3abuild_20tt_119',['A. Spatial Tree Construction (&lt;tt&gt;Octree::build&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#a-spatial-tree-construction-octreebuild',1,'']]],
  ['tt_20one_20insn_20per_20tb_20tt_120',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['tt_20opt_20gem5_20tt_20binary_20—_20known_20limitation_121',['6b. The bind-mounted &lt;tt&gt;/opt/gem5&lt;/tt&gt; binary — known limitation',['../md_docs_2setup.html#autotoc_md6b-the-bind-mounted-optgem5-binary--known-limitation',1,'']]],
  ['tt_20pipeline_5fexport_20tt_20capped_20at_201_206×_20speedup_122',['2. Why &lt;tt&gt;pipeline_export&lt;/tt&gt; Capped at ~1.6× Speedup',['../md_docs_2projection.html#autotoc_md2-why-pipeline_export-capped-at-16-speedup',1,'']]],
  ['tt_20pipeline_5ffast_5fexport_20tt_20vs_20tt_20pipeline_5frvv_5fultra_5ffast_20tt_123',['5. Architectural Comparison: &lt;tt&gt;pipeline_fast_export&lt;/tt&gt; vs &lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;',['../md_docs_2projection.html#autotoc_md5-architectural-comparison-pipeline_fast_export-vs-pipeline_rvv_ultra_fast',1,'']]],
  ['tt_20pipeline_5frvv_5fultra_5ffast_20tt_124',['4. Hardware RVV 1.0 Vectorization (&lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;)',['../md_docs_2projection.html#autotoc_md4-hardware-rvv-10-vectorization-pipeline_rvv_ultra_fast',1,'']]],
  ['tt_20pointeroctree_20tt_125',['4. API Extensions to &lt;tt&gt;PointerOctree&lt;/tt&gt;',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md4-api-extensions-to-pointeroctree',1,'']]],
  ['tt_20qemu_20riscv64_20tt_20the_20emulator_126',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['tt_20riscv64_20linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_127',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['tt_20savepcd_20file_5fpath_20points_5fvector_20tt_128',['&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#savepcdfile_path-points_vector',1,'']]],
  ['tt_20scripts_20profile_5fpipeline_20py_20tt_129',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]],
  ['tt_20spatialhash_20tt_20strong_130',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['tt_20src_20include_20profiler_20h_20tt_131',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['tt_20struct_20pointcloudsoa_20tt_132',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['tt_20struct_20pointxyz_20tt_133',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['tt_20test_5fvoxel_5frvv_20tt_20the_20binary_20to_20execute_134',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['tt_20vluxei32_20tt_20indexed_20load_135',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['tt_20vsetvl_20tt_20vector_20set_20vector_20length_136',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['tuning_137',['Performance Tuning',['../instruction_manual.html#performance-tuning',1,'']]],
  ['two_20phase_20workflow_20tt_20scripts_20profile_5fpipeline_20py_20tt_138',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]],
  ['types_139',['types',['../structrvv__pcl_1_1detail_1_1PCDHeader.html#a98f31d73e0e4684d7fc5b3827fde3f2c',1,'rvv_pcl::detail::PCDHeader']]]
];
