var searchData=
[
  ['1️⃣_20tt_20qemu_20riscv64_20tt_20the_20emulator_0',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['1_200_20features_1',['RVV 1.0 Features',['../instruction_manual.html#rvv-10-features',1,'']]],
  ['1_200_20vectorization_20tt_20pipeline_5frvv_5fultra_5ffast_20tt_2',['4. Hardware RVV 1.0 Vectorization (&lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;)',['../md_docs_2projection.html#autotoc_md4-hardware-rvv-10-vectorization-pipeline_rvv_ultra_fast',1,'']]],
  ['1_206×_20speedup_3',['2. Why &lt;tt&gt;pipeline_export&lt;/tt&gt; Capped at ~1.6× Speedup',['../md_docs_2projection.html#autotoc_md2-why-pipeline_export-capped-at-16-speedup',1,'']]],
  ['1_20build_20the_20image_4',['1. Build the image',['../md_docs_2setup.html#autotoc_md1-build-the-image',1,'']]],
  ['1_20executive_20summary_5',['1. Executive Summary',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md1-executive-summary',1,'']]],
  ['1_20executive_20summary_20benchmark_20evolution_6',['1. Executive Summary &amp; Benchmark Evolution',['../md_docs_2projection.html#autotoc_md1-executive-summary--benchmark-evolution',1,'']]],
  ['1_20executive_20summary_20problem_20statement_7',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['1_20overview_20objectives_8',['1. Overview &amp; Objectives',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md1-overview--objectives',1,'']]],
  ['1_20pipeline_20profiling_20matrix_9',['2. Phase 1 Pipeline Profiling Matrix',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md2-phase-1-pipeline-profiling-matrix',1,'']]],
  ['1_20run_20hardware_20accelerated_20rvv_20ultra_20fast_20pipeline_3a_10',['1. Run Hardware-Accelerated RVV Ultra-Fast Pipeline:',['../md_docs_2projection.html#autotoc_md1-run-hardware-accelerated-rvv-ultra-fast-pipeline',1,'']]],
  ['1_20standardized_20development_20workflow_11',['1. Standardized Development Workflow',['../instruction_manual.html#autotoc_md1-standardized-development-workflow',1,'']]],
  ['1_20strip_20mining_20pattern_12',['1. Strip Mining Pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'']]],
  ['1_20tt_20one_20insn_20per_20tb_20tt_13',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['1_20tt_20riscv64_20linux_20gnu_20g_20tt_20the_20linux_20cross_20compiler_14',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['1_20tt_20vsetvl_20tt_20vector_20set_20vector_20length_15',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['114_20278_20to_2018_20542_24_16',['Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'']]],
  ['128_20tt_20cpu_20configuration_17',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['14_20strong_18',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['14_20upgrade_20linux_20toolchain_19',['⚡ GCC 14 Upgrade &amp; Linux Toolchain',['../index.html#autotoc_md-gcc-14-upgrade--linux-toolchain',1,'']]],
  ['18_20542_24_20',['18 542$',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'Ablation B: Spatial Neighbor Search Methods ($N=18,542$)'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)']]],
  ['1_3a_20illegal_20instruction_21',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['1_3a_20initialization_20strong_22',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['1_3a_20pipeline_20stage_20sub_20stage_20micro_20timing_20breakdown_23',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['1_3a_20preprocessing_24',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]]
];
