var searchData=
[
  ['b_20running_20with_20system_20libraries_20strong_0',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['banana_20pi_20bpi_20f3_1',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['bare_20metal_2',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['based_20counting_3',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['baseline_20subtraction_4',['3. Baseline Subtraction',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md3-baseline-subtraction',1,'']]],
  ['basic_20compilation_20command_20linux_20target_5',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['bench_5fnormal_6',['bench_normal',['../benchmark_8cpp.html#a2f0f03be552275d6d7a75510161c19e6',1,'benchmark.cpp']]],
  ['bench_5fradius_7',['bench_radius',['../benchmark_8cpp.html#a77550c19237153748f4c4bd35887fa12',1,'benchmark.cpp']]],
  ['bench_5fransac_8',['bench_ransac',['../benchmark_8cpp.html#aca389cd56155161401a97f0197e42d49',1,'benchmark.cpp']]],
  ['bench_5fsor_9',['bench_sor',['../benchmark_8cpp.html#a1ead7cc5a41d415b081b5f7fc439f6fb',1,'benchmark.cpp']]],
  ['bench_5fvoxel_10',['bench_voxel',['../benchmark_8cpp.html#ab82b6bf3017a9ccef0988e8671004580',1,'benchmark.cpp']]],
  ['bench_5fvoxel_5fv2_11',['bench_voxel_v2',['../benchmark_8cpp.html#ad32795d49e2d54728dbbd509e0b5e18f',1,'benchmark.cpp']]],
  ['benchmark_12',['Running the Benchmark',['../index.html#running-the-benchmark',1,'']]],
  ['benchmark_20verification_3a_20instruction_20counts_13',['Benchmark Verification: Instruction Counts',['../md_results_2benchmark__summary__report.html',1,'']]],
  ['benchmark_2ecpp_14',['benchmark.cpp',['../benchmark_8cpp.html',1,'']]],
  ['benchmark_5fsummary_5freport_2emd_15',['benchmark_summary_report.md',['../benchmark__summary__report_8md.html',1,'']]],
  ['benchmarkdata_16',['BenchmarkData',['../structBenchmarkData.html',1,'']]],
  ['benchmarking_17',['benchmarking',['../index.html#autotoc_md-benchmarking',1,'📊 Benchmarking'],['../instruction_manual.html#benchmarking',1,'Benchmarking']]],
  ['benchmarks_20large_20scale_18',['🚀 Advanced Benchmarks (Large-Scale)',['../md_results_2benchmark__summary__report.html#autotoc_md-advanced-benchmarks-large-scale',1,'']]],
  ['better_19',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['binary_20file_20',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['binary_20interface_21',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['binary_20to_20execute_22',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['blockquote_23',['&lt;/blockquote&gt;',['../instruction_manual.html#blockquote',1,'']]],
  ['board_24',['Why this board?',['../instruction_manual.html#why-this-board',1,'']]],
  ['boolean_20vectors_25',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['boxoverlapssphere_26',['boxOverlapsSphere',['../namespacervv__pcl.html#af7c99d4213ef677500481fe22652bdeb',1,'rvv_pcl']]],
  ['bpi_20f3_27',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['branch_3a_20arian_5fexps_28',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['breakdown_29',['breakdown',['../instruction_manual.html#command-breakdown',1,'Command Breakdown'],['../instruction_manual.html#qemu-execution-command-breakdown',1,'QEMU Execution Command Breakdown'],['../instruction_manual.html#summary-qemu-command-breakdown',1,'Summary: QEMU Command Breakdown'],['../vector_theory.html#the-code-breakdown',1,'The Code Breakdown']]],
  ['build_30',['build',['../pipeline_demo.html#autotoc_md1-build',1,'1. Build'],['../classrvv__pcl_1_1SpatialHash.html#aeef3a803a087f37383705892c628d07c',1,'rvv_pcl::SpatialHash::build()'],['../classrvv__pcl_1_1Octree.html#ac111c28a7fbad65e5a2e614677b28781',1,'rvv_pcl::Octree::build()'],['../index.html#manual-build',1,'Manual Build']]],
  ['build_20targeting_20gcc_2014_20strong_31',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['build_5fepsilon_5f_32',['build_epsilon_',['../classrvv__pcl_1_1Octree.html#ace0933d9bb09408d94c589932b657042',1,'rvv_pcl::Octree']]],
  ['building_20for_20linux_33',['Building for Linux',['../index.html#building-for-linux',1,'']]],
  ['building_20testing_34',['🏗️ Building &amp; Testing',['../index.html#️-building--testing',1,'']]],
  ['buildparams_35',['buildParams',['../classrvv__pcl_1_1Octree.html#a25d4fb900fb2285313c9be32c8035134',1,'rvv_pcl::Octree']]],
  ['by_20step_20execution_3a_20voxel_20grid_20test_36',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]]
];
