var searchData=
[
  ['v_20true_20vlen_20128_20tt_20cpu_20configuration_0',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['v_20vector_20optimized_20point_20cloud_20library_1',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['v_20vector_20rvv_20implementation_20guide_2',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['vector_20code_3',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['vector_20execution_20⚡_4',['RVV Vector Execution ⚡',['../instruction_manual.html#rvv-vector-execution-',1,'']]],
  ['vector_20instruction_20emulation_20strong_5',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['vector_20intrinsics_20naming_20guide_6',['3. Vector Intrinsics Naming Guide',['../instruction_manual.html#autotoc_md3-vector-intrinsics-naming-guide',1,'']]],
  ['vector_20masks_20boolean_20vectors_7',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['vector_20optimized_20point_20cloud_20library_8',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['vector_20rvv_20implementation_20guide_9',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['vector_20set_20vector_20length_10',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['vector_20theory_11',['Vector Theory */',['../vector_theory.html',1,'']]],
  ['vector_5fadd_12',['vector_add',['../test__autovec_8c.html#aaee0dc237f945ad81e6e5fc2410d0035',1,'test_autovec.c']]],
  ['vector_5foperations_5fexplained_13',['vector_operations_explained',['../vector_operations_explained.html',1,'']]],
  ['vector_5foperations_5fexplained_2emd_14',['vector_operations_explained.md',['../vector__operations__explained_8md.html',1,'']]],
  ['vectors_15',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['verification_16',['verification',['../index.html#run-full-verification',1,'Run Full Verification'],['../instruction_manual.html#testing--verification',1,'Testing &amp; Verification']]],
  ['verification_20steps_20manual_17',['Detailed Verification Steps (Manual)',['../index.html#detailed-verification-steps-manual',1,'']]],
  ['verification_3a_20instruction_20counts_18',['Benchmark Verification: Instruction Counts',['../md_results_2benchmark__summary__report.html',1,'']]],
  ['verify_20without_20cmake_20manual_20compilation_19',['Verify without CMake (Manual Compilation)',['../index.html#verify-without-cmake-manual-compilation',1,'']]],
  ['visualize_20',['visualize',['../namespacevisualize__result.html#a4f38314714fef01bfcacc7b2770dd038',1,'visualize_result']]],
  ['visualize_5fresult_21',['visualize_result',['../namespacevisualize__result.html',1,'']]],
  ['visualize_5fresult_2epy_22',['visualize_result.py',['../visualize__result_8py.html',1,'']]],
  ['vlen_20128_20tt_20cpu_20configuration_23',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['vluxei32_20tt_20indexed_20load_24',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['voxel_20grid_20downsampling_20strong_25',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['voxel_20grid_20test_26',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['voxel_5fgrid_5fdownsamp_2ecpp_27',['voxel_grid_downsamp.cpp',['../voxel__grid__downsamp_8cpp.html',1,'']]],
  ['voxel_5fgrid_5fdownsamp_5frvv_28',['voxel_grid_downsamp_rvv',['../namespacervv__pcl.html#aeb6d0889fa7a2d26d799e33858c4997a',1,'rvv_pcl']]],
  ['voxel_5fgrid_5fdownsamp_5frvv_5fv2_29',['voxel_grid_downsamp_rvv_v2',['../namespacervv__pcl.html#a4704468dd499c2107740037f835751cc',1,'rvv_pcl']]],
  ['voxel_5fgrid_5fdownsamp_5fsc_30',['voxel_grid_downsamp_sc',['../namespacervv__pcl.html#a4ba723f597780e83a18f39b9bd31e8ac',1,'rvv_pcl']]],
  ['vs_20bare_20metal_31',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['vs_20real_20hardware_32',['QEMU vs Real Hardware',['../instruction_manual.html#qemu-vs-real-hardware',1,'']]],
  ['vsetvl_20tt_20vector_20set_20vector_20length_33',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]]
];
