var searchData=
[
  ['calculation_0',['Distance Calculation',['../instruction_manual.html#distance-calculation',1,'']]],
  ['call_20translation_20strong_1',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['cannot_20execute_20binary_20file_2',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['cd_20pipeline_3',['🤖 CI/CD Pipeline',['../index.html#autotoc_md-cicd-pipeline',1,'']]],
  ['cell_5fsize_5f_4',['cell_size_',['../classrvv__pcl_1_1SpatialHash.html#ae04eeccbfb840ae62458138d8f2db005',1,'rvv_pcl::SpatialHash']]],
  ['check_5frvv_5ffeatures_5',['check_rvv_features',['../test__rvv__features_8c.html#a699ce3eaaa120d787df2775c49c55826',1,'test_rvv_features.c']]],
  ['children_6',['children',['../structrvv__pcl_1_1OctreeNode.html#a68e0907cabe2b57aa877bfe61ce8899b',1,'rvv_pcl::OctreeNode']]],
  ['ci_20cd_20pipeline_7',['🤖 CI/CD Pipeline',['../index.html#autotoc_md-cicd-pipeline',1,'']]],
  ['class_20tt_20octree_20tt_20strong_8',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['class_20tt_20spatialhash_20tt_20strong_9',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['clean_20build_20targeting_20gcc_2014_20strong_10',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['cloud_20library_11',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['cloud_20pipeline_20demo_20branch_3a_20arian_5fexps_12',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['cloud_5f_13',['cloud_',['../classrvv__pcl_1_1Octree.html#a350aeea9e39f10699be47f496faa537f',1,'rvv_pcl::Octree::cloud_'],['../classrvv__pcl_1_1SpatialHash.html#aa0014a79604f78c69f5c02fba42c006d',1,'rvv_pcl::SpatialHash::cloud_']]],
  ['cmake_20manual_20compilation_14',['Verify without CMake (Manual Compilation)',['../index.html#verify-without-cmake-manual-compilation',1,'']]],
  ['code_15',['code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'2. How to Function &amp; Extend the Code'],['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'Array of Structures (AoS) - Scalar Code'],['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'Structure of Arrays (SoA) - Vector Code']]],
  ['code_20breakdown_16',['The Code Breakdown',['../vector_theory.html#the-code-breakdown',1,'']]],
  ['codebase_20architecture_17',['Codebase Architecture',['../instruction_manual.html#codebase-architecture',1,'']]],
  ['command_18',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['command_20breakdown_19',['command breakdown',['../instruction_manual.html#command-breakdown',1,'Command Breakdown'],['../instruction_manual.html#qemu-execution-command-breakdown',1,'QEMU Execution Command Breakdown'],['../instruction_manual.html#summary-qemu-command-breakdown',1,'Summary: QEMU Command Breakdown']]],
  ['command_20linux_20target_20',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['command_20not_20found_21',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['commands_22',['commands',['../instruction_manual.html#compilation-commands',1,'Compilation Commands'],['../instruction_manual.html#execution-commands',1,'Execution Commands']]],
  ['common_20intrinsics_23',['Common Intrinsics',['../instruction_manual.html#common-intrinsics',1,'']]],
  ['common_20qemu_20errors_20solutions_24',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['common_20rvv_20patterns_25',['Common RVV Patterns',['../instruction_manual.html#common-rvv-patterns',1,'']]],
  ['compilation_26',['compilation',['../instruction_manual.html#stage-2-compilation',1,'Stage 2: Compilation'],['../index.html#verify-without-cmake-manual-compilation',1,'Verify without CMake (Manual Compilation)']]],
  ['compilation_20command_20linux_20target_27',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['compilation_20commands_28',['Compilation Commands',['../instruction_manual.html#compilation-commands',1,'']]],
  ['compilation_20deep_20dive_29',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['compilation_20output_30',['Inspecting Compilation Output',['../instruction_manual.html#inspecting-compilation-output',1,'']]],
  ['compilation_20stages_31',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['compiler_32',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['compiler_20selection_3a_20linux_20vs_20bare_20metal_33',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['complete_20example_3a_20what_20happens_20when_20you_20run_20the_20command_34',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['complete_20flow_35',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['component_20structure_36',['Component Structure',['../instruction_manual.html#component-structure',1,'']]],
  ['compute_5fcovariance_5frvv_37',['compute_covariance_rvv',['../namespacervv__pcl.html#a7579c4594b9c3142399c0ebc4818d8b0',1,'rvv_pcl']]],
  ['concepts_38',['concepts',['../vector_theory.html#key-rvv-concepts',1,'Key RVV Concepts'],['../instruction_manual.html#rvv-programming-concepts',1,'RVV Programming Concepts']]],
  ['configuration_39',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['configuration_20options_20summary_40',['Configuration Options Summary',['../instruction_manual.html#configuration-options-summary',1,'']]],
  ['contents_41',['Table of Contents',['../instruction_manual.html#table-of-contents',1,'']]],
  ['convention_42',['3. Intrinsics Naming Convention',['../vector_theory.html#autotoc_md3-intrinsics-naming-convention',1,'']]],
  ['core_20algorithms_43',['core algorithms',['../instruction_manual.html#core-algorithms',1,'Core Algorithms'],['../instruction_manual.html#the-5-core-algorithms',1,'The 5 Core Algorithms']]],
  ['core_20logic_3a_20tt_20get_5fdist_5fsq_5frvv_20tt_44',['Core Logic: &lt;tt&gt;get_dist_sq_rvv&lt;/tt&gt;',['../vector_theory.html#core-logic-get_dist_sq_rvv',1,'']]],
  ['counting_45',['The Solution: Trace-Based Counting',['../md_tests_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['counting_20methodology_46',['Instruction Counting Methodology',['../md_tests_2INSTRUCTION__COUNTING.html',1,'']]],
  ['cpu_20configuration_47',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['cpu_20rv64_20v_20true_20vlen_20128_20tt_20cpu_20configuration_48',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['create_20soa_20structure_49',['Create SoA Structure',['../instruction_manual.html#create-soa-structure',1,'']]],
  ['cross_20compiler_50',['1. &lt;tt&gt;riscv64-linux-gnu-g++&lt;/tt&gt; - The Linux Cross-Compiler',['../instruction_manual.html#autotoc_md1-riscv64-linux-gnu-g---the-linux-cross-compiler',1,'']]],
  ['custom_20toolchain_20path_51',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]]
];
