var searchData=
[
  ['p1_5f_0',['p1_',['../classrvv__pcl_1_1SpatialHash.html#a3c5615bb17999c2fa30b887190867534',1,'rvv_pcl::SpatialHash']]],
  ['p2_5f_1',['p2_',['../classrvv__pcl_1_1SpatialHash.html#a372dc70b3bcbfb9913cd8dde3a5190b8',1,'rvv_pcl::SpatialHash']]],
  ['path_2',['Custom Toolchain Path',['../index.html#custom-toolchain-path',1,'']]],
  ['pattern_3',['pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'1. Strip Mining Pattern'],['../instruction_manual.html#test-pattern',1,'Test Pattern']]],
  ['patterns_4',['Common RVV Patterns',['../instruction_manual.html#common-rvv-patterns',1,'']]],
  ['per_20tb_20tt_5',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['performance_20summary_20table_6',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['performance_20tuning_7',['Performance Tuning',['../instruction_manual.html#performance-tuning',1,'']]],
  ['phase_201_3a_20initialization_20strong_8',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['phase_202_3a_20instruction_20execution_20loop_20strong_9',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['phase_203_3a_20system_20call_20translation_20strong_10',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['phase_204_3a_20vector_20instruction_20emulation_20strong_11',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['pi_20bpi_20f3_12',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['pipeline_13',['pipeline',['../index.html#autotoc_md-cicd-pipeline',1,'🤖 CI/CD Pipeline'],['../pipeline_demo.html#autotoc_md2-run-pipeline',1,'2. Run Pipeline']]],
  ['pipeline_20demo_14',['Pipeline Demo */',['../pipeline_demo.html',1,'']]],
  ['pipeline_20demo_20branch_3a_20arian_5fexps_15',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['plane_20fitting_20strong_16',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['point_20cloud_20library_17',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['point_20cloud_20pipeline_20demo_20branch_3a_20arian_5fexps_18',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['pointcloudsoa_19',['PointCloudSoA',['../structrvv__pcl_1_1PointCloudSoA.html',1,'rvv_pcl']]],
  ['pointcloudsoa_20tt_20',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['points_5fvector_20tt_21',['points_vector tt',['../instruction_manual.html#loadpcdfile_path-points_vector',1,'&lt;tt&gt;loadPCD(file_path, points_vector)&lt;/tt&gt;'],['../instruction_manual.html#savepcdfile_path-points_vector',1,'&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;']]],
  ['pointxyz_22',['PointXYZ',['../structrvv__pcl_1_1PointXYZ.html',1,'rvv_pcl']]],
  ['pointxyz_20tt_23',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['preprocessing_24',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]],
  ['prerequisites_25',['prerequisites',['../index.html#prerequisites',1,'Prerequisites'],['../pipeline_demo.html#prerequisites-1',1,'Prerequisites']]],
  ['problem_26',['problem',['../vector_theory.html#the-problem',1,'The Problem'],['../md_tests_2INSTRUCTION__COUNTING.html#the-problem-1',1,'The Problem']]],
  ['program_20start_27',['Program Start',['../instruction_manual.html#program-start',1,'']]],
  ['programming_20concepts_28',['RVV Programming Concepts',['../instruction_manual.html#rvv-programming-concepts',1,'']]],
  ['project_20navigation_29',['project navigation',['../vector_theory.html#️-project-navigation-1',1,'🗺️ Project Navigation'],['../md_tests_2INSTRUCTION__COUNTING.html#️-project-navigation-2',1,'🗺️ Project Navigation'],['../instruction_manual.html#️-project-navigation',1,'🗺️ Project Navigation']]],
  ['project_20structure_30',['project structure',['../index.html#autotoc_md-project-structure',1,'📂 Project Structure'],['../pipeline_demo.html#project-structure',1,'Project Structure']]],
  ['proves_20rvv_20efficiency_31',['Why This Proves RVV Efficiency',['../md_tests_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]]
];
