var searchData=
[
  ['v_20qemu_20toolchain_0',['5. Verify the RISC-V + QEMU toolchain',['../md_docs_2setup.html#autotoc_md5-verify-the-risc-v--qemu-toolchain',1,'']]],
  ['v_20true_20vlen_20128_20tt_20cpu_20configuration_1',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['v_20vector_20optimized_20point_20cloud_20library_2',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['v_20vector_20rvv_20implementation_20guide_3',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['variants_204_20caravan_20strategies_20_24n_2018_20542_24_4',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['vector_20code_5',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['vector_20execution_20⚡_6',['RVV Vector Execution ⚡',['../instruction_manual.html#rvv-vector-execution-',1,'']]],
  ['vector_20indexed_20gather_20tt_20_5f_5friscv_5fvluxei32_5fv_5ff32m8_20tt_7',['B. Vector Indexed Gather (&lt;tt&gt;__riscv_vluxei32_v_f32m8&lt;/tt&gt;)',['../md_docs_2projection.html#b-vector-indexed-gather-__riscv_vluxei32_v_f32m8',1,'']]],
  ['vector_20instruction_20emulation_20strong_8',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['vector_20intrinsics_20naming_20guide_9',['3. Vector Intrinsics Naming Guide',['../instruction_manual.html#autotoc_md3-vector-intrinsics-naming-guide',1,'']]],
  ['vector_20kernel_10',['C. Caravan Leaf Vector Kernel',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#c-caravan-leaf-vector-kernel',1,'']]],
  ['vector_20mask_20compression_20tt_20_5f_5friscv_5fvcompress_5fvm_5ff32m8_20tt_11',['C. Hardware Vector Mask Compression (&lt;tt&gt;__riscv_vcompress_vm_f32m8&lt;/tt&gt;)',['../md_docs_2projection.html#c-hardware-vector-mask-compression-__riscv_vcompress_vm_f32m8',1,'']]],
  ['vector_20masks_20boolean_20vectors_12',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['vector_20mechanics_13',['2. Architectural Design &amp; Vector Mechanics',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md2-architectural-design--vector-mechanics',1,'']]],
  ['vector_20optimized_20point_20cloud_20library_14',['RVPoint: RISC-V Vector Optimized Point Cloud Library',['../index.html',1,'']]],
  ['vector_20rvv_20implementation_20guide_15',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['vector_20set_20vector_20length_16',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['vector_20theory_17',['Vector Theory */',['../vector_theory.html',1,'']]],
  ['vector_5foperations_5fexplained_18',['vector_operations_explained',['../vector_operations_explained.html',1,'']]],
  ['vector_5foperations_5fexplained_2emd_19',['vector_operations_explained.md',['../vector__operations__explained_8md.html',1,'']]],
  ['vectorization_20tt_20pipeline_5frvv_5fultra_5ffast_20tt_20',['4. Hardware RVV 1.0 Vectorization (&lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;)',['../md_docs_2projection.html#autotoc_md4-hardware-rvv-10-vectorization-pipeline_rvv_ultra_fast',1,'']]],
  ['vectorized_202d_20coordinate_20quantization_20tt_20insertcloudrvv_20tt_21',['A. Vectorized 2D Coordinate Quantization (&lt;tt&gt;insertCloudRVV&lt;/tt&gt;)',['../md_docs_2projection.html#a-vectorized-2d-coordinate-quantization-insertcloudrvv',1,'']]],
  ['vectors_22',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['verification_23',['verification',['../md_docs_2setup.html#autotoc_md6-gem5-setup-and-verification',1,'6. gem5 setup and verification'],['../index.html#run-full-verification',1,'Run Full Verification'],['../instruction_manual.html#testing--verification',1,'Testing &amp; Verification']]],
  ['verification_20steps_20manual_24',['Detailed Verification Steps (Manual)',['../index.html#detailed-verification-steps-manual',1,'']]],
  ['verify_20the_20risc_20v_20qemu_20toolchain_25',['5. Verify the RISC-V + QEMU toolchain',['../md_docs_2setup.html#autotoc_md5-verify-the-risc-v--qemu-toolchain',1,'']]],
  ['verify_20without_20cmake_20manual_20compilation_26',['Verify without CMake (Manual Compilation)',['../index.html#verify-without-cmake-manual-compilation',1,'']]],
  ['via_20the_20tt_20manuel313_20gem5_5fv25_20tt_20docker_20image_20the_20wrapper_20script_20s_20approach_27',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['vlen_20128_20tt_20cpu_20configuration_28',['2️⃣ &lt;tt&gt;-cpu rv64,v=true,vlen=128&lt;/tt&gt; - CPU Configuration',['../instruction_manual.html#autotoc_md2️⃣--cpu-rv64vtruevlen128---cpu-configuration',1,'']]],
  ['vluxei32_20tt_20indexed_20load_29',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['voxel_20grid_20downsampling_30',['Ablation A: Voxel Grid Downsampling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-a-voxel-grid-downsampling',1,'']]],
  ['voxel_20grid_20downsampling_20_24n_20114_20278_20to_2018_20542_24_31',['Ablation A: Voxel Grid Downsampling ($N=114,278 \to 18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-a-voxel-grid-downsampling-n114278-to-18542',1,'']]],
  ['voxel_20grid_20downsampling_20strong_32',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['voxel_20grid_20test_33',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['voxel_5fgrid_5fdownsamp_2ecpp_34',['voxel_grid_downsamp.cpp',['../voxel__grid__downsamp_8cpp.html',1,'']]],
  ['voxel_5fgrid_5fdownsamp_5frvv_35',['voxel_grid_downsamp_rvv',['../namespacervv__pcl.html#aeb6d0889fa7a2d26d799e33858c4997a',1,'rvv_pcl']]],
  ['voxel_5fgrid_5fdownsamp_5frvv_5fv2_36',['voxel_grid_downsamp_rvv_v2',['../namespacervv__pcl.html#a4704468dd499c2107740037f835751cc',1,'rvv_pcl']]],
  ['voxel_5fgrid_5fdownsamp_5fsc_37',['voxel_grid_downsamp_sc',['../namespacervv__pcl.html#a4ba723f597780e83a18f39b9bd31e8ac',1,'rvv_pcl']]],
  ['voxel_5fto_5fend_38',['voxel_to_end',['../test__rvpoint__3d__turbo__bench_8cpp.html#a0210f016895adb6a2d607358c251d37c',1,'test_rvpoint_3d_turbo_bench.cpp']]],
  ['voxeldownsample_39',['voxelDownsample',['../test__rvpoint__3d__turbo__bench_8cpp.html#a91a94038a192d8692700a7d4b0ed3e99',1,'test_rvpoint_3d_turbo_bench.cpp']]],
  ['voxelhash3d_40',['VoxelHash3D',['../structVoxelHash3D.html',1,'']]],
  ['voxelhashfunc_41',['VoxelHashFunc',['../structVoxelHashFunc.html',1,'']]],
  ['vs_20bare_20metal_42',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['vs_20real_20hardware_43',['QEMU vs Real Hardware',['../instruction_manual.html#qemu-vs-real-hardware',1,'']]],
  ['vs_20tt_20pipeline_5frvv_5fultra_5ffast_20tt_44',['5. Architectural Comparison: &lt;tt&gt;pipeline_fast_export&lt;/tt&gt; vs &lt;tt&gt;pipeline_rvv_ultra_fast&lt;/tt&gt;',['../md_docs_2projection.html#autotoc_md5-architectural-comparison-pipeline_fast_export-vs-pipeline_rvv_ultra_fast',1,'']]],
  ['vsetvl_20tt_20vector_20set_20vector_20length_45',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]]
];
