var searchData=
[
  ['b_0',['b',['../structPlane3D.html#a887c467c5e8b9329c9e2cb026bcc0869',1,'Plane3D::b'],['../structrvpoint_1_1PointXYZRGB.html#a7ff4348124e9f44173978ffc5c3beb18',1,'rvpoint::PointXYZRGB::b']]],
  ['b_20eliminating_20_2450_20000_24_20matrix_20eigen_20decompositions_1',['B. Eliminating $50,000$ Matrix Eigen-Decompositions',['../md_docs_2projection.html#b-eliminating-50000-matrix-eigen-decompositions',1,'']]],
  ['b_20octree_20traversal_20with_20shared_20tile_20aabb_2',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['b_20ransac_20sub_20actions_20stage_208_3',['B. RANSAC Sub-Actions (Stage 8)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#b-ransac-sub-actions-stage-8',1,'']]],
  ['b_20running_20with_20system_20libraries_20strong_4',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['b_20vector_20indexed_20gather_20tt_20_5f_5friscv_5fvluxei32_5fv_5ff32m8_20tt_5',['B. Vector Indexed Gather (&lt;tt&gt;__riscv_vluxei32_v_f32m8&lt;/tt&gt;)',['../md_docs_2projection.html#b-vector-indexed-gather-__riscv_vluxei32_v_f32m8',1,'']]],
  ['b_3a_20spatial_20neighbor_20search_6',['Ablation B: Spatial Neighbor Search',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-b-spatial-neighbor-search',1,'']]],
  ['b_3a_20spatial_20neighbor_20search_20methods_20_24n_2018_20542_24_7',['Ablation B: Spatial Neighbor Search Methods ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'']]],
  ['banana_20pi_20bpi_20f3_8',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['bare_20metal_9',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['based_20counting_10',['The Solution: Trace-Based Counting',['../md_docs_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['baseline_20subtraction_11',['3. Baseline Subtraction',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md3-baseline-subtraction',1,'']]],
  ['basic_20compilation_20command_20linux_20target_12',['Basic Compilation Command (Linux Target)',['../instruction_manual.html#basic-compilation-command-linux-target',1,'']]],
  ['batchradiussearch_13',['batchradiussearch',['../classrvpoint_1_1CaravanPointerOctree.html#ae94d47d484684743af3450ec35a86c8c',1,'rvpoint::CaravanPointerOctree::batchRadiusSearch()'],['../classrvpoint_1_1CaravanRadiusSearch.html#a4e3328565a3def6567b042b575bb2995',1,'rvpoint::CaravanRadiusSearch::batchRadiusSearch()']]],
  ['bench_5fcaravan_5fradius_2ecpp_14',['bench_caravan_radius.cpp',['../bench__caravan__radius_8cpp.html',1,'']]],
  ['bench_5fnormal_5fpcd_2ecpp_15',['bench_normal_pcd.cpp',['../bench__normal__pcd_8cpp.html',1,'']]],
  ['bench_5foctree_5fradius_2ecpp_16',['bench_octree_radius.cpp',['../bench__octree__radius_8cpp.html',1,'']]],
  ['bench_5fparams_2eh_17',['bench_params.h',['../bench__params_8h.html',1,'']]],
  ['bench_5fscalar_5fradius_2ecpp_18',['bench_scalar_radius.cpp',['../bench__scalar__radius_8cpp.html',1,'']]],
  ['bench_5fsor_5fpcd_2ecpp_19',['bench_sor_pcd.cpp',['../bench__sor__pcd_8cpp.html',1,'']]],
  ['benchmark_20',['Running the Benchmark',['../index.html#running-the-benchmark',1,'']]],
  ['benchmark_20evolution_21',['1. Executive Summary &amp; Benchmark Evolution',['../md_docs_2projection.html#autotoc_md1-executive-summary--benchmark-evolution',1,'']]],
  ['benchmark_2ecpp_22',['benchmark.cpp',['../benchmark_8cpp.html',1,'']]],
  ['benchmark_5fkernels_2ecpp_23',['benchmark_kernels.cpp',['../benchmark__kernels_8cpp.html',1,'']]],
  ['benchmark_5fkernels_2eh_24',['benchmark_kernels.h',['../benchmark__kernels_8h.html',1,'']]],
  ['benchmark_5fpointer_5foctree_5freal_2ecpp_25',['benchmark_pointer_octree_real.cpp',['../benchmark__pointer__octree__real_8cpp.html',1,'']]],
  ['benchmarkcloudholder_26',['BenchmarkCloudHolder',['../structrvpoint_1_1bench_1_1BenchmarkCloudHolder.html',1,'rvpoint::bench']]],
  ['benchmarkfusedrvv_27',['benchmarkfusedrvv',['../classBenchmarkFusedRVV.html',1,'BenchmarkFusedRVV'],['../classBenchmarkFusedRVV.html#a70ab2403becfe40cdac6008f23bb8e60',1,'BenchmarkFusedRVV::BenchmarkFusedRVV()']]],
  ['benchmarking_28',['benchmarking',['../index.html#autotoc_md-benchmarking',1,'📊 Benchmarking'],['../instruction_manual.html#benchmarking',1,'Benchmarking']]],
  ['benchmarkrow_29',['BenchmarkRow',['../structBenchmarkRow.html',1,'']]],
  ['benchmarkscalar25d_30',['benchmarkscalar25d',['../classBenchmarkScalar25D.html',1,'BenchmarkScalar25D'],['../classBenchmarkScalar25D.html#ae4edcd8ffaa670474c7408abf86b5437',1,'BenchmarkScalar25D::BenchmarkScalar25D()']]],
  ['better_31',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['bfs_32',['D. Connected-Component 2.5D Grid BFS',['../md_docs_2projection.html#d-connected-component-25d-grid-bfs',1,'']]],
  ['binary_20—_20known_20limitation_33',['6b. The bind-mounted &lt;tt&gt;/opt/gem5&lt;/tt&gt; binary — known limitation',['../md_docs_2setup.html#autotoc_md6b-the-bind-mounted-optgem5-binary--known-limitation',1,'']]],
  ['binary_20file_34',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['binary_20interface_35',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['binary_20to_20execute_36',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['bind_20mounted_20tt_20opt_20gem5_20tt_20binary_20—_20known_20limitation_37',['6b. The bind-mounted &lt;tt&gt;/opt/gem5&lt;/tt&gt; binary — known limitation',['../md_docs_2setup.html#autotoc_md6b-the-bind-mounted-optgem5-binary--known-limitation',1,'']]],
  ['blockquote_38',['blockquote',['../instruction_manual.html#blockquote',1,'&lt;/blockquote&gt;'],['../md_docs_2projection.html#blockquote-1',1,'&lt;/blockquote&gt;']]],
  ['board_39',['Why this board?',['../instruction_manual.html#why-this-board',1,'']]],
  ['boolean_20vectors_40',['4. Vector Masks (Boolean Vectors)',['../instruction_manual.html#autotoc_md4-vector-masks-boolean-vectors',1,'']]],
  ['bottleneck_20analysis_20report_41',['Pipeline Performance Profiling &amp; Bottleneck Analysis Report',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html',1,'']]],
  ['bpi_20f3_42',['Target Hardware: Banana Pi BPI-F3',['../instruction_manual.html#target-hardware-banana-pi-bpi-f3',1,'']]],
  ['breakdown_43',['breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown'],['../instruction_manual.html#command-breakdown',1,'Command Breakdown'],['../instruction_manual.html#qemu-execution-command-breakdown',1,'QEMU Execution Command Breakdown'],['../instruction_manual.html#summary-qemu-command-breakdown',1,'Summary: QEMU Command Breakdown'],['../vector_theory.html#the-code-breakdown',1,'The Code Breakdown']]],
  ['breakdown_20across_20configurations_44',['Stage Breakdown Across Configurations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#stage-breakdown-across-configurations',1,'']]],
  ['build_45',['build',['../classFusedHashLeafOctree.html#ae752196aafb4cf0504c5c8d1ec50623d',1,'FusedHashLeafOctree::build()'],['../classrvpoint_1_1CaravanPointerOctree.html#aab6baa89272f000f787e642d716540b9',1,'rvpoint::CaravanPointerOctree::build()'],['../classrvpoint_1_1Octree.html#a9235b95b07bffd48f681e68b8839fc1f',1,'rvpoint::Octree::build()'],['../classrvpoint_1_1PointerOctree.html#afd8c9a749eefd4a40a44e02b61315f37',1,'rvpoint::PointerOctree::build()'],['../classrvpoint_1_1SpatialHash.html#adb0ca62affa106dc4e341b9aea31f37c',1,'rvpoint::SpatialHash::build()'],['../classSIMDOctree8Wide.html#a14d878a21888a9a9dec0709cec4e0973',1,'SIMDOctree8Wide::build()'],['../classFast3DSpatialGrid.html#a3fccbcd236130cd685157096fc1e5606',1,'Fast3DSpatialGrid::build()'],['../classLinearMortonOctree.html#aa1d848bcd79035f3cfdc7799f407e7d0',1,'LinearMortonOctree::build()'],['../classCompactSparse3DGridBench.html#af7c6f2f73c491caec2d2773c8e3dd6d4',1,'CompactSparse3DGridBench::build()'],['../index.html#manual-build',1,'Manual Build']]],
  ['build_20targeting_20gcc_2014_20strong_46',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['build_20the_20image_47',['1. Build the image',['../md_docs_2setup.html#autotoc_md1-build-the-image',1,'']]],
  ['build_5fepsilon_5f_48',['build_epsilon_',['../classrvpoint_1_1Octree.html#ab5e696e8420666def53e84a80ab3af33',1,'rvpoint::Octree::build_epsilon_'],['../classrvpoint_1_1PointerOctree.html#a8b24b68dd5e369327ad573e424392089',1,'rvpoint::PointerOctree::build_epsilon_']]],
  ['build_5fpoint_5fcloud_5fmsg_49',['build_point_cloud_msg',['../namespaceexport__mcap.html#a5d2ddfce77d4d90e3f41a61f991fdc7e',1,'export_mcap']]],
  ['building_20and_20running_20the_20project_50',['7. Building and running the project',['../md_docs_2setup.html#autotoc_md7-building-and-running-the-project',1,'']]],
  ['building_20for_20linux_51',['Building for Linux',['../index.html#building-for-linux',1,'']]],
  ['building_20testing_52',['🏗️ Building &amp; Testing',['../index.html#️-building--testing',1,'']]],
  ['buildparams_53',['buildparams',['../classrvpoint_1_1PointerOctree.html#a33e4b2d97cd0a78580073bc14e107da8',1,'rvpoint::PointerOctree::buildParams()'],['../classrvpoint_1_1Octree.html#a74954b471f986a9bfe8b818812cae937',1,'rvpoint::Octree::buildParams()']]],
  ['by_20step_20execution_3a_20voxel_20grid_20test_54',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]]
];
