var searchData=
[
  ['i_20src_20include_20tt_20include_20directory_0',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['icache_1',['icache',['../namespacegem5__se.html#a6c084a5f910a69caf738136129aa9657',1,'gem5_se']]],
  ['icache_5fport_2',['icache_port',['../namespacegem5__se.html#a8451d6b42945fbc53c9b5e864274c447',1,'gem5_se']]],
  ['idx_3',['idx',['../structQueryOrder.html#ab4cb64ef6ab9f063d3bf1e905ba389af',1,'QueryOrder']]],
  ['illegal_20instruction_4',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['illegalinstfault_20tt_5',['gem5 v24 does not support all RVV instructions — &lt;tt&gt;normal_rvv&lt;/tt&gt; hits &lt;tt&gt;IllegalInstFault&lt;/tt&gt;',['../md_guides_2session__2026-04-07.html#gem5-v24-does-not-support-all-rvv-instructions--normal_rvv-hits-illegalinstfault',1,'']]],
  ['image_20only_20when_20dockerfile_20changes_6',['Building Docker Image (only when Dockerfile changes)',['../md_guides_2AGENT.html#building-docker-image-only-when-dockerfile-changes',1,'']]],
  ['implementation_20guide_7',['RISC-V Vector (RVV) Implementation Guide',['../vector_theory.html#risc-v-vector-rvv-implementation-guide',1,'']]],
  ['implemented_8',['Algorithms Implemented',['../md_guides_2AGENT.html#algorithms-implemented',1,'']]],
  ['impossible_20inside_20docker_20containers_9',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['in_20sor_10',['Integration in SOR',['../vector_theory.html#integration-in-sor',1,'']]],
  ['in_20tt_20rvv_5fcommon_20cpp_20tt_11',['Key RVV Kernels (in &lt;tt&gt;rvv_common.cpp&lt;/tt&gt;)',['../md_guides_2AGENT.html#key-rvv-kernels-in-rvv_commoncpp',1,'']]],
  ['include_20directory_12',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['include_20tt_20include_20directory_13',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['indexed_20load_14',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['indexing_15',['Spatial Indexing',['../instruction_manual.html#spatial-indexing',1,'']]],
  ['indices_16',['indices',['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#ac0837d16b5ac1b2ba640205d5a7ea296',1,'rvv_pcl::VectorizedTraversalOctreeNode::indices'],['../structrvv__pcl_1_1PointerOctreeNode.html#a383f2f80a01cf51bc3773ef966042a0c',1,'rvv_pcl::PointerOctreeNode::indices'],['../structrvv__pcl_1_1KdTreeNode.html#ad566f013a08a632d9928fdabedb8cf3c',1,'rvv_pcl::KdTreeNode::indices'],['../structrvv__pcl_1_1OctreeNode.html#a28c02748d58d247cd0f5cb248f1420f6',1,'rvv_pcl::OctreeNode::indices'],['../structrvv__pcl_1_1CustomPointerOctreeNode.html#a3a21ddf9d1d3551a843f34269a9f1749',1,'rvv_pcl::CustomPointerOctreeNode::indices']]],
  ['initialization_20strong_17',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['input_18',['5. Source Files - Input',['../instruction_manual.html#autotoc_md5-source-files---input',1,'']]],
  ['input_5fpcd_19',['input_pcd',['../namespacevisualize__result.html#aa00bb6b32dea28c9b60df9d3fa1117d2',1,'visualize_result']]],
  ['inside_20container_20',['CMake Build (inside container)',['../md_guides_2AGENT.html#cmake-build-inside-container',1,'']]],
  ['inside_20container_20directly_21',['Running Commands Inside Container Directly',['../md_guides_2AGENT.html#running-commands-inside-container-directly',1,'']]],
  ['inside_20docker_20containers_22',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['insn_20per_20tb_20tt_23',['1. &lt;tt&gt;one-insn-per-tb&lt;/tt&gt;',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md1-one-insn-per-tb',1,'']]],
  ['inspecting_20compilation_20output_24',['Inspecting Compilation Output',['../instruction_manual.html#inspecting-compilation-output',1,'']]],
  ['inst_20constrs_20cc_20tt_20compilation_20oom_20killed_20even_20with_20moderate_20parallelism_25',['gem5 &lt;tt&gt;inst-constrs.cc&lt;/tt&gt; compilation OOM-killed even with moderate parallelism',['../md_guides_2session__2026-04-07.html#gem5-inst-constrscc-compilation-oom-killed-even-with-moderate-parallelism',1,'']]],
  ['instruction_26',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['instruction_20counting_20methodology_27',['Instruction Counting Methodology',['../md_tests_2INSTRUCTION__COUNTING.html',1,'']]],
  ['instruction_20counting_20rdinstret_28',['Instruction Counting (rdinstret)',['../md_guides_2AGENT.html#instruction-counting-rdinstret',1,'']]],
  ['instruction_20emulation_20strong_29',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['instruction_20encoding_20formats_30',['3. Instruction Encoding Formats',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md3-instruction-encoding-formats',1,'']]],
  ['instruction_20execution_20loop_20strong_31',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['instruction_20manual_20reference_20guide_32',['RVPoint Instruction Manual &amp; Reference Guide',['../instruction_manual.html#rvpoint-instruction-manual--reference-guide',1,'']]],
  ['instruction_5fcounting_2emd_33',['INSTRUCTION_COUNTING.md',['../INSTRUCTION__COUNTING_8md.html',1,'']]],
  ['instruction_5fmanual_34',['INSTRUCTION_MANUAL',['../instruction_manual.html',1,'']]],
  ['instruction_5fmanual_2emd_35',['INSTRUCTION_MANUAL.md',['../INSTRUCTION__MANUAL_8md.html',1,'']]],
  ['instructions_20—_20tt_20normal_5frvv_20tt_20hits_20tt_20illegalinstfault_20tt_36',['gem5 v24 does not support all RVV instructions — &lt;tt&gt;normal_rvv&lt;/tt&gt; hits &lt;tt&gt;IllegalInstFault&lt;/tt&gt;',['../md_guides_2session__2026-04-07.html#gem5-v24-does-not-support-all-rvv-instructions--normal_rvv-hits-illegalinstfault',1,'']]],
  ['instructions_20specification_37',['2. Custom Instructions Specification',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md2-custom-instructions-specification',1,'']]],
  ['instructiontimer_38',['InstructionTimer',['../structInstructionTimer.html',1,'']]],
  ['integration_39',['4. Software Usage &amp; Compiler Integration',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md4-software-usage--compiler-integration',1,'']]],
  ['integration_20in_20sor_40',['Integration in SOR',['../vector_theory.html#integration-in-sor',1,'']]],
  ['integration_20usage_20guide_41',['Team Integration &amp; Usage Guide',['../instruction_manual.html#team-integration--usage-guide',1,'']]],
  ['interface_42',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['internally_20complete_20flow_43',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['intrinsics_44',['Common Intrinsics',['../instruction_manual.html#common-intrinsics',1,'']]],
  ['intrinsics_20naming_20convention_45',['3. Intrinsics Naming Convention',['../vector_theory.html#autotoc_md3-intrinsics-naming-convention',1,'']]],
  ['intrinsics_20naming_20guide_46',['3. Vector Intrinsics Naming Guide',['../instruction_manual.html#autotoc_md3-vector-intrinsics-naming-guide',1,'']]],
  ['is_20better_47',['Why this is better',['../vector_theory.html#why-this-is-better',1,'']]],
  ['is_20impossible_20inside_20docker_20containers_48',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['is_20not_20pipeline_20cost_49',['Ground Truth Generation Is Not Pipeline Cost',['../md_guides_2AGENT.html#ground-truth-generation-is-not-pipeline-cost',1,'']]],
  ['is_5fleaf_50',['is_leaf',['../structrvv__pcl_1_1MortonPointerOctreeNode.html#a52cd276e4396ac54b66a7f3b2aff3b42',1,'rvv_pcl::MortonPointerOctreeNode::is_leaf'],['../structrvv__pcl_1_1KdTreeNode.html#ac1706746643cdd80a1818430d463f1d7',1,'rvv_pcl::KdTreeNode::is_leaf'],['../structrvv__pcl_1_1OctreeNode.html#aa60688f7c1a975c33ad7eb5ecde8de9d',1,'rvv_pcl::OctreeNode::is_leaf'],['../structrvv__pcl_1_1CustomPointerOctreeNode.html#a32b797477607838150076beeefb622ba',1,'rvv_pcl::CustomPointerOctreeNode::is_leaf'],['../structrvv__pcl_1_1PacketPointerOctreeNode.html#a146453b4793c1a23632ae9b193cc5b9a',1,'rvv_pcl::PacketPointerOctreeNode::is_leaf'],['../structrvv__pcl_1_1PointerOctreeNode.html#ad7abbb03c35499ea0b5792cc38728f33',1,'rvv_pcl::PointerOctreeNode::is_leaf'],['../structrvv__pcl_1_1VectorizedTraversalOctreeNode.html#a82881068de4f1559e9020d8fd7641cd1',1,'rvv_pcl::VectorizedTraversalOctreeNode::is_leaf']]],
  ['it_20does_51',['What it does',['../md_guides_2AGENT.html#what-it-does',1,'']]]
];
