var searchData=
[
  ['s_20approach_0',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['savepcd_1',['savePCD',['../namespacervpoint.html#ae8569e421b46a394d8ae193bd16d38f1',1,'rvpoint']]],
  ['savepcd_20file_5fpath_20points_5fvector_20tt_2',['&lt;tt&gt;savePCD(file_path, points_vector)&lt;/tt&gt;',['../instruction_manual.html#savepcdfile_path-points_vector',1,'']]],
  ['savepcdrgb_3',['savePCDRGB',['../namespacervpoint.html#a66f6347c4ab3f8ceb1f72ddea9000361',1,'rvpoint']]],
  ['scalar_20code_4',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['scalar_20execution_5',['Scalar Execution',['../instruction_manual.html#scalar-execution',1,'']]],
  ['scalar_5f25d_5fbaseline_2ecpp_6',['scalar_25d_baseline.cpp',['../scalar__25d__baseline_8cpp.html',1,'']]],
  ['scaling_7',['scaling',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-d-ransac-plane-fitting-iteration-scaling-1',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling'],['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-d-ransac-plane-fitting-iteration-scaling',1,'Ablation D: RANSAC Plane Fitting Iteration Scaling']]],
  ['script_20s_20approach_8',['6a. Via the &lt;tt&gt;manuel313/gem5_v25&lt;/tt&gt; Docker image (the wrapper script&apos;s approach)',['../md_docs_2setup.html#autotoc_md6a-via-the-manuel313gem5_v25-docker-image-the-wrapper-scripts-approach',1,'']]],
  ['scripts_20profile_5fpipeline_20py_20tt_9',['Automated Two-Phase Workflow (&lt;tt&gt;scripts/profile_pipeline.py&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#automated-two-phase-workflow-scriptsprofile_pipelinepy',1,'']]],
  ['search_10',['Ablation B: Spatial Neighbor Search',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-b-spatial-neighbor-search',1,'']]],
  ['search_20methods_20_24n_2018_20542_24_11',['Ablation B: Spatial Neighbor Search Methods ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'']]],
  ['search_20strong_12',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['searcher_5f_13',['searcher_',['../classrvpoint_1_1EuclideanClustering.html#adb507a7d71d40996f11132c82c47aa50',1,'rvpoint::EuclideanClustering']]],
  ['searchrecursive_14',['searchRecursive',['../classSIMDOctree8Wide.html#a09e5d46a326a636748a30472b975d858',1,'SIMDOctree8Wide']]],
  ['segment_15',['segment',['../classBenchmarkScalar25D.html#af79d54c0268f074532fb33e9f2e90036',1,'BenchmarkScalar25D']]],
  ['segmentground_16',['segmentGround',['../classSweepTurboGrid.html#ad4edbc2ca77ba63ef65c5d46918745a7',1,'SweepTurboGrid']]],
  ['segmentobstacles_17',['segmentObstacles',['../classBenchmarkFusedRVV.html#a4be6fd2882a0c8947fc871a5e4ecfda3',1,'BenchmarkFusedRVV']]],
  ['selection_3a_20linux_20vs_20bare_20metal_18',['Compiler Selection: Linux vs Bare Metal',['../instruction_manual.html#compiler-selection-linux-vs-bare-metal',1,'']]],
  ['serialization_20results_19',['3. Serialization &amp; Results',['../instruction_manual.html#autotoc_md3-serialization--results',1,'']]],
  ['serve_5flocal_20',['serve_local',['../namespaceserve__mcap.html#ab765f5181efd048aa005ba3699b6f5f1',1,'serve_mcap']]],
  ['serve_5fmcap_21',['serve_mcap',['../namespaceserve__mcap.html',1,'']]],
  ['serve_5fmcap_2epy_22',['serve_mcap.py',['../serve__mcap_8py.html',1,'']]],
  ['set_20vector_20length_23',['1. &lt;tt&gt;vsetvl&lt;/tt&gt; (Vector Set Vector Length)',['../vector_theory.html#autotoc_md1-vsetvl-vector-set-vector-length',1,'']]],
  ['setbuildepsilon_24',['setbuildepsilon',['../classrvpoint_1_1Octree.html#aa084525b81cdf079d4e24898392e208e',1,'rvpoint::Octree::setBuildEpsilon()'],['../classrvpoint_1_1PointerOctree.html#aef6793888d0b969c3d93bed78d491b06',1,'rvpoint::PointerOctree::setBuildEpsilon()']]],
  ['setclustertolerance_25',['setClusterTolerance',['../classrvpoint_1_1EuclideanClustering.html#a48122007cf2e77b32504af324e1aa2dd',1,'rvpoint::EuclideanClustering']]],
  ['sethashprimes_26',['setHashPrimes',['../classrvpoint_1_1SpatialHash.html#aec8f3dc5735dfb62c30afc097b6b26fc',1,'rvpoint::SpatialHash']]],
  ['setinputcloud_27',['setinputcloud',['../classrvpoint_1_1PointerOctree.html#adb111cc23de16a2afbdbb033f88eb090',1,'rvpoint::PointerOctree::setInputCloud()'],['../classrvpoint_1_1CaravanPointerOctree.html#ad23f95ee0abbfe2f622eb3fd7b6546f7',1,'rvpoint::CaravanPointerOctree::setInputCloud()'],['../classrvpoint_1_1CaravanRadiusSearch.html#af4dc6e05a8ad91de7dbc089cd20996e5',1,'rvpoint::CaravanRadiusSearch::setInputCloud()'],['../classrvpoint_1_1Octree.html#a80f3ed970d115e61cea9861ac22b98af',1,'rvpoint::Octree::setInputCloud()'],['../classrvpoint_1_1SpatialHash.html#ab9311fe263815b3a5d4da653d71e397c',1,'rvpoint::SpatialHash::setInputCloud()'],['../classrvpoint_1_1EuclideanClustering.html#a1c51e0fdd3c8b2e8eb3c58ada989a735',1,'rvpoint::EuclideanClustering::setInputCloud(const PointCloudSoA &amp;cloud)']]],
  ['setmaxclustersize_28',['setMaxClusterSize',['../classrvpoint_1_1EuclideanClustering.html#a05ec9a85ed465146cd6d0eafe3deb9b0',1,'rvpoint::EuclideanClustering']]],
  ['setmaxdepth_29',['setmaxdepth',['../classrvpoint_1_1PointerOctree.html#ae7607bf20250b0029ae3730314af7f84',1,'rvpoint::PointerOctree::setMaxDepth()'],['../classrvpoint_1_1Octree.html#a258b891d51bbe4a5b7f97952cf0c4231',1,'rvpoint::Octree::setMaxDepth()']]],
  ['setmaxpointsperleaf_30',['setmaxpointsperleaf',['../classrvpoint_1_1PointerOctree.html#a36bf87bb5747b3b11bfc170136935437',1,'rvpoint::PointerOctree::setMaxPointsPerLeaf()'],['../classrvpoint_1_1Octree.html#aa0536a364510da0e2546df4f76d62cb6',1,'rvpoint::Octree::setMaxPointsPerLeaf()']]],
  ['setminclustersize_31',['setMinClusterSize',['../classrvpoint_1_1EuclideanClustering.html#a6481eca847d3cfff689e2cd52a978e53',1,'rvpoint::EuclideanClustering']]],
  ['setneighborsearch_32',['setneighborsearch',['../classrvpoint_1_1EuclideanClustering.html#a02e279d5cddd629d9dbbe9bcc112c8eb',1,'rvpoint::EuclideanClustering::setNeighborSearch(const PointerOctree *search)'],['../classrvpoint_1_1EuclideanClustering.html#a4efefbc78a13110f4830016990aaff23',1,'rvpoint::EuclideanClustering::setNeighborSearch(const Octree *search)']]],
  ['setup_33',['setup',['../index.html#️-installation--setup',1,'🛠️ Installation &amp; Setup'],['../md_docs_2setup.html',1,'RVPoint Docker Environment Setup']]],
  ['setup_20and_20verification_34',['6. gem5 setup and verification',['../md_docs_2setup.html#autotoc_md6-gem5-setup-and-verification',1,'']]],
  ['setup_20ubuntu_2024_2004_35',['WSL2 Setup (Ubuntu 24.04)',['../index.html#wsl2-setup-ubuntu-2404',1,'']]],
  ['setup_2emd_36',['setup.md',['../setup_8md.html',1,'']]],
  ['shared_20tile_20aabb_37',['B. Octree Traversal with Shared Tile AABB',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#b-octree-traversal-with-shared-tile-aabb',1,'']]],
  ['simdoctree8wide_38',['simdoctree8wide',['../classSIMDOctree8Wide.html#a8933bc3bfd3f5bd3c8b0cfe3ef26f576',1,'SIMDOctree8Wide::SIMDOctree8Wide()'],['../classSIMDOctree8Wide.html',1,'SIMDOctree8Wide']]],
  ['simdoctreenode8wide_39',['SIMDOctreeNode8Wide',['../structSIMDOctreeNode8Wide.html',1,'']]],
  ['simple_5feigen3x3_5fsmallest_40',['simple_eigen3x3_smallest',['../namespacervpoint.html#afca43ab8c35a62f79cde3c61a84186a4',1,'rvpoint']]],
  ['simple_5fpcd_5floader_2eh_41',['simple_pcd_loader.h',['../simple__pcd__loader_8h.html',1,'']]],
  ['sizes_42',['sizes',['../structrvpoint_1_1detail_1_1PCDHeader.html#ac7023299c24afc7c2e1f6bdc30aae009',1,'rvpoint::detail::PCDHeader']]],
  ['soa_43',['soa',['../structrvpoint_1_1bench_1_1BenchmarkCloudHolder.html#a354541b4db8fca0a83b85ac56a94943f',1,'rvpoint::bench::BenchmarkCloudHolder']]],
  ['soa_20structure_44',['Create SoA Structure',['../instruction_manual.html#create-soa-structure',1,'']]],
  ['soa_20vector_20code_45',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['soabuffer_46',['SoABuffer',['../structSoABuffer.html',1,'']]],
  ['solution_3a_20trace_20based_20counting_47',['The Solution: Trace-Based Counting',['../md_docs_2INSTRUCTION__COUNTING.html#the-solution-trace-based-counting',1,'']]],
  ['solution_3a_20tt_20vluxei32_20tt_20indexed_20load_48',['The Solution: &lt;tt&gt;vluxei32&lt;/tt&gt; (Indexed Load)',['../vector_theory.html#the-solution-vluxei32-indexed-load',1,'']]],
  ['solutions_49',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['sor_50',['sor',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-c-statistical-outlier-removal-sor',1,'Ablation C: Statistical Outlier Removal (SOR)'],['../vector_theory.html#integration-in-sor',1,'Integration in SOR']]],
  ['sor_20implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_51',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['sor_20strong_52',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['sor_5fgrid_5fcaravan_53',['sor_grid_caravan',['../namespacervpoint.html#a752ed79bf7e97fbedbb613b253450978',1,'rvpoint']]],
  ['sor_5foctree_54',['sor_octree',['../namespacervpoint.html#ae198927a038a7272cf580a377e218f16',1,'rvpoint']]],
  ['sor_5fpointer_5foctree_55',['sor_pointer_octree',['../namespacervpoint.html#aca2f4a96c9327030e4c252a56e9a0a25',1,'rvpoint']]],
  ['sor_5frvv_56',['sor_rvv',['../namespacervpoint.html#aa7999d712225b741113d5850a9bd9e50',1,'rvpoint']]],
  ['sor_5fsc_57',['sor_sc',['../namespacervpoint.html#a744416d5cd3a5ddf347bd201947efa73',1,'rvpoint']]],
  ['sor_5fspatial_5fhash_58',['sor_spatial_hash',['../namespacervpoint.html#acf6d015f1ab8185f8d0a1f8173e62358',1,'rvpoint']]],
  ['sorfilter_59',['sorFilter',['../classrvpoint_1_1CaravanPointerOctree.html#a4e395d976a2aae032cb1f59e1663c751',1,'rvpoint::CaravanPointerOctree']]],
  ['source_20files_20input_60',['5. Source Files - Input',['../instruction_manual.html#autotoc_md5-source-files---input',1,'']]],
  ['spatial_20indexing_61',['Spatial Indexing',['../instruction_manual.html#spatial-indexing',1,'']]],
  ['spatial_20neighbor_20search_62',['Ablation B: Spatial Neighbor Search',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-b-spatial-neighbor-search',1,'']]],
  ['spatial_20neighbor_20search_20methods_20_24n_2018_20542_24_63',['Ablation B: Spatial Neighbor Search Methods ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-b-spatial-neighbor-search-methods-n18542',1,'']]],
  ['spatial_20tree_20construction_20tt_20octree_3a_3abuild_20tt_64',['A. Spatial Tree Construction (&lt;tt&gt;Octree::build&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#a-spatial-tree-construction-octreebuild',1,'']]],
  ['spatial_5fhashing_2ecpp_65',['spatial_hashing.cpp',['../spatial__hashing_8cpp.html',1,'']]],
  ['spatial_5fhashing_2eh_66',['spatial_hashing.h',['../spatial__hashing_8h.html',1,'']]],
  ['spatialhash_67',['spatialhash',['../classrvpoint_1_1SpatialHash.html#a9fede3a289ac19ef70c666d635f64cf8',1,'rvpoint::SpatialHash::SpatialHash()'],['../classrvpoint_1_1SpatialHash.html',1,'rvpoint::SpatialHash']]],
  ['spatialhash_20tt_20strong_68',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['specification_69',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['speedup_70',['2. Why &lt;tt&gt;pipeline_export&lt;/tt&gt; Capped at ~1.6× Speedup',['../md_docs_2projection.html#autotoc_md2-why-pipeline_export-capped-at-16-speedup',1,'']]],
  ['splitby3_71',['splitBy3',['../test__all__3d__branching__approaches_8cpp.html#a599ba77a8e32c7dfa9859238cb5752f2',1,'test_all_3d_branching_approaches.cpp']]],
  ['src_20include_20profiler_20h_20tt_72',['Zero-Overhead Compile-Time Toggle (&lt;tt&gt;src/include/profiler.h&lt;/tt&gt;)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#zero-overhead-compile-time-toggle-srcincludeprofilerh',1,'']]],
  ['src_20include_20tt_20include_20directory_73',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['stage_201_3a_20preprocessing_74',['Stage 1: Preprocessing',['../instruction_manual.html#stage-1-preprocessing',1,'']]],
  ['stage_202_3a_20compilation_75',['Stage 2: Compilation',['../instruction_manual.html#stage-2-compilation',1,'']]],
  ['stage_203_3a_20assembly_76',['Stage 3: Assembly',['../instruction_manual.html#stage-3-assembly',1,'']]],
  ['stage_204_3a_20linking_77',['Stage 4: Linking',['../instruction_manual.html#stage-4-linking',1,'']]],
  ['stage_208_78',['B. RANSAC Sub-Actions (Stage 8)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#b-ransac-sub-actions-stage-8',1,'']]],
  ['stage_209_79',['C. Euclidean Clustering Sub-Actions (Stage 9)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#c-euclidean-clustering-sub-actions-stage-9',1,'']]],
  ['stage_20breakdown_20across_20configurations_80',['Stage Breakdown Across Configurations',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#stage-breakdown-across-configurations',1,'']]],
  ['stage_20sub_20stage_20micro_20timing_20breakdown_81',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['stage_20timing_20matrix_82',['High-Level Stage Timing Matrix',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#high-level-stage-timing-matrix',1,'']]],
  ['stages_83',['The 4 Compilation Stages',['../instruction_manual.html#the-4-compilation-stages',1,'']]],
  ['standardized_20development_20workflow_84',['1. Standardized Development Workflow',['../instruction_manual.html#autotoc_md1-standardized-development-workflow',1,'']]],
  ['start_85',['start',['../instruction_manual.html#program-start',1,'Program Start'],['../classTimer.html#a3a8b5272198d029779dc9302a54305a8',1,'Timer::start()'],['../structInstructionTimer.html#a7168bb762d280110c7b13e5f9b159f48',1,'InstructionTimer::start']]],
  ['start_20recommended_86',['Quick Start (Recommended)',['../index.html#quick-start-recommended',1,'']]],
  ['statement_87',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['statistical_20outlier_20removal_20sor_88',['Ablation C: Statistical Outlier Removal (SOR)',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#ablation-c-statistical-outlier-removal-sor',1,'']]],
  ['statistical_20outlier_20removal_20sor_20implementation_20variants_204_20caravan_20strategies_20_24n_2018_20542_24_89',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['statistical_20outlier_20removal_20sor_20strong_90',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['statistical_5foutlier_5fremoval_2ecpp_91',['statistical_outlier_removal.cpp',['../statistical__outlier__removal_8cpp.html',1,'']]],
  ['statistical_5foutlier_5fremoval_2eh_92',['statistical_outlier_removal.h',['../statistical__outlier__removal_8h.html',1,'']]],
  ['step_20by_20step_20execution_3a_20voxel_20grid_20test_93',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['steps_20for_20finalization_3a_94',['Next Steps for Finalization:',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#next-steps-for-finalization',1,'']]],
  ['steps_20for_20implementation_95',['5. Next Steps for Implementation',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md5-next-steps-for-implementation',1,'']]],
  ['steps_20manual_96',['Detailed Verification Steps (Manual)',['../index.html#detailed-verification-steps-manual',1,'']]],
  ['strategies_20_24n_2018_20542_24_97',['Ablation C: Statistical Outlier Removal (SOR) Implementation Variants &amp; 4 Caravan Strategies ($N=18,542$)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#ablation-c-statistical-outlier-removal-sor-implementation-variants--4-caravan-strategies-n18542',1,'']]],
  ['strip_20mining_20pattern_98',['1. Strip Mining Pattern',['../instruction_manual.html#autotoc_md1-strip-mining-pattern',1,'']]],
  ['strong_20a_20clean_20build_20targeting_20gcc_2014_20strong_99',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['strong_20adding_20a_20new_20algorithm_20strong_100',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['strong_20b_20running_20with_20system_20libraries_20strong_101',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]],
  ['strong_20class_20tt_20octree_20tt_20strong_102',['&lt;strong&gt;Class &lt;tt&gt;Octree&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-octree',1,'']]],
  ['strong_20class_20tt_20spatialhash_20tt_20strong_103',['&lt;strong&gt;Class &lt;tt&gt;SpatialHash&lt;/tt&gt;&lt;/strong&gt;',['../instruction_manual.html#class-spatialhash',1,'']]],
  ['strong_20normal_20estimation_20strong_104',['&lt;strong&gt;Normal Estimation&lt;/strong&gt;',['../instruction_manual.html#normal-estimation',1,'']]],
  ['strong_20phase_201_3a_20initialization_20strong_105',['&lt;strong&gt;Phase 1: Initialization&lt;/strong&gt;',['../instruction_manual.html#phase-1-initialization',1,'']]],
  ['strong_20phase_202_3a_20instruction_20execution_20loop_20strong_106',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['strong_20phase_203_3a_20system_20call_20translation_20strong_107',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['strong_20phase_204_3a_20vector_20instruction_20emulation_20strong_108',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['strong_20radius_20search_20strong_109',['&lt;strong&gt;Radius Search&lt;/strong&gt;',['../instruction_manual.html#radius-search',1,'']]],
  ['strong_20ransac_20plane_20fitting_20strong_110',['&lt;strong&gt;RANSAC Plane Fitting&lt;/strong&gt;',['../instruction_manual.html#ransac-plane-fitting',1,'']]],
  ['strong_20statistical_20outlier_20removal_20sor_20strong_111',['&lt;strong&gt;Statistical Outlier Removal (SOR)&lt;/strong&gt;',['../instruction_manual.html#statistical-outlier-removal-sor',1,'']]],
  ['strong_20voxel_20grid_20downsampling_20strong_112',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['struct_20pointcloudsoa_20tt_113',['&lt;tt&gt;struct PointCloudSoA&lt;/tt&gt;',['../instruction_manual.html#struct-pointcloudsoa',1,'']]],
  ['struct_20pointxyz_20tt_114',['&lt;tt&gt;struct PointXYZ&lt;/tt&gt;',['../instruction_manual.html#struct-pointxyz',1,'']]],
  ['structure_115',['structure',['../index.html#autotoc_md-project-structure',1,'📂 Project Structure'],['../instruction_manual.html#component-structure',1,'Component Structure'],['../instruction_manual.html#create-soa-structure',1,'Create SoA Structure']]],
  ['structure_20of_20arrays_20soa_20vector_20code_116',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['structures_117',['structures',['../instruction_manual.html#data-structures-1',1,'Data Structures'],['../instruction_manual.html#data-structures',1,'Data Structures']]],
  ['structures_20aos_20scalar_20code_118',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['sub_20action_20micro_20timing_20analysis_119',['Sub-Action Micro-Timing Analysis',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#sub-action-micro-timing-analysis',1,'']]],
  ['sub_20actions_20stage_208_120',['B. RANSAC Sub-Actions (Stage 8)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#b-ransac-sub-actions-stage-8',1,'']]],
  ['sub_20actions_20stage_209_121',['C. Euclidean Clustering Sub-Actions (Stage 9)',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#c-euclidean-clustering-sub-actions-stage-9',1,'']]],
  ['sub_20stage_20micro_20timing_20breakdown_122',['3. Phase 1: Pipeline Stage &amp; Sub-Stage Micro-Timing Breakdown',['../md_docs_2PIPELINE__PROFILING__AND__ABLATION__EXPERIMENT.html#autotoc_md3-phase-1-pipeline-stage--sub-stage-micro-timing-breakdown',1,'']]],
  ['subtraction_123',['3. Baseline Subtraction',['../md_docs_2INSTRUCTION__COUNTING.html#autotoc_md3-baseline-subtraction',1,'']]],
  ['summary_124',['summary',['../md_docs_2reports_22026-08-10-pipeline-profiling-analysis.html#autotoc_md1-executive-summary',1,'1. Executive Summary'],['../instruction_manual.html#configuration-options-summary',1,'Configuration Options Summary']]],
  ['summary_20benchmark_20evolution_125',['1. Executive Summary &amp; Benchmark Evolution',['../md_docs_2projection.html#autotoc_md1-executive-summary--benchmark-evolution',1,'']]],
  ['summary_20problem_20statement_126',['1. Executive Summary &amp; Problem Statement',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md1-executive-summary--problem-statement',1,'']]],
  ['summary_20table_127',['Performance Summary Table',['../vector_theory.html#performance-summary-table',1,'']]],
  ['summary_3a_20qemu_20command_20breakdown_128',['Summary: QEMU Command Breakdown',['../instruction_manual.html#summary-qemu-command-breakdown',1,'']]],
  ['sweepturbogrid_129',['sweepturbogrid',['../classSweepTurboGrid.html#a0f486dfde5a2ced0af30a5b6169501f2',1,'SweepTurboGrid::SweepTurboGrid()'],['../classSweepTurboGrid.html',1,'SweepTurboGrid']]],
  ['synergy_20expected_20performance_20impact_130',['3. Key Synergy &amp; Expected Performance Impact',['../md_docs_2plans_22026-08-10-caravan-pointer-octree-design.html#autotoc_md3-key-synergy--expected-performance-impact',1,'']]],
  ['system_20call_20translation_20strong_131',['&lt;strong&gt;Phase 3: System Call Translation&lt;/strong&gt;',['../instruction_manual.html#phase-3-system-call-translation',1,'']]],
  ['system_20libraries_20strong_132',['&lt;strong&gt;B. Running with System Libraries&lt;/strong&gt;',['../instruction_manual.html#b-running-with-system-libraries',1,'']]]
];
