var searchData=
[
  ['efficiency_0',['Why This Proves RVV Efficiency',['../md_tests_2INSTRUCTION__COUNTING.html#why-this-proves-rvv-efficiency',1,'']]],
  ['eigen_5fdecomposition_5frvv_1',['eigen_decomposition_rvv',['../namespacervv__pcl.html#ab6bf0c81cf1a0a4c26d0cd950f5e5789',1,'rvv_pcl']]],
  ['elapsed_2',['elapsed',['../structTimer.html#a7b0a5dca78dad1dc32bd528b8d558957',1,'Timer']]],
  ['elapsedms_3',['elapsedMs',['../structTimer.html#aff1a7e5d5dbcca1b9a7f679afc2f371a',1,'Timer']]],
  ['emulation_20strong_4',['&lt;strong&gt;Phase 4: Vector Instruction Emulation&lt;/strong&gt;',['../instruction_manual.html#phase-4-vector-instruction-emulation',1,'']]],
  ['emulator_5',['1️⃣ &lt;tt&gt;qemu-riscv64&lt;/tt&gt; - The Emulator',['../instruction_manual.html#autotoc_md1️⃣-qemu-riscv64---the-emulator',1,'']]],
  ['enabled_6',['New Features Enabled',['../index.html#new-features-enabled',1,'']]],
  ['eps_5fscale_5f_7',['eps_scale_',['../classrvv__pcl_1_1SpatialHash.html#a4d5764b064b2b5beef84d4e653444e68',1,'rvv_pcl::SpatialHash']]],
  ['error_201_3a_20illegal_20instruction_8',['Error 1: &quot;Illegal instruction&quot;',['../instruction_manual.html#error-1-illegal-instruction',1,'']]],
  ['error_202_3a_20cannot_20execute_20binary_20file_9',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['error_203_3a_20qemu_20riscv64_3a_20command_20not_20found_10',['Error 3: &quot;qemu-riscv64: command not found&quot;',['../instruction_manual.html#error-3-qemu-riscv64-command-not-found',1,'']]],
  ['errors_20solutions_11',['Common QEMU Errors &amp; Solutions',['../instruction_manual.html#common-qemu-errors--solutions',1,'']]],
  ['estimation_20strong_12',['&lt;strong&gt;Normal Estimation&lt;/strong&gt;',['../instruction_manual.html#normal-estimation',1,'']]],
  ['example_3a_20what_20happens_20when_20you_20run_20the_20command_13',['Complete Example: What Happens When You Run the Command',['../instruction_manual.html#complete-example-what-happens-when-you-run-the-command',1,'']]],
  ['exec_20nochain_20tt_14',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['execute_15',['3️⃣ &lt;tt&gt;test_voxel_rvv&lt;/tt&gt; - The Binary to Execute',['../instruction_manual.html#autotoc_md3️⃣-test_voxel_rvv---the-binary-to-execute',1,'']]],
  ['execute_20binary_20file_16',['Error 2: &quot;cannot execute binary file&quot;',['../instruction_manual.html#error-2-cannot-execute-binary-file',1,'']]],
  ['execution_17',['Scalar Execution',['../instruction_manual.html#scalar-execution',1,'']]],
  ['execution_20⚡_18',['RVV Vector Execution ⚡',['../instruction_manual.html#rvv-vector-execution-',1,'']]],
  ['execution_20command_20breakdown_19',['QEMU Execution Command Breakdown',['../instruction_manual.html#qemu-execution-command-breakdown',1,'']]],
  ['execution_20commands_20',['Execution Commands',['../instruction_manual.html#execution-commands',1,'']]],
  ['execution_20flow_21',['Execution Flow',['../instruction_manual.html#execution-flow',1,'']]],
  ['execution_20loop_20strong_22',['&lt;strong&gt;Phase 2: Instruction Execution Loop&lt;/strong&gt;',['../instruction_manual.html#phase-2-instruction-execution-loop',1,'']]],
  ['execution_3a_20voxel_20grid_20test_23',['Step-by-Step Execution: Voxel Grid Test',['../instruction_manual.html#step-by-step-execution-voxel-grid-test',1,'']]],
  ['expected_20output_24',['3. Expected Output',['../pipeline_demo.html#autotoc_md3-expected-output',1,'']]],
  ['expected_20results_25',['Expected Results',['../index.html#expected-results',1,'']]],
  ['extend_20the_20code_26',['2. How to Function &amp; Extend the Code',['../instruction_manual.html#autotoc_md2-how-to-function--extend-the-code',1,'']]]
];
