var searchData=
[
  ['a_20clean_20build_20targeting_20gcc_2014_20strong_0',['&lt;strong&gt;A. Clean Build (Targeting GCC 14)&lt;/strong&gt;',['../instruction_manual.html#a-clean-build-targeting-gcc-14',1,'']]],
  ['a_20new_20algorithm_1',['Task 3: Adding a New Algorithm',['../md_guides_2AGENT.html#task-3-adding-a-new-algorithm',1,'']]],
  ['a_20new_20algorithm_20strong_2',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['a_20qemu_20vm_20—_20limits_20container_20ram_20to_205_206_20gb_3',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['a_20specific_20algorithm_20test_4',['Task 2: Running a Specific Algorithm Test',['../md_guides_2AGENT.html#task-2-running-a-specific-algorithm-test',1,'']]],
  ['a_20tt_20vdist3d_20vf_20tt_20fused_203d_20squared_20distance_5',['A. &lt;tt&gt;vdist3d.vf&lt;/tt&gt; (Fused 3D Squared Distance)',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#a-vdist3dvf-fused-3d-squared-distance',1,'']]],
  ['active_5fmask_6',['active_mask',['../structrvv__pcl_1_1TraversalItem.html#a2b1df52cf5dd447ff713f6e320d53ef4',1,'rvv_pcl::TraversalItem']]],
  ['adding_20a_20new_20algorithm_7',['Task 3: Adding a New Algorithm',['../md_guides_2AGENT.html#task-3-adding-a-new-algorithm',1,'']]],
  ['adding_20a_20new_20algorithm_20strong_8',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['addition_9',['CMakeLists.txt addition',['../md_guides_2AGENT.html#cmakeliststxt-addition',1,'']]],
  ['advanced_20optimization_3a_20fused_20gather_20filter_10',['Advanced Optimization: Fused Gather-Filter',['../vector_theory.html#advanced-optimization-fused-gather-filter',1,'']]],
  ['advanced_20topics_11',['Advanced Topics',['../instruction_manual.html#advanced-topics',1,'']]],
  ['agent_20best_20practices_12',['Agent Best Practices',['../md_guides_2AGENT.html#agent-best-practices',1,'']]],
  ['agent_20guide_3a_20rvpoint_13',['AI Agent Guide: RVPoint',['../md_guides_2AGENT.html',1,'']]],
  ['agent_2emd_14',['AGENT.md',['../AGENT_8md.html',1,'']]],
  ['agents_15',['agents',['../md_guides_2AGENT.html#common-tasks-for-agents',1,'Common Tasks for Agents'],['../md_guides_2AGENT.html#critical-gotchas-for-agents',1,'Critical Gotchas for Agents'],['../md_guides_2AGENT.html#quick-start-for-agents',1,'Quick Start for Agents'],['../md_guides_2AGENT.html#recommended-reading-order-for-new-agents',1,'Recommended Reading Order for New Agents']]],
  ['ai_20agent_20guide_3a_20rvpoint_16',['AI Agent Guide: RVPoint',['../md_guides_2AGENT.html',1,'']]],
  ['algorithm_17',['Task 3: Adding a New Algorithm',['../md_guides_2AGENT.html#task-3-adding-a-new-algorithm',1,'']]],
  ['algorithm_20strong_18',['&lt;strong&gt;Adding a New Algorithm&lt;/strong&gt;',['../instruction_manual.html#adding-a-new-algorithm',1,'']]],
  ['algorithm_20test_19',['Task 2: Running a Specific Algorithm Test',['../md_guides_2AGENT.html#task-2-running-a-specific-algorithm-test',1,'']]],
  ['algorithms_20',['algorithms',['../instruction_manual.html#core-algorithms',1,'Core Algorithms'],['../instruction_manual.html#the-5-core-algorithms',1,'The 5 Core Algorithms']]],
  ['algorithms_20implemented_21',['Algorithms Implemented',['../md_guides_2AGENT.html#algorithms-implemented',1,'']]],
  ['all_20rvv_20instructions_20—_20tt_20normal_5frvv_20tt_20hits_20tt_20illegalinstfault_20tt_22',['gem5 v24 does not support all RVV instructions — &lt;tt&gt;normal_rvv&lt;/tt&gt; hits &lt;tt&gt;IllegalInstFault&lt;/tt&gt;',['../md_guides_2session__2026-04-07.html#gem5-v24-does-not-support-all-rvv-instructions--normal_rvv-hits-illegalinstfault',1,'']]],
  ['always_20use_20v2_23',['Voxel Grid: Always Use v2',['../md_guides_2AGENT.html#voxel-grid-always-use-v2',1,'']]],
  ['aos_24',['aos',['../structCloudData.html#a1fadd15c76ede456f89f9b7ed630be2a',1,'CloudData']]],
  ['aos_20scalar_20code_25',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['api_20reference_26',['API Reference',['../instruction_manual.html#api-reference',1,'']]],
  ['application_20binary_20interface_27',['3. &lt;tt&gt;-mabi=lp64d&lt;/tt&gt; - Application Binary Interface',['../instruction_manual.html#autotoc_md3--mabilp64d---application-binary-interface',1,'']]],
  ['architecture_28',['architecture',['..//home/runner/work/rvpoint/rvpoint/src/custom_rvv_octree/README.md#autotoc_md1-the-core-architecture',1,'1. The Core Architecture'],['../instruction_manual.html#codebase-architecture',1,'Codebase Architecture'],['../md_guides_2AGENT.html#project-architecture',1,'Project Architecture']]],
  ['architecture_20specification_29',['2. &lt;tt&gt;-march=rv64gcv&lt;/tt&gt; - Architecture Specification',['../instruction_manual.html#autotoc_md2--marchrv64gcv---architecture-specification',1,'']]],
  ['are_5fpoints_5fclose_30',['are_points_close',['../test__voxel__grid_8cpp.html#ad26dac34e77a9711c640f3f7790c95fb',1,'are_points_close(const PointXYZ &amp;a, const PointXYZ &amp;b, float eps=1e-4):&#160;test_voxel_grid.cpp'],['../test__sor_8cpp.html#ad26dac34e77a9711c640f3f7790c95fb',1,'are_points_close(const PointXYZ &amp;a, const PointXYZ &amp;b, float eps=1e-4):&#160;test_sor.cpp'],['../test__voxel__linux_8cpp.html#ad26dac34e77a9711c640f3f7790c95fb',1,'are_points_close(const PointXYZ &amp;a, const PointXYZ &amp;b, float eps=1e-4):&#160;test_voxel_linux.cpp'],['../test__voxel__scaling_8cpp.html#ad26dac34e77a9711c640f3f7790c95fb',1,'are_points_close(const PointXYZ &amp;a, const PointXYZ &amp;b, float eps=1e-4):&#160;test_voxel_scaling.cpp']]],
  ['args_31',['args',['../namespacegem5__se.html#aa90ec32e000cd5205d3cf9ad264eacc7',1,'gem5_se']]],
  ['arian_5fexps_32',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['array_20of_20structures_20aos_20scalar_20code_33',['Array of Structures (AoS) - Scalar Code',['../instruction_manual.html#array-of-structures-aos---scalar-code',1,'']]],
  ['arrays_20soa_20vector_20code_34',['Structure of Arrays (SoA) - Vector Code',['../instruction_manual.html#structure-of-arrays-soa---vector-code',1,'']]],
  ['as_20of_202026_2004_2007_35',['What&apos;s Done (as of 2026-04-07)',['../md_guides_2AGENT.html#whats-done-as-of-2026-04-07',1,'']]],
  ['assembly_36',['Stage 3: Assembly',['../instruction_manual.html#stage-3-assembly',1,'']]],
  ['assoc_37',['assoc',['../namespacegem5__se.html#ab35e7d9f500b84e35ee1cbd8a21041c3',1,'gem5_se']]],
  ['available_20tests_38',['Available tests',['../index.html#available-tests',1,'']]]
];
