var searchData=
[
  ['d_20exec_20nochain_20tt_0',['2. Trace Logging (&lt;tt&gt;-d exec,nochain&lt;/tt&gt;)',['../md_tests_2INSTRUCTION__COUNTING.html#autotoc_md2-trace-logging--d-execnochain',1,'']]],
  ['data_1',['Task 5: Pipeline Walkthrough with Real Data',['../md_guides_2AGENT.html#task-5-pipeline-walkthrough-with-real-data',1,'']]],
  ['data_20generation_2',['Data Generation',['../instruction_manual.html#data-generation',1,'']]],
  ['data_20layout_20critical_20design_20decision_3',['Data Layout (Critical Design Decision)',['../md_guides_2AGENT.html#data-layout-critical-design-decision',1,'']]],
  ['data_20spec_4',['Synthetic data spec',['../md_guides_2AGENT.html#synthetic-data-spec',1,'']]],
  ['data_20structures_5',['data structures',['../instruction_manual.html#data-structures-1',1,'Data Structures'],['../instruction_manual.html#data-structures',1,'Data Structures'],['../md_guides_2AGENT.html#spatial-data-structures',1,'Spatial Data Structures']]],
  ['data_5flatency_6',['data_latency',['../namespacegem5__se.html#af5778a263611b12a58324ae0b5171f13',1,'gem5_se']]],
  ['dcache_7',['dcache',['../namespacegem5__se.html#aaf06a0b5c4d1578cbe32c5074ed1b86c',1,'gem5_se']]],
  ['dcache_5fport_8',['dcache_port',['../namespacegem5__se.html#a58870bf4572e7af90c7bd6572a7cdc4f',1,'gem5_se']]],
  ['debugging_20tips_9',['Debugging Tips',['../instruction_manual.html#debugging-tips',1,'']]],
  ['decision_10',['Data Layout (Critical Design Decision)',['../md_guides_2AGENT.html#data-layout-critical-design-decision',1,'']]],
  ['deep_20dive_11',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['default_12',['default',['../namespacegem5__se.html#a20f20c537d34e4723fdeb9d1ae83a25e',1,'gem5_se']]],
  ['demo_13',['Pipeline Demo */',['../pipeline_demo.html',1,'']]],
  ['demo_20branch_3a_20arian_5fexps_14',['RVV Point Cloud Pipeline Demo (Branch: arian_exps)',['../pipeline_demo.html#rvv-point-cloud-pipeline-demo-branch-arian_exps',1,'']]],
  ['deprecated_20list_15',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20decision_16',['Data Layout (Critical Design Decision)',['../md_guides_2AGENT.html#data-layout-critical-design-decision',1,'']]],
  ['design_20rules_20for_20this_20benchmark_17',['Key design rules for this benchmark',['../md_guides_2AGENT.html#key-design-rules-for-this-benchmark',1,'']]],
  ['desktop_20for_20linux_20uses_20a_20qemu_20vm_20—_20limits_20container_20ram_20to_205_206_20gb_18',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['destructive_20commands_19',['Before Running Destructive Commands',['../md_guides_2AGENT.html#before-running-destructive-commands',1,'']]],
  ['dev_20container_20recommended_20',['Dev Container (Recommended)',['../index.html#dev-container-recommended',1,'']]],
  ['development_20workflow_21',['1. Standardized Development Workflow',['../instruction_manual.html#autotoc_md1-standardized-development-workflow',1,'']]],
  ['directly_22',['Running Commands Inside Container Directly',['../md_guides_2AGENT.html#running-commands-inside-container-directly',1,'']]],
  ['directory_23',['4. &lt;tt&gt;-I src/include&lt;/tt&gt; - Include Directory',['../instruction_manual.html#autotoc_md4--i-srcinclude---include-directory',1,'']]],
  ['discovered_24',['Hard Limits Discovered',['../md_guides_2session__2026-04-07.html#hard-limits-discovered',1,'']]],
  ['distance_20calculation_25',['Distance Calculation',['../instruction_manual.html#distance-calculation',1,'']]],
  ['dive_26',['Compilation Deep Dive',['../instruction_manual.html#compilation-deep-dive',1,'']]],
  ['do_20✅_27',['DO ✅',['../md_guides_2AGENT.html#do-',1,'']]],
  ['docker_20containers_28',['&lt;tt&gt;swapon&lt;/tt&gt; is impossible inside Docker containers',['../md_guides_2session__2026-04-07.html#swapon-is-impossible-inside-docker-containers',1,'']]],
  ['docker_20desktop_20for_20linux_20uses_20a_20qemu_20vm_20—_20limits_20container_20ram_20to_205_206_20gb_29',['Docker Desktop for Linux uses a QEMU VM — limits container RAM to ~5.6 GB',['../md_guides_2session__2026-04-07.html#docker-desktop-for-linux-uses-a-qemu-vm--limits-container-ram-to-56-gb',1,'']]],
  ['docker_20image_20only_20when_20dockerfile_20changes_30',['Building Docker Image (only when Dockerfile changes)',['../md_guides_2AGENT.html#building-docker-image-only-when-dockerfile-changes',1,'']]],
  ['docker_20manual_31',['Docker (Manual)',['../index.html#docker-manual',1,'']]],
  ['dockerfile_20changes_32',['Building Docker Image (only when Dockerfile changes)',['../md_guides_2AGENT.html#building-docker-image-only-when-dockerfile-changes',1,'']]],
  ['documentation_20resources_33',['Documentation &amp; Resources',['../index.html#documentation--resources',1,'']]],
  ['does_34',['What it does',['../md_guides_2AGENT.html#what-it-does',1,'']]],
  ['does_20internally_20complete_20flow_35',['What QEMU Does Internally (Complete Flow)',['../instruction_manual.html#what-qemu-does-internally-complete-flow',1,'']]],
  ['does_20not_20exist_20on_20ubuntu_2022_2004_36',['&lt;tt&gt;mkswap -q&lt;/tt&gt; flag does not exist on Ubuntu 22.04',['../md_guides_2session__2026-04-07.html#mkswap--q-flag-does-not-exist-on-ubuntu-2204',1,'']]],
  ['does_20not_20support_20all_20rvv_20instructions_20—_20tt_20normal_5frvv_20tt_20hits_20tt_20illegalinstfault_20tt_37',['gem5 v24 does not support all RVV instructions — &lt;tt&gt;normal_rvv&lt;/tt&gt; hits &lt;tt&gt;IllegalInstFault&lt;/tt&gt;',['../md_guides_2session__2026-04-07.html#gem5-v24-does-not-support-all-rvv-instructions--normal_rvv-hits-illegalinstfault',1,'']]],
  ['don_20t_20❌_38',['DON&apos;T ❌',['../md_guides_2AGENT.html#dont-',1,'']]],
  ['done_20as_20of_202026_2004_2007_39',['What&apos;s Done (as of 2026-04-07)',['../md_guides_2AGENT.html#whats-done-as-of-2026-04-07',1,'']]],
  ['done_20this_20session_40',['Work Done This Session',['../md_guides_2session__2026-04-07.html#work-done-this-session',1,'']]],
  ['downsampling_20strong_41',['&lt;strong&gt;Voxel Grid Downsampling&lt;/strong&gt;',['../instruction_manual.html#voxel-grid-downsampling',1,'']]],
  ['dram_42',['dram',['../namespacegem5__se.html#ab768cf97be39ce84ed2c4298d3be24c3',1,'gem5_se']]],
  ['dualstream_43',['DualStream',['../structDualStream.html',1,'']]]
];
