set(CMAKE_SYSTEM_NAME Linux)

# Detect if compiling natively on RISC-V host (e.g. Orange Pi RV2 / SpacemiT K1)
if(CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "riscv" OR CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "rv64")
    set(CMAKE_SYSTEM_PROCESSOR "${CMAKE_HOST_SYSTEM_PROCESSOR}")
    set(IS_NATIVE_RISCV TRUE)
else()
    set(CMAKE_SYSTEM_PROCESSOR riscv)
    set(IS_NATIVE_RISCV FALSE)
endif()

if(IS_NATIVE_RISCV)
    if(DEFINED ENV{CC} AND NOT "$ENV{CC}" STREQUAL "")
        set(CMAKE_C_COMPILER "$ENV{CC}")
    elseif(EXISTS "/usr/bin/gcc")
        set(CMAKE_C_COMPILER "/usr/bin/gcc")
    else()
        find_program(CMAKE_C_COMPILER NAMES gcc riscv64-linux-gnu-gcc riscv64-unknown-linux-gnu-gcc)
    endif()

    if(DEFINED ENV{CXX} AND NOT "$ENV{CXX}" STREQUAL "")
        set(CMAKE_CXX_COMPILER "$ENV{CXX}")
    elseif(EXISTS "/usr/bin/g++")
        set(CMAKE_CXX_COMPILER "/usr/bin/g++")
    else()
        find_program(CMAKE_CXX_COMPILER NAMES g++ riscv64-linux-gnu-g++ riscv64-unknown-linux-gnu-g++)
    endif()

    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
else()
    # Cross-compilation from x86_64 host
    if(DEFINED ENV{RISCV_PATH} AND EXISTS "$ENV{RISCV_PATH}/bin/riscv64-unknown-linux-gnu-gcc")
        set(RISCV_PATH "$ENV{RISCV_PATH}")
    elseif(EXISTS "/opt/riscv/bin/riscv64-unknown-linux-gnu-gcc")
        set(RISCV_PATH "/opt/riscv")
    else()
        set(RISCV_PATH "/opt/riscv")
    endif()

    set(CMAKE_C_COMPILER "${RISCV_PATH}/bin/riscv64-unknown-linux-gnu-gcc")
    set(CMAKE_CXX_COMPILER "${RISCV_PATH}/bin/riscv64-unknown-linux-gnu-g++")

    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

if(NOT DEFINED RISCV_ARCH)
    set(RISCV_ARCH "rv64gcv")
endif()
if(NOT DEFINED RISCV_ABI)
    set(RISCV_ABI "lp64d")
endif()

set(CMAKE_C_FLAGS "-march=${RISCV_ARCH} -mabi=${RISCV_ABI}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-march=${RISCV_ARCH} -mabi=${RISCV_ABI}" CACHE STRING "" FORCE)

